package jobs

import (
	"bytes"
	"fmt"
	"strings"
)

// The UI mirrors of errors.go and events.go. cmd/gen-uicontract writes
// them (go generate ./jobs); TestUIContractInSync fails when the checked-in
// files differ from what these render.

// UIContractFiles maps a path relative to the repository root to its
// renderer.
var UIContractFiles = map[string]func() []byte{
	"ui/src/apps/backup/errorCodes.js": RenderErrorCodesJS,
	"ui/src/apps/backup/events.js":     RenderEventsJS,
}

const generatedHeader = "// GENERATED by services/backup/cmd/gen-uicontract from services/backup/jobs/%s.\n" +
	"// Do not edit: change the Go file, then run `go generate ./jobs` in services/backup.\n"

func jsString(s string) string {
	return "'" + strings.NewReplacer(`\`, `\\`, `'`, `\'`).Replace(s) + "'"
}

func jsList(items []string) string {
	quoted := make([]string, len(items))
	for i, s := range items {
		quoted[i] = jsString(s)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

// writeRows ends an object literal opened by the caller: one row per
// line, comma separated, no trailing comma (the UI's style).
func writeRows(b *bytes.Buffer, rows []string) {
	b.WriteString(strings.Join(rows, ",\n"))
	b.WriteString("\n})\n\n")
}

// RenderErrorCodesJS renders ui/src/apps/backup/errorCodes.js.
func RenderErrorCodesJS() []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, generatedHeader, "errors.go")
	b.WriteString(`//
// Every error_code the backend can send, with its retry class and the
// one-click fixes (actions) the UI offers for it. Explain a code with
// backup.err.<code>.title / .cause / .fix and label an action with
// backup.action.<action>.

export const ERROR_CODES = Object.freeze({
`)
	var rows []string
	for _, c := range AllErrorCodes() {
		info, _ := Info(c)
		actions := make([]string, len(info.Actions))
		for i, a := range info.Actions {
			actions[i] = string(a)
		}
		rows = append(rows, fmt.Sprintf("\t%s: Object.freeze({ class: %s, actions: Object.freeze(%s) })", string(c), jsString(string(info.Class)), jsList(actions)))
	}
	writeRows(&b, rows)

	classes := []string{string(ClassTransient), string(ClassDeferred), string(ClassGuard), string(ClassConfig), string(ClassHook), string(ClassLifecycle), string(ClassAPI)}
	fmt.Fprintf(&b, "export const ERROR_CLASSES = Object.freeze(%s)\n\n", jsList(classes))

	actions := AllActions()
	names := make([]string, len(actions))
	for i, a := range actions {
		names[i] = string(a)
	}
	fmt.Fprintf(&b, "export const ACTIONS = Object.freeze(%s)\n\n", jsList(names))

	fields := make([]string, len(AllFieldCodes))
	for i, f := range AllFieldCodes {
		fields[i] = string(f)
	}
	b.WriteString("// Values of a 400 response's field_errors besides error codes; label\n")
	b.WriteString("// them with backup.field.<code>.\n")
	fmt.Fprintf(&b, "export const FIELD_CODES = Object.freeze(%s)\n\n", jsList(fields))

	b.WriteString(`// errorInfo returns {class, actions} for a code; unknown codes are
// treated as internal, like the backend does.
export function errorInfo(code) {
	return ERROR_CODES[code] || ERROR_CODES.internal
}

// errorKeys returns the i18n keys explaining a code.
export function errorKeys(code) {
	const c = ERROR_CODES[code] ? code : 'internal'
	return {
		title: ` + "`backup.err.${c}.title`" + `,
		cause: ` + "`backup.err.${c}.cause`" + `,
		fix: ` + "`backup.err.${c}.fix`" + `
	}
}

// fieldErrorKey returns the i18n key for a field_errors value.
export function fieldErrorKey(value) {
	if (FIELD_CODES.includes(value)) return ` + "`backup.field.${value}`" + `
	return errorKeys(value).title
}
`)
	return b.Bytes()
}

// RenderEventsJS renders ui/src/apps/backup/events.js.
func RenderEventsJS() []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, generatedHeader, "events.go")
	b.WriteString(`//
// Message-bus events, received through this.$socket (vue-socket.io-extended)
// as { Properties: { ... } } with every property a string.

export const BACKUP_EVENTS = Object.freeze({
`)
	var rows []string
	for _, e := range []struct{ name, value string }{
		{"RUN_BEGIN", EventRunBegin}, {"RUN_PROGRESS", EventRunProgress}, {"RUN_END", EventRunEnd},
		{"RUN_WAITING", EventRunWaiting}, {"JOB_CHANGED", EventJobChanged}, {"NOTIFY", EventNotify},
	} {
		rows = append(rows, fmt.Sprintf("\t%s: %s", e.name, jsString(e.value)))
	}
	writeRows(&b, rows)
	b.WriteString("// Properties sent with each event.\nexport const EVENT_PROPERTIES = Object.freeze({\n")
	rows = rows[:0]
	for _, et := range EventTypes() {
		props := make([]string, len(et.PropertyTypeList))
		for i, p := range et.PropertyTypeList {
			props[i] = p.Name
		}
		rows = append(rows, fmt.Sprintf("\t%s: Object.freeze(%s)", jsString(et.Name), jsList(props)))
	}
	writeRows(&b, rows)
	fmt.Fprintf(&b, "export const JOB_CHANGE = Object.freeze({ CREATED: %s, UPDATED: %s, DELETED: %s, TOGGLED: %s })\n",
		jsString(JobChangeCreated), jsString(JobChangeUpdated), jsString(JobChangeDeleted), jsString(JobChangeToggled))
	return b.Bytes()
}
