// Package codegen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package codegen

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

const (
	Access_tokenScopes = "access_token.Scopes"
)

// Defines values for NotificationCategory.
const (
	App     NotificationCategory = "app"
	Backup  NotificationCategory = "backup"
	Storage NotificationCategory = "storage"
	System  NotificationCategory = "system"
)

// Defines values for NotificationLevel.
const (
	Error   NotificationLevel = "error"
	Info    NotificationLevel = "info"
	Success NotificationLevel = "success"
	Warning NotificationLevel = "warning"
)

// Action defines model for Action.
type Action struct {
	// Name action name
	Name string `json:"name"`

	// Properties event properties
	Properties map[string]string `json:"properties"`

	// SourceID associated source id
	SourceID string `json:"sourceID"`

	// Timestamp timestamp this action took place
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// ActionType defines model for ActionType.
type ActionType struct {
	// Name action name
	//
	// (there is no naming convention for action names, but it is recommended to name each as structural and descriptive as possible)
	Name             string         `json:"name"`
	PropertyTypeList []PropertyType `json:"propertyTypeList"`

	// SourceID action source id to identify where the action will take
	SourceID string `json:"sourceID"`
}

// BaseResponse defines model for BaseResponse.
type BaseResponse struct {
	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// Event defines model for Event.
type Event struct {
	// Name event name
	Name string `json:"name"`

	// Properties event properties
	Properties map[string]string `json:"properties"`

	// SourceID associated source id
	SourceID string `json:"sourceID"`

	// Timestamp timestamp this event took place
	Timestamp *time.Time `json:"timestamp,omitempty"`

	// Uuid event uuid
	Uuid *string `json:"uuid,omitempty"`
}

// EventType defines model for EventType.
type EventType struct {
	// Name event name
	//
	// (there is no naming convention for event names, but it is recommended to name each as structural and descriptive as possible)
	Name             string         `json:"name"`
	PropertyTypeList []PropertyType `json:"propertyTypeList"`

	// SourceID event source id to identify where the event comes from
	SourceID string `json:"sourceID"`
}

// Notification defines model for Notification.
type Notification struct {
	// Action What opening it does (absent when nothing). `target` names the place (`backup`: `window` is a
	// Backup & Sync window `{kind, props}`; `settings`: `props.section`).
	Action *map[string]interface{} `json:"action,omitempty"`

	// Args arguments for `key`
	Args     map[string]interface{} `json:"args"`
	Category NotificationCategory   `json:"category"`

	// EventName name of the event it came from
	EventName string `json:"event_name"`

	// Icon icon URL ("" when none)
	Icon string `json:"icon"`

	// Id feed id; ids only ever grow
	Id int64 `json:"id"`

	// Key i18n key a client can render (with `args`) instead of `message` ("" when none)
	Key   string            `json:"key"`
	Level NotificationLevel `json:"level"`

	// Message English text
	Message string `json:"message"`

	// Read whether the caller has read it
	Read bool `json:"read"`

	// SourceId source of the event it came from
	SourceId string    `json:"source_id"`
	Time     time.Time `json:"time"`

	// Title English title
	Title string `json:"title"`
}

// NotificationCategory defines model for Notification.Category.
type NotificationCategory string

// NotificationLevel defines model for Notification.Level.
type NotificationLevel string

// NotificationCount defines model for NotificationCount.
type NotificationCount struct {
	UnreadCount int64 `json:"unread_count"`
}

// NotificationList defines model for NotificationList.
type NotificationList struct {
	Data []Notification `json:"data"`

	// HasMore more matching entries exist, older than the last one returned
	HasMore bool `json:"has_more"`

	// LatestId the newest entry the caller can see (0 when none)
	LatestId int64 `json:"latest_id"`

	// UnreadCount the caller's unread entries in the whole feed
	UnreadCount int64 `json:"unread_count"`
}

// NotificationSelection defines model for NotificationSelection.
type NotificationSelection struct {
	// All every entry up to `up_to` instead of `ids`
	All *bool    `json:"all,omitempty"`
	Ids *[]int64 `json:"ids,omitempty"`

	// UpTo with `all`, the newest id it applies to (default and maximum - the newest that exists)
	UpTo *int64 `json:"up_to,omitempty"`
}

// PropertyType defines model for PropertyType.
type PropertyType struct {
	Description *string `json:"description,omitempty"`
	Example     *string `json:"example,omitempty"`

	// Name property name
	//
	// > It is recommended for a property name to be as descriptive as possible. One option is to prefix with a namespace.
	// > - If the property is source specific, prefix with source ID. For example, `local-storage:vendor`
	// > - Otherwise, prefix with `common:`. For example, `common:email`
	// >
	// > Some bad examples are `id`, `avail`, `blk`...which can be ambiguous and confusing.
	Name string `json:"name"`
}

// ActionName defines model for ActionName.
type ActionName = string

// ActionNames defines model for ActionNames.
type ActionNames = []string

// EventName defines model for EventName.
type EventName = string

// EventNames defines model for EventNames.
type EventNames = []string

// SourceID defines model for SourceID.
type SourceID = string

// GetActionTypeOK defines model for GetActionTypeOK.
type GetActionTypeOK = ActionType

// GetActionTypesOK defines model for GetActionTypesOK.
type GetActionTypesOK = []ActionType

// GetEventTypeOK defines model for GetEventTypeOK.
type GetEventTypeOK = EventType

// GetEventTypesOK defines model for GetEventTypesOK.
type GetEventTypesOK = []EventType

// GetNotificationsOK defines model for GetNotificationsOK.
type GetNotificationsOK = NotificationList

// NotificationCountOK defines model for NotificationCountOK.
type NotificationCountOK = NotificationCount

// PublishEventOK defines model for PublishEventOK.
type PublishEventOK = Event

// ResponseBadRequest defines model for ResponseBadRequest.
type ResponseBadRequest = BaseResponse

// ResponseConflict defines model for ResponseConflict.
type ResponseConflict = BaseResponse

// ResponseInternalServerError defines model for ResponseInternalServerError.
type ResponseInternalServerError = BaseResponse

// ResponseNotFound defines model for ResponseNotFound.
type ResponseNotFound = BaseResponse

// ResponseOK defines model for ResponseOK.
type ResponseOK = BaseResponse

// ResponseServiceUnavailable defines model for ResponseServiceUnavailable.
type ResponseServiceUnavailable = BaseResponse

// TriggerActionOK defines model for TriggerActionOK.
type TriggerActionOK = Action

// NotificationSelectionBody defines model for NotificationSelectionBody.
type NotificationSelectionBody = NotificationSelection

// PublishEvent event properties
type PublishEvent map[string]string

// RegisterActionTypes defines model for RegisterActionTypes.
type RegisterActionTypes = []ActionType

// RegisterEventTypes defines model for RegisterEventTypes.
type RegisterEventTypes = []EventType

// TriggerAction action properties
type TriggerAction map[string]string

// SubscribeActionWSParams defines parameters for SubscribeActionWS.
type SubscribeActionWSParams struct {
	Names *ActionNames `form:"names,omitempty" json:"names,omitempty"`
}

// TriggerActionJSONBody defines parameters for TriggerAction.
type TriggerActionJSONBody map[string]string

// RegisterActionTypesJSONBody defines parameters for RegisterActionTypes.
type RegisterActionTypesJSONBody = []ActionType

// SubscribeEventWSParams defines parameters for SubscribeEventWS.
type SubscribeEventWSParams struct {
	Names *EventNames `form:"names,omitempty" json:"names,omitempty"`
}

// PublishEventJSONBody defines parameters for PublishEvent.
type PublishEventJSONBody map[string]string

// RegisterEventTypesJSONBody defines parameters for RegisterEventTypes.
type RegisterEventTypesJSONBody = []EventType

// GetNotificationsParams defines parameters for GetNotifications.
type GetNotificationsParams struct {
	// After only entries with an id greater than this
	After *int64 `form:"after,omitempty" json:"after,omitempty"`

	// Before only entries with an id smaller than this
	Before *int64 `form:"before,omitempty" json:"before,omitempty"`

	// Limit page size (default 50)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Unread only unread entries
	Unread *bool `form:"unread,omitempty" json:"unread,omitempty"`
}

// TriggerActionJSONRequestBody defines body for TriggerAction for application/json ContentType.
type TriggerActionJSONRequestBody TriggerActionJSONBody

// RegisterActionTypesJSONRequestBody defines body for RegisterActionTypes for application/json ContentType.
type RegisterActionTypesJSONRequestBody = RegisterActionTypesJSONBody

// PublishEventJSONRequestBody defines body for PublishEvent for application/json ContentType.
type PublishEventJSONRequestBody PublishEventJSONBody

// RegisterEventTypesJSONRequestBody defines body for RegisterEventTypes for application/json ContentType.
type RegisterEventTypesJSONRequestBody = RegisterEventTypesJSONBody

// DismissNotificationsJSONRequestBody defines body for DismissNotifications for application/json ContentType.
type DismissNotificationsJSONRequestBody = NotificationSelection

// MarkNotificationsReadJSONRequestBody defines body for MarkNotificationsRead for application/json ContentType.
type MarkNotificationsReadJSONRequestBody = NotificationSelection

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Subscribe to actions by source ID (WebSocket)
	// (GET /action/{source_id})
	SubscribeActionWS(ctx echo.Context, sourceId SourceID, params SubscribeActionWSParams) error
	// Trigger an action
	// (POST /action/{source_id}/{name})
	TriggerAction(ctx echo.Context, sourceId SourceID, name ActionName) error
	// List action types
	// (GET /action_type)
	GetActionTypes(ctx echo.Context) error
	// Register one or more action types
	// (POST /action_type)
	RegisterActionTypes(ctx echo.Context) error
	// Get action types by source ID
	// (GET /action_type/{source_id})
	GetActionTypesBySourceID(ctx echo.Context, sourceId SourceID) error
	// Get an action type by source ID and name
	// (GET /action_type/{source_id}/{name})
	GetActionType(ctx echo.Context, sourceId SourceID, name ActionName) error
	// Subscribe to events by source ID (WebSocket)
	// (GET /event/{source_id})
	SubscribeEventWS(ctx echo.Context, sourceId SourceID, params SubscribeEventWSParams) error
	// Publish an event
	// (POST /event/{source_id}/{name})
	PublishEvent(ctx echo.Context, sourceId SourceID, name EventName) error
	// List event types
	// (GET /event_type)
	GetEventTypes(ctx echo.Context) error
	// Register one or more event types
	// (POST /event_type)
	RegisterEventTypes(ctx echo.Context) error
	// Get event types by source ID
	// (GET /event_type/{source_id})
	GetEventTypesBySourceID(ctx echo.Context, sourceId SourceID) error
	// Get an event type by source ID and name
	// (GET /event_type/{source_id}/{name})
	GetEventType(ctx echo.Context, sourceId SourceID, name EventName) error
	// List the caller's notification feed
	// (GET /notifications)
	GetNotifications(ctx echo.Context, params GetNotificationsParams) error
	// Dismiss notifications
	// (POST /notifications/dismiss)
	DismissNotifications(ctx echo.Context) error
	// Mark notifications read
	// (POST /notifications/read)
	MarkNotificationsRead(ctx echo.Context) error
	// Subscribe to events and actions (SocketIO)
	// (GET /socket.io)
	SubscribeSIO(ctx echo.Context) error
	// Poll events and actions (SocketIO)
	// (POST /socket.io)
	PollSIO(ctx echo.Context) error
	// Subscribe to events and actions (SocketIO)
	// (GET /socket.io/)
	SubscribeSIO2(ctx echo.Context) error
	// Poll events and actions (SocketIO)
	// (POST /socket.io/)
	PollSIO2(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// SubscribeActionWS converts echo context to params.
func (w *ServerInterfaceWrapper) SubscribeActionWS(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceID

	err = runtime.BindStyledParameterWithLocation("simple", false, "source_id", runtime.ParamLocationPath, ctx.Param("source_id"), &sourceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params SubscribeActionWSParams
	// ------------- Optional query parameter "names" -------------

	err = runtime.BindQueryParameter("form", true, false, "names", ctx.QueryParams(), &params.Names)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter names: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SubscribeActionWS(ctx, sourceId, params)
	return err
}

// TriggerAction converts echo context to params.
func (w *ServerInterfaceWrapper) TriggerAction(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceID

	err = runtime.BindStyledParameterWithLocation("simple", false, "source_id", runtime.ParamLocationPath, ctx.Param("source_id"), &sourceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name ActionName

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, ctx.Param("name"), &name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.TriggerAction(ctx, sourceId, name)
	return err
}

// GetActionTypes converts echo context to params.
func (w *ServerInterfaceWrapper) GetActionTypes(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetActionTypes(ctx)
	return err
}

// RegisterActionTypes converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterActionTypes(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RegisterActionTypes(ctx)
	return err
}

// GetActionTypesBySourceID converts echo context to params.
func (w *ServerInterfaceWrapper) GetActionTypesBySourceID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceID

	err = runtime.BindStyledParameterWithLocation("simple", false, "source_id", runtime.ParamLocationPath, ctx.Param("source_id"), &sourceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetActionTypesBySourceID(ctx, sourceId)
	return err
}

// GetActionType converts echo context to params.
func (w *ServerInterfaceWrapper) GetActionType(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceID

	err = runtime.BindStyledParameterWithLocation("simple", false, "source_id", runtime.ParamLocationPath, ctx.Param("source_id"), &sourceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name ActionName

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, ctx.Param("name"), &name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetActionType(ctx, sourceId, name)
	return err
}

// SubscribeEventWS converts echo context to params.
func (w *ServerInterfaceWrapper) SubscribeEventWS(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceID

	err = runtime.BindStyledParameterWithLocation("simple", false, "source_id", runtime.ParamLocationPath, ctx.Param("source_id"), &sourceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params SubscribeEventWSParams
	// ------------- Optional query parameter "names" -------------

	err = runtime.BindQueryParameter("form", true, false, "names", ctx.QueryParams(), &params.Names)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter names: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SubscribeEventWS(ctx, sourceId, params)
	return err
}

// PublishEvent converts echo context to params.
func (w *ServerInterfaceWrapper) PublishEvent(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceID

	err = runtime.BindStyledParameterWithLocation("simple", false, "source_id", runtime.ParamLocationPath, ctx.Param("source_id"), &sourceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name EventName

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, ctx.Param("name"), &name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PublishEvent(ctx, sourceId, name)
	return err
}

// GetEventTypes converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventTypes(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetEventTypes(ctx)
	return err
}

// RegisterEventTypes converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterEventTypes(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RegisterEventTypes(ctx)
	return err
}

// GetEventTypesBySourceID converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventTypesBySourceID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceID

	err = runtime.BindStyledParameterWithLocation("simple", false, "source_id", runtime.ParamLocationPath, ctx.Param("source_id"), &sourceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetEventTypesBySourceID(ctx, sourceId)
	return err
}

// GetEventType converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventType(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceID

	err = runtime.BindStyledParameterWithLocation("simple", false, "source_id", runtime.ParamLocationPath, ctx.Param("source_id"), &sourceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name EventName

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, ctx.Param("name"), &name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetEventType(ctx, sourceId, name)
	return err
}

// GetNotifications converts echo context to params.
func (w *ServerInterfaceWrapper) GetNotifications(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetNotificationsParams
	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameter("form", true, false, "after", ctx.QueryParams(), &params.After)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter after: %s", err))
	}

	// ------------- Optional query parameter "before" -------------

	err = runtime.BindQueryParameter("form", true, false, "before", ctx.QueryParams(), &params.Before)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter before: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "unread" -------------

	err = runtime.BindQueryParameter("form", true, false, "unread", ctx.QueryParams(), &params.Unread)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter unread: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetNotifications(ctx, params)
	return err
}

// DismissNotifications converts echo context to params.
func (w *ServerInterfaceWrapper) DismissNotifications(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DismissNotifications(ctx)
	return err
}

// MarkNotificationsRead converts echo context to params.
func (w *ServerInterfaceWrapper) MarkNotificationsRead(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.MarkNotificationsRead(ctx)
	return err
}

// SubscribeSIO converts echo context to params.
func (w *ServerInterfaceWrapper) SubscribeSIO(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SubscribeSIO(ctx)
	return err
}

// PollSIO converts echo context to params.
func (w *ServerInterfaceWrapper) PollSIO(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PollSIO(ctx)
	return err
}

// SubscribeSIO2 converts echo context to params.
func (w *ServerInterfaceWrapper) SubscribeSIO2(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SubscribeSIO2(ctx)
	return err
}

// PollSIO2 converts echo context to params.
func (w *ServerInterfaceWrapper) PollSIO2(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PollSIO2(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/action/:source_id", wrapper.SubscribeActionWS)
	router.POST(baseURL+"/action/:source_id/:name", wrapper.TriggerAction)
	router.GET(baseURL+"/action_type", wrapper.GetActionTypes)
	router.POST(baseURL+"/action_type", wrapper.RegisterActionTypes)
	router.GET(baseURL+"/action_type/:source_id", wrapper.GetActionTypesBySourceID)
	router.GET(baseURL+"/action_type/:source_id/:name", wrapper.GetActionType)
	router.GET(baseURL+"/event/:source_id", wrapper.SubscribeEventWS)
	router.POST(baseURL+"/event/:source_id/:name", wrapper.PublishEvent)
	router.GET(baseURL+"/event_type", wrapper.GetEventTypes)
	router.POST(baseURL+"/event_type", wrapper.RegisterEventTypes)
	router.GET(baseURL+"/event_type/:source_id", wrapper.GetEventTypesBySourceID)
	router.GET(baseURL+"/event_type/:source_id/:name", wrapper.GetEventType)
	router.GET(baseURL+"/notifications", wrapper.GetNotifications)
	router.POST(baseURL+"/notifications/dismiss", wrapper.DismissNotifications)
	router.POST(baseURL+"/notifications/read", wrapper.MarkNotificationsRead)
	router.GET(baseURL+"/socket.io", wrapper.SubscribeSIO)
	router.POST(baseURL+"/socket.io", wrapper.PollSIO)
	router.GET(baseURL+"/socket.io/", wrapper.SubscribeSIO2)
	router.POST(baseURL+"/socket.io/", wrapper.PollSIO2)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xc63LbuJJ+lS7uVo29RV2SeGbPaGpqazKZi2tm4lScU/kRpUyIbEk4JgEeALSsSfnv",
	"PsA+4j7JFhq8gCJlSbbibJ2aX4lJAN3o/voGNPUpiGWWS4HC6GDyKciZYhkaVPTXD7HhUrxmGdq/uAgm",
	"Qc7MMggDQc/cP2Gg8J8FV5gEE6MKDAMdLzFjdg7esixP7dBUxiwdaCMVW+AkZ8pwu/hkLlXGTBAGZp3b",
	"cdooLhbB3V3okdeHrBVue53JQlhKtJF/FqjW7Z3owGedG8yI7gZjNadMKbYmRn+6QWE+h5gSrq8nLEkw",
	"6RVQTVfvt0jY80JhJm9o/aOL5VIWKsbzV1ukoun1FU8eIpoeedy5ZVCblzLhTiavpeFzHjOr/0tMkRD1",
	"UiZr+zKWwqAw9r8sz9Ny2OgfWgr7rOHh3xXOg0nwb6PGWEburR71Umi4aTZ1FwZvilnK9ZLUdhADLEkI",
	"wix9o2SOypTb6+ggQR0rnhMPkwAtIcibKWEjzk8bKMlkgmkwCX5UxZ+ognDjdVHwJJgEZ2fPcYxfzwbf",
	"Ji9wcDbHvw1mZ9/MB9/GZ8/Ons0TjJP/7My9QZFIFUyCSyZecX3tgUXO/oGxceJq837y7uLVxWnQI8W3",
	"uODaoHLu4d06d7LYW5g1gu9Ta7N4D7QfwCzp/DPxWq/9OFbfKb5YVGJ9CngyorQnPg8B4GPwRXarcym0",
	"28MvaBosXPx2NL/hA6zL3cVvdhMt2vpA4p8B5jVXNeKOKBAPxftQ/iziOMiSap78EKCPKBF/3d+5NtuZ",
	"8Ef+aLOcz8QFrb2dDT++HRsZ26m+Lc31JUveuvi/B2XPz2Sotc0oJsFLlkC1xF24J3cvmcaKhT4mNxat",
	"hv4oxTzl8YN5recfjVF/xWrcuTCoBEsvUd2g+kkpG8ePpNZd/JQe2uPmtTQ/y0IkD5XZa2nALXA0obWW",
	"rAYeEfu76LdNwKqJx/h3wW4YT9nMCeBJGClJg0cbTswSQXj+A+aICXAtvjJQDyMVt5KPo4fZbZKrYeCV",
	"u1QGt9IYUVZ2vdlLWdvdW3xtq3HDDUL/8ml+WBZ9ribckKfWMubMYAJuEFBluHf9FwaGZ6gNy/Lu4vUr",
	"MEuuodSdkfIa8pTFdrlSSZMgYQYHdkJvzd2kix+azYRVie8p4WPP7r1063CUTcVUWItSCFyDkPYhFwuI",
	"pbAAIPOSCrwZOoRZYYAbO0FhLLMMRYIJGJqMgCxeAtOgjSpiUyiWAhMJ1CzcoH2bS605Gepjcb62W6dU",
	"Zt+M7I03sZuU3YsnJ4caS3bTPLGCmq9hRWK07qkctuJpCoZd4yGQ2xcOzbb7QNHyrB1Y1NFrc3/lC1Bo",
	"CiUwgdkaNIVp0DxB4HOowcLEurUvKntYciHSdXXi0nOaUp9T7ANU54T28YZbzrP+coZfyBk6iR3sC8PA",
	"yacfCPTOZ3hPKR7Z4TYF3cEw3tPdNhOe2tvusqOndLZOCrt8rRsVyww1zJXMnt7X+sVsFxKsTgD7nY/z",
	"lO2dv18yAzJHYbHBDSQSNZywmbZbXS1R2AR4ycXidAiRYWqBJnJwIZGQxcFJNGPxdZFHE4hWXCRyFZHb",
	"noqX9BymxXj8/Bu4XIsY3ACIPl1zkYTk6vRd9B1EGo3hYqHtKvR0qN1xdHQ6nIqgRxxMLfRh22VqUWQW",
	"NAT+6BrXUd/CMTO4kIqO2VEUmVWZ22IQ2mw+CING03qtDWaevhooE2Ku+k2VbErOPWRxA7F92MGW4DdM",
	"SaknjocJ1STrPtvhsQNAm5R9Cn9/+zucTINpUKlVkI12l+hxiq7uSb4DnmiQIl1bjhUslFz5jJ4993wv",
	"F+abs4YAFwYXqCyFa1z38PjsbwKucQ0M4pSToTEByrogBScrbpYQWX1Hp8CFNsgSK7yoTCOivq01AnRy",
	"Gzq5DeeMp/2uJ8UbG1EbpXMxl1bFRRyjtsF4xZQ1Fbs6nSb0aX1rzvOTWKRcL8HgrWnx90rGJSz/97//",
	"B36RcpEivFLWpTpmJ6D5Qgy4ALzNrRMZ9rFvk6Iu1dUSbRwgoMUsTVHBklkXzxLgXro7kzJFJhpPedUH",
	"hdJJHgbcQW08vYHeUtkvZhtu0vsES699DroOaKdvpshfMuBf8nnG7HmICjQVb436HdBLL1WaZqmjXb7d",
	"HVR2HHwh7OyruHq709Y2dtaav4uHKvS2WUiY2f88uhWuegLykumrTKq+6kAqhIyZ2IYeQGEURw14y7UJ",
	"QaYJwZkJwmDKtAEpmlKiF9IpM6hNL6TpmAdXqA1RWvuWYp2QRoSTcdu37OHmNrXVJepofKXBDa33yd3G",
	"VkuZIp057UNwQ9ekqA0mfCl40t+FhOZeuJtypGlvNqXWpSiL3CZTUZFfGRm1PDdPdNSrKZ7oFsL2EHXG",
	"bs/d8Gfj8bgLNCLf4xldVEnTKAQPBNz6RaBDO5vmSDhJcM6K1FC+m7FbnhUZDPwpxqZRBE/di46MCzsp",
	"mIx7FdcRfyuV7Rqhvwu/x+BXppIVUwiufnNemtuUfWuh5VWXzTpV1dczvj+ZqbLXuvSwDvcFwnmnmqAz",
	"HmiNtyKeUfGwpZYYwoVAkETMrmck5Arn/BZIg8wlpDmLcVhTHsC5C1E1KSsHF7x0jrFFd9hapnx5/moI",
	"P9vKyEkjhKivNI48Qhc2vK64xvZ6kd20FJNoc73yOWaMp/U69XqXMkOYWW/gJmiwCo14EoUQ0amz/c8s",
	"vY6Gw+FqyeMlOSkrwGzGF4UsNOE0lmJeaC4Ww3sqsbLO3xUSSeldN2EzBYwLxc360rr8qgyxudKVkdfY",
	"k4v+IMANABoQgmIrsJjQEL1EplBRsH4R02snk2gI73F2KeNrdDao6b9DLqdCF7N6eQ0ZW0POtCYD1hD9",
	"F63yfeN5TmZKrjQqbYX2lQGNZiqWyBL7SApgDaWy6qDWHzeiaf75oTBLqfifLrQ1Difnv2F520qpY2f7",
	"rykjuriEP8rzr5dWXXGMuSmPMpz2XC3n6ky4YYpbtTqE6rLsTvmNZdosMbMWUQpihkpbKxAWc1zrohrP",
	"dVxobRcNIU+RaYQbrrkhI/nwCze/FjNQmEvNjVTrjydLY3I9GY0W3CyL2TCW2ejnAQ7EYD24HVX7qEoz",
	"l5f1b++HN+dBGFhmnQxunltHYotOlvNgErwYjocvbAnMzJIQNHK7H32q0687+3iBPXH0stq2lUEltdka",
	"onpuBDfcU+vQc08ROY6oMqDSL9hax0VgaicDZxQtGdMfpRepj+PXOWonDutxCBrnic+iOz9/f0l7bToV",
	"P/RnUc2QUd2KdhfuHOu3Hd593GgHeTZ+1hXhO5uKSCHQO0ueIRT5QrHyAMiTnz/UAosSGVex0UyFMZL/",
	"LnXBCKJr8mLGXZNhYsVE7qPIMmbr7K16rL0ynDSWaRHHbO3/IWj4+kkkueTC6OCjXboHRKNPVt+EpVzq",
	"HjCV13jARKVU6YBQnVbPil4Nt3uPnka7pXKrjsH1tmS81VQ4anO62S30fDzevkw5brR513kXBmf7zOtp",
	"dKCpZ/tPrW/Q29jpqM3Dh2MTMjRLmbShcWXK7KrXsdj6B1iatszbJXoWynGhFAqTrkGVPXKYuLi/B17a",
	"nVHBQ7TQaa5qi8Rx73HeEYmd54kl3GISVQcgVVhSAVVmAldtsey78b7mxweguG+ZB2HZa3l4LIy/3X9q",
	"06rS0lmvqA/R4Qa094qfv+B9KN+B7TKbryNhk0LvBP3L9WVzBv5Qf/nxOJZzHC9EkvSl6EevR6jOi1rb",
	"NSh80k5/VHg9TH1eCkq11U51Pm3Me5TGj6zwtuBbCYsVYnlcuFP3lPofnvC689enTXfLC9ed2S5dXn7m",
	"ZNf7hORL5rpV4ealurlrJt2Z6pZTH5XpdsCzM9EtW10tfKv7833Cd+sLkCfR68Oy3BafD0oMNnqBv3yO",
	"u6kxDxjEZJ8/2TPB9Qz6ePmt98XIA112q1f+Lgy+PkQBfZ2/PRmyt/VNgT42P/alemh6vCG8B2bH3ir/",
	"osnx/upr28RBmXGveRw5MW5U9UXz4k2TO1aW5ItwS1Z8mNL2zIkbusdJiZtuqV16fNLo+BhNHz0d9mS+",
	"KxvepnO/515v1fE7/wZ1jpiE1W3cnCttQtKvLNwBd3W1SvlZwnXGtabcbCoG8EamKSle4Kp01hGbG1QR",
	"fE+zl3yxtAtHNr3WiAK0hDlTcNJtiDkd0pKEJxZfl8vNcC4VVuulclUvJ6trKryhQ/6cLfA7iKrb2Qg0",
	"W2vwmjhcR599twWErQ+6ukBsS9ExX0rHXacJ4AksFDLTXLNzveUTa5JT6xPrAy8/92VIZ+5GfhdDTtLH",
	"5MhqBDT/E5uL4K/Hp1vIpzyjppqGenlhHEyej8ce6Wd7C6PdHbCFrhvUIrx5tf5gZ7H5heDjsoGvxy/2",
	"n9rzSVBPGtdqpuh8seN5HH8n9zmdUekitldQv/IEteticJd0puuOpIK6xWACRhUYwdbmiKmo0DVpDfJa",
	"C0BY9+Lum6GgW0xtbB2qkTpUsz6H8MrtZNMpHJxVbv8tggcll33ffP5/wlUpNhAbcjsYSVVTXj+M/mDq",
	"uoIRWbkNQw2UPg+GYAAMUnLv7r1DEVOK32DVjXTaBybLbgtJb53T+QtN96PJyq0NJSjd9R54qrsdDjgT",
	"bHcR3HAG7uzo/KLMeao/IVJSZhHopSzSBGYIyMm/RLROZAEYuXWi+077Ls8vgqMdwNXMHev8LaxgtHEM",
	"JtOUGt8FN5yl/M+yQamiv9fRnS/ok2qmf3BX78Y/t9t2nkC5aM/Ks/WmFrunczJNe9Rw785jKQwXhd23",
	"DWJbN76Nrf033ELyaCuUqy4ollELWNTMiQBvY8xduzF9hFF2fxnFOG1Gp0wvIRpF5OBWUl0zZQsVqyzK",
	"wmwOZw2ZGT7jKTfrHYh+/hekfQ1vBe0XV1oJ/edfCvt3fi8cVVntLrgPH23y7b5vdFVYodJgEoxuno/K",
	"04erWeEuMUor6n4wSTGBlJkxwRbUGd0crIRW8iu0cVxXULFDqF+u1HF5r+P20tQO7QPkbhXSS9q/6jyA",
	"dik8r5Wu3aDRpV45EaD+MGKidz+diFdfmDTE3uNMb96hHJFiBYiGYI8r7NKzDiRHpbk2mHTrlwnIwpTG",
	"I5VZgkEHYC0zlAKBzWRhpuKEgfvOovxoJKTbyTyHFdPUAGlTSvsUXEEMcy7In5ySe7m2ZjqXaipejCFh",
	"aw0nzEAmtYFn4/G4qj9PQ9DWoSVIP5hAqeWK0W8ilK4NE+qVnwryXEuW5ygwaUoV17M4hJ/KIt8S10um",
	"3EfALE1dbfOdS4iZSKaiPrEBbZihA5C8rIGG8J6aYKuLNLSSalrpNSTlxzV0zzkVkXbJmq4MbzAr9Kh8",
	"2Mrdr+KUac3n6+FCRhNgYu0dACZTEf1H+SVWVDm1iPogo7rnOIQ8LbQVOL/FBFJbq8q51cmA7AgtX26H",
	"rb7cWuGUrP1u40GRJ8ygnlDAmBW1mdki1NvIxN/AJKZDnCSin7KYCrqWoITfmmndUn5KON6+Cok8ghNG",
	"8v5KT6k+GG3qJF4ysbBgKuibrfLkz182CoE+aS9jg9u4FBCVN5j+0GFjQ72pcdeKXNswNSKzVzinAGjJ",
	"0YO3OP9+uuNXk6YBjFwk23CN5QelRyW4ldgRCTXdBn3UWj+edVyS28kdkZT/jUQfwfbnwB/D4HZg2OIX",
	"JYvcxddy3B8lou47lw43YmTY18kRbsaycFtVF9bEm7Bw/0V/uKWKqBe6LH8IpmcXFfctrus/go2vTT7e",
	"fbz7vwAAAP//dGNMHVhVAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
