// Package codegen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package codegen

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v5"
)

const (
	Access_tokenScopes = "access_token.Scopes"
)

// Defines values for NotificationCategory.
const (
	App     NotificationCategory = "app"
	Backup  NotificationCategory = "backup"
	Storage NotificationCategory = "storage"
	System  NotificationCategory = "system"
)

// Defines values for NotificationLevel.
const (
	Error   NotificationLevel = "error"
	Info    NotificationLevel = "info"
	Success NotificationLevel = "success"
	Warning NotificationLevel = "warning"
)

// Action defines model for Action.
type Action struct {
	// Name action name
	Name string `json:"name"`

	// Properties event properties
	Properties map[string]string `json:"properties"`

	// SourceID associated source id
	SourceID string `json:"sourceID"`

	// Timestamp timestamp this action took place
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// ActionType defines model for ActionType.
type ActionType struct {
	// Name action name
	//
	// (there is no naming convention for action names, but it is recommended to name each as structural and descriptive as possible)
	Name             string         `json:"name"`
	PropertyTypeList []PropertyType `json:"propertyTypeList"`

	// SourceID action source id to identify where the action will take
	SourceID string `json:"sourceID"`
}

// BaseResponse defines model for BaseResponse.
type BaseResponse struct {
	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// Event defines model for Event.
type Event struct {
	// Name event name
	Name string `json:"name"`

	// Properties event properties
	Properties map[string]string `json:"properties"`

	// SourceID associated source id
	SourceID string `json:"sourceID"`

	// Timestamp timestamp this event took place
	Timestamp *time.Time `json:"timestamp,omitempty"`

	// Uuid event uuid
	Uuid *string `json:"uuid,omitempty"`
}

// EventType defines model for EventType.
type EventType struct {
	// Name event name
	//
	// (there is no naming convention for event names, but it is recommended to name each as structural and descriptive as possible)
	Name             string         `json:"name"`
	PropertyTypeList []PropertyType `json:"propertyTypeList"`

	// SourceID event source id to identify where the event comes from
	SourceID string `json:"sourceID"`
}

// Notification defines model for Notification.
type Notification struct {
	// Action What opening it does (absent when nothing). `target` names the place (`backup`: `window` is a
	// Backup & Sync window `{kind, props}`; `settings`: `props.section`).
	Action *map[string]interface{} `json:"action,omitempty"`

	// Args arguments for `key`
	Args     map[string]interface{} `json:"args"`
	Category NotificationCategory   `json:"category"`

	// EventName name of the event it came from
	EventName string `json:"event_name"`

	// Icon icon URL ("" when none)
	Icon string `json:"icon"`

	// Id feed id; ids only ever grow
	Id int64 `json:"id"`

	// Key i18n key a client can render (with `args`) instead of `message` ("" when none)
	Key   string            `json:"key"`
	Level NotificationLevel `json:"level"`

	// Message English text
	Message string `json:"message"`

	// Read whether the caller has read it
	Read bool `json:"read"`

	// SourceId source of the event it came from
	SourceId string    `json:"source_id"`
	Time     time.Time `json:"time"`

	// Title English title
	Title string `json:"title"`
}

// NotificationCategory defines model for Notification.Category.
type NotificationCategory string

// NotificationLevel defines model for Notification.Level.
type NotificationLevel string

// NotificationCount defines model for NotificationCount.
type NotificationCount struct {
	UnreadCount int64 `json:"unread_count"`
}

// NotificationList defines model for NotificationList.
type NotificationList struct {
	Data []Notification `json:"data"`

	// HasMore more matching entries exist, older than the last one returned
	HasMore bool `json:"has_more"`

	// LatestId the newest entry the caller can see (0 when none)
	LatestId int64 `json:"latest_id"`

	// UnreadCount the caller's unread entries in the whole feed
	UnreadCount int64 `json:"unread_count"`
}

// NotificationSelection defines model for NotificationSelection.
type NotificationSelection struct {
	// All every entry up to `up_to` instead of `ids`
	All *bool    `json:"all,omitempty"`
	Ids *[]int64 `json:"ids,omitempty"`

	// UpTo with `all`, the newest id it applies to (default and maximum - the newest that exists)
	UpTo *int64 `json:"up_to,omitempty"`
}

// PropertyType defines model for PropertyType.
type PropertyType struct {
	Description *string `json:"description,omitempty"`
	Example     *string `json:"example,omitempty"`

	// Name property name
	//
	// > It is recommended for a property name to be as descriptive as possible. One option is to prefix with a namespace.
	// > - If the property is source specific, prefix with source ID. For example, `local-storage:vendor`
	// > - Otherwise, prefix with `common:`. For example, `common:email`
	// >
	// > Some bad examples are `id`, `avail`, `blk`...which can be ambiguous and confusing.
	Name string `json:"name"`
}

// ActionName defines model for ActionName.
type ActionName = string

// ActionNames defines model for ActionNames.
type ActionNames = []string

// EventName defines model for EventName.
type EventName = string

// EventNames defines model for EventNames.
type EventNames = []string

// SourceID defines model for SourceID.
type SourceID = string

// GetActionTypeOK defines model for GetActionTypeOK.
type GetActionTypeOK = ActionType

// GetActionTypesOK defines model for GetActionTypesOK.
type GetActionTypesOK = []ActionType

// GetEventTypeOK defines model for GetEventTypeOK.
type GetEventTypeOK = EventType

// GetEventTypesOK defines model for GetEventTypesOK.
type GetEventTypesOK = []EventType

// GetNotificationsOK defines model for GetNotificationsOK.
type GetNotificationsOK = NotificationList

// NotificationCountOK defines model for NotificationCountOK.
type NotificationCountOK = NotificationCount

// PublishEventOK defines model for PublishEventOK.
type PublishEventOK = Event

// ResponseBadRequest defines model for ResponseBadRequest.
type ResponseBadRequest = BaseResponse

// ResponseConflict defines model for ResponseConflict.
type ResponseConflict = BaseResponse

// ResponseInternalServerError defines model for ResponseInternalServerError.
type ResponseInternalServerError = BaseResponse

// ResponseNotFound defines model for ResponseNotFound.
type ResponseNotFound = BaseResponse

// ResponseOK defines model for ResponseOK.
type ResponseOK = BaseResponse

// ResponseServiceUnavailable defines model for ResponseServiceUnavailable.
type ResponseServiceUnavailable = BaseResponse

// TriggerActionOK defines model for TriggerActionOK.
type TriggerActionOK = Action

// NotificationSelectionBody defines model for NotificationSelectionBody.
type NotificationSelectionBody = NotificationSelection

// PublishEvent event properties
type PublishEvent map[string]string

// RegisterActionTypes defines model for RegisterActionTypes.
type RegisterActionTypes = []ActionType

// RegisterEventTypes defines model for RegisterEventTypes.
type RegisterEventTypes = []EventType

// TriggerAction action properties
type TriggerAction map[string]string

// SubscribeActionWSParams defines parameters for SubscribeActionWS.
type SubscribeActionWSParams struct {
	Names *ActionNames `form:"names,omitempty" json:"names,omitempty"`
}

// TriggerActionJSONBody defines parameters for TriggerAction.
type TriggerActionJSONBody map[string]string

// RegisterActionTypesJSONBody defines parameters for RegisterActionTypes.
type RegisterActionTypesJSONBody = []ActionType

// SubscribeEventWSParams defines parameters for SubscribeEventWS.
type SubscribeEventWSParams struct {
	Names *EventNames `form:"names,omitempty" json:"names,omitempty"`
}

// PublishEventJSONBody defines parameters for PublishEvent.
type PublishEventJSONBody map[string]string

// RegisterEventTypesJSONBody defines parameters for RegisterEventTypes.
type RegisterEventTypesJSONBody = []EventType

// GetNotificationsParams defines parameters for GetNotifications.
type GetNotificationsParams struct {
	// After only entries with an id greater than this
	After *int64 `form:"after,omitempty" json:"after,omitempty"`

	// Before only entries with an id smaller than this
	Before *int64 `form:"before,omitempty" json:"before,omitempty"`

	// Limit page size (default 50)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Unread only unread entries
	Unread *bool `form:"unread,omitempty" json:"unread,omitempty"`
}

// TriggerActionJSONRequestBody defines body for TriggerAction for application/json ContentType.
type TriggerActionJSONRequestBody TriggerActionJSONBody

// RegisterActionTypesJSONRequestBody defines body for RegisterActionTypes for application/json ContentType.
type RegisterActionTypesJSONRequestBody = RegisterActionTypesJSONBody

// PublishEventJSONRequestBody defines body for PublishEvent for application/json ContentType.
type PublishEventJSONRequestBody PublishEventJSONBody

// RegisterEventTypesJSONRequestBody defines body for RegisterEventTypes for application/json ContentType.
type RegisterEventTypesJSONRequestBody = RegisterEventTypesJSONBody

// DismissNotificationsJSONRequestBody defines body for DismissNotifications for application/json ContentType.
type DismissNotificationsJSONRequestBody = NotificationSelection

// MarkNotificationsReadJSONRequestBody defines body for MarkNotificationsRead for application/json ContentType.
type MarkNotificationsReadJSONRequestBody = NotificationSelection

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Subscribe to actions by source ID (WebSocket)
	// (GET /action/{source_id})
	SubscribeActionWS(ctx *echo.Context, sourceId SourceID, params SubscribeActionWSParams) error
	// Trigger an action
	// (POST /action/{source_id}/{name})
	TriggerAction(ctx *echo.Context, sourceId SourceID, name ActionName) error
	// List action types
	// (GET /action_type)
	GetActionTypes(ctx *echo.Context) error
	// Register one or more action types
	// (POST /action_type)
	RegisterActionTypes(ctx *echo.Context) error
	// Get action types by source ID
	// (GET /action_type/{source_id})
	GetActionTypesBySourceID(ctx *echo.Context, sourceId SourceID) error
	// Get an action type by source ID and name
	// (GET /action_type/{source_id}/{name})
	GetActionType(ctx *echo.Context, sourceId SourceID, name ActionName) error
	// Subscribe to events by source ID (WebSocket)
	// (GET /event/{source_id})
	SubscribeEventWS(ctx *echo.Context, sourceId SourceID, params SubscribeEventWSParams) error
	// Publish an event
	// (POST /event/{source_id}/{name})
	PublishEvent(ctx *echo.Context, sourceId SourceID, name EventName) error
	// List event types
	// (GET /event_type)
	GetEventTypes(ctx *echo.Context) error
	// Register one or more event types
	// (POST /event_type)
	RegisterEventTypes(ctx *echo.Context) error
	// Get event types by source ID
	// (GET /event_type/{source_id})
	GetEventTypesBySourceID(ctx *echo.Context, sourceId SourceID) error
	// Get an event type by source ID and name
	// (GET /event_type/{source_id}/{name})
	GetEventType(ctx *echo.Context, sourceId SourceID, name EventName) error
	// List the caller's notification feed
	// (GET /notifications)
	GetNotifications(ctx *echo.Context, params GetNotificationsParams) error
	// Dismiss notifications
	// (POST /notifications/dismiss)
	DismissNotifications(ctx *echo.Context) error
	// Mark notifications read
	// (POST /notifications/read)
	MarkNotificationsRead(ctx *echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// SubscribeActionWS converts echo context to params.
func (w *ServerInterfaceWrapper) SubscribeActionWS(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceID

	err = runtime.BindStyledParameterWithLocation("simple", false, "source_id", runtime.ParamLocationPath, ctx.Param("source_id"), &sourceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params SubscribeActionWSParams
	// ------------- Optional query parameter "names" -------------

	err = runtime.BindQueryParameter("form", true, false, "names", ctx.QueryParams(), &params.Names)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter names: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SubscribeActionWS(ctx, sourceId, params)
	return err
}

// TriggerAction converts echo context to params.
func (w *ServerInterfaceWrapper) TriggerAction(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceID

	err = runtime.BindStyledParameterWithLocation("simple", false, "source_id", runtime.ParamLocationPath, ctx.Param("source_id"), &sourceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name ActionName

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, ctx.Param("name"), &name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.TriggerAction(ctx, sourceId, name)
	return err
}

// GetActionTypes converts echo context to params.
func (w *ServerInterfaceWrapper) GetActionTypes(ctx *echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetActionTypes(ctx)
	return err
}

// RegisterActionTypes converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterActionTypes(ctx *echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RegisterActionTypes(ctx)
	return err
}

// GetActionTypesBySourceID converts echo context to params.
func (w *ServerInterfaceWrapper) GetActionTypesBySourceID(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceID

	err = runtime.BindStyledParameterWithLocation("simple", false, "source_id", runtime.ParamLocationPath, ctx.Param("source_id"), &sourceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetActionTypesBySourceID(ctx, sourceId)
	return err
}

// GetActionType converts echo context to params.
func (w *ServerInterfaceWrapper) GetActionType(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceID

	err = runtime.BindStyledParameterWithLocation("simple", false, "source_id", runtime.ParamLocationPath, ctx.Param("source_id"), &sourceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name ActionName

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, ctx.Param("name"), &name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetActionType(ctx, sourceId, name)
	return err
}

// SubscribeEventWS converts echo context to params.
func (w *ServerInterfaceWrapper) SubscribeEventWS(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceID

	err = runtime.BindStyledParameterWithLocation("simple", false, "source_id", runtime.ParamLocationPath, ctx.Param("source_id"), &sourceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params SubscribeEventWSParams
	// ------------- Optional query parameter "names" -------------

	err = runtime.BindQueryParameter("form", true, false, "names", ctx.QueryParams(), &params.Names)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter names: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SubscribeEventWS(ctx, sourceId, params)
	return err
}

// PublishEvent converts echo context to params.
func (w *ServerInterfaceWrapper) PublishEvent(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceID

	err = runtime.BindStyledParameterWithLocation("simple", false, "source_id", runtime.ParamLocationPath, ctx.Param("source_id"), &sourceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name EventName

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, ctx.Param("name"), &name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PublishEvent(ctx, sourceId, name)
	return err
}

// GetEventTypes converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventTypes(ctx *echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetEventTypes(ctx)
	return err
}

// RegisterEventTypes converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterEventTypes(ctx *echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RegisterEventTypes(ctx)
	return err
}

// GetEventTypesBySourceID converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventTypesBySourceID(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceID

	err = runtime.BindStyledParameterWithLocation("simple", false, "source_id", runtime.ParamLocationPath, ctx.Param("source_id"), &sourceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetEventTypesBySourceID(ctx, sourceId)
	return err
}

// GetEventType converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventType(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceID

	err = runtime.BindStyledParameterWithLocation("simple", false, "source_id", runtime.ParamLocationPath, ctx.Param("source_id"), &sourceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name EventName

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, ctx.Param("name"), &name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetEventType(ctx, sourceId, name)
	return err
}

// GetNotifications converts echo context to params.
func (w *ServerInterfaceWrapper) GetNotifications(ctx *echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetNotificationsParams
	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameter("form", true, false, "after", ctx.QueryParams(), &params.After)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter after: %s", err))
	}

	// ------------- Optional query parameter "before" -------------

	err = runtime.BindQueryParameter("form", true, false, "before", ctx.QueryParams(), &params.Before)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter before: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "unread" -------------

	err = runtime.BindQueryParameter("form", true, false, "unread", ctx.QueryParams(), &params.Unread)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter unread: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetNotifications(ctx, params)
	return err
}

// DismissNotifications converts echo context to params.
func (w *ServerInterfaceWrapper) DismissNotifications(ctx *echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DismissNotifications(ctx)
	return err
}

// MarkNotificationsRead converts echo context to params.
func (w *ServerInterfaceWrapper) MarkNotificationsRead(ctx *echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.MarkNotificationsRead(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/action/:source_id", wrapper.SubscribeActionWS)
	router.POST(baseURL+"/action/:source_id/:name", wrapper.TriggerAction)
	router.GET(baseURL+"/action_type", wrapper.GetActionTypes)
	router.POST(baseURL+"/action_type", wrapper.RegisterActionTypes)
	router.GET(baseURL+"/action_type/:source_id", wrapper.GetActionTypesBySourceID)
	router.GET(baseURL+"/action_type/:source_id/:name", wrapper.GetActionType)
	router.GET(baseURL+"/event/:source_id", wrapper.SubscribeEventWS)
	router.POST(baseURL+"/event/:source_id/:name", wrapper.PublishEvent)
	router.GET(baseURL+"/event_type", wrapper.GetEventTypes)
	router.POST(baseURL+"/event_type", wrapper.RegisterEventTypes)
	router.GET(baseURL+"/event_type/:source_id", wrapper.GetEventTypesBySourceID)
	router.GET(baseURL+"/event_type/:source_id/:name", wrapper.GetEventType)
	router.GET(baseURL+"/notifications", wrapper.GetNotifications)
	router.POST(baseURL+"/notifications/dismiss", wrapper.DismissNotifications)
	router.POST(baseURL+"/notifications/read", wrapper.MarkNotificationsRead)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xc73LbRpJ/lS7cVUW6Av/YVvY2TKWuothxXElsl+UtfzBVwhBokrMCZrAzA1GMS1/v",
	"Ae4R70muegZ/BgQokhKtXG3tp0TEYLqn+zfdv55p+EsQyyyXAoXRweRLkDPFMjSo7F8/xoZL8ZZlSH9x",
	"EUyCnJllEAbC/ub+EwYK/1FwhUkwMarAMNDxEjNG7+Aty/KUhqYyZulAG6nYAic5U4bT5JO5VBkzQRiY",
	"dU7jtFFcLIK7u9ATrw+ZK9z2OJOFIEl2If8oUK3bK9GBrzo3mFm5G4rVmjKl2Noq+uoGhfkaZkq4vp6w",
	"JMGk10C1XL3fJGHPA4WZvLHzH90sF7JQMb55ucUq2j6+4slDTNNjjzs3DWpzLhPubPJWGj7nMSP/X2CK",
	"FlHnMlnTw1gKg8LQ/7I8T8tho79rKei3Rod/VzgPJsG/jZrNMnJP9ahXQqNNs6i7MHhfzFKul9ZtBynA",
	"ksRCmKXvlcxRmXJ5HR8kqGPFc6vDJEASBHnzStiY88sGSjKZYBpMgp9U8QeqINx4XBQ8CSbB2dlzHOO3",
	"s8F3yQscnM3xr4PZ2V/mg+/is2dnz+YJxsl/dt69QZFIFUyCCyZecn3tgUXO/o6xceZq637y8d3Ld6dB",
	"jxU/4IJrg8qFh4/r3Nlib2PWCL7Prc3kPdB+gLLW519J13rux6n6UfHFojLrU8CTWUl74vMQAD4GX3bf",
	"6lwK7dbwGk2DhXe/Hi1u+ADravfuV1pES7Y+UPhXgHmtVY24IxrEQ/E+kr+KOQ7aSbVOfgrQR7SIP+9v",
	"XJvtSvgjfyKW85W0sHNvV8PPb8dGxnapH8rtes6SDy7/7yHZizMZak2MYhKcswSqKe7CPbU7ZxorFfqU",
	"3Ji0GvqTFPOUxw/WtX7/aIr6M1bj3giDSrD0AtUNqldKUR4/klt36VNGaE+bt9L8LAuRPNRmb6UBN8HR",
	"jNaashp4ROzvkt/eAuQmHuPfBLthPGUzZ4AnUaQUDZ5sODFLBOHFD5gjJsC1+MZAPcy6uEU+jp5mt1mu",
	"hoFX7toyuEVjRFnZ9bKXsra7t/jaVuOGG4L+6Wl+WBZ9ribcsKfWMubMYAJuENjKcO/6LwwMz1AbluXd",
	"yetHYJZcQ+k7I+U15CmLabrSSZMgYQYH9EJvzd3Qxc/NYsKqxPeccNmzeo9uHY6yqZgK2lEKgWsQkn7k",
	"YgGxFAQAu72kAu8NHcKsMMANvaAwllmGIsEEjH0ZAVm8BKZBG1XEplAsBSYSqFW4QXqaS6253aiPxfma",
	"lm6pzL6M7L33YpeU3YsnZ4caS7RonpCh5mtYWTNSeCqHrXiagmHXeAjk9oVDs+w+ULQiawcWdfbaXF/5",
	"ABSaQglMYLYGbdM0aJ4g8DnUYGFi3VqXLXtY8k6k6+rEpec0pT6n2AeoLgjtEw23nGf9Kxj+ScHQWezg",
	"WBgGzj79QLDPfIX3tOKRA25T0B0M4z3DbfPCU0fbXfvoKYOts8KuWOtGxTJDDXMls6ePtX4x24UEqwlg",
	"f/BxkbK98k9LZkDmKAgb3EAiUcMJm2la6mqJggjwkovF6RAiw9QCTeTgYk1idxycRDMWXxd5NIFoxUUi",
	"V5EN21Nxbn+HaTEeP/8LXKxFDG4ARF+uuUhCG+r0XfQ9RBqN4WKhaRb761C74+jodDgVQY85mFrow5bL",
	"1KLICDQW/NE1rqO+iWNmcCGVPWZHUWTkMrfEICQ2H4RB42m91gYzz18NlC1irvq3qt1Tcu4hixuI6ccO",
	"tgS/YUpKPXE6TGxNsu7bOzx2AGiLol/hbx9+g5NpMA0qtwq7R7tT9ARFV/ck3wNPNEiRrkljBQslV76i",
	"Z8+92MuF+ctZI4ALgwtUJOEa1z06PvurgGtcA4M45XajMQGKQpCCkxU3S4jI39EpcKENsoSMF5U0Iupb",
	"WmNAZ7ehs9twznjaH3pSvKGM2jidi7kkFxdxjJqS8Yop2io0uz1N6PP6Vs7zSixSrpdg8Na09Hsp4xKW",
	"//vf/wOvpVykCC8VhVSn7AQ0X4gBF4C3OQWRYZ/6RIq6UldLpDxggRazNEUFS0YhniXAPbo7kzJFJppI",
	"edUHhTJIHgbcQb15ehM9SdkvZxtu0vsMax/7GnQD0M7YbDN/qYB/yedtZi9CVKCpdGvc74BeRqlya5Y+",
	"2hXb3UFlJ8AXgt6+iqunO/faxspa7+/SoUq9bRUSZvY/j26lq56EvGT6KpOqrzqQCiFjJqbUAyiM4qgB",
	"b7k2Icg0sXBmwmIwZdqAFE0p0QvplBnUphfS9pgHV6iNlbT2dwoFIY0IJ+N2bNkjzG16qyvUyfhGgxta",
	"r5O7ha2WMkV75rSPwA1fW0dtKOFbwbP+LiQ098JdypGmvWxKrUtTFjmRqajIr4yMWpGbJzrq9RRPdAth",
	"e5g6Y7dv3PBn4/G4CzQrvicyuqySplEIHgg4xUWwh3ZEcyScJDhnRWos383YLc+KDAb+K4ZolIWn7kVH",
	"xgW9FEzGvY7rmL9FZbub0F+F32PwC1PJiikEV7+5KM2Jsm8ttLzqspmnqvp6xveTmYq91qUHBdwXCG86",
	"1YQ944HWeDLxzBYPW2qJIbwTCNIKo/mMhFzhnN+C9SBzhDRnMQ5ryQN441JULYrs4JKXzjEmdIetacqH",
	"b14O4WeqjJw1Qoj6SuPIE/SO0uuKa2zPF9GipZhEm/OVv2PGeFrPU893ITOEGUUD94IGcmjEkyiEyJ46",
	"0//M0utoOByuljxe2iBFBsxmfFHIQlucxlLMC83FYnhPJVbW+btSonV6N0wQU8C4UNysLyjkV2UIcaUr",
	"I6+xh4v+KMANADsgBMVWQJjQEJ0jU6hssn4R28fOJtEQPuHsQsbXaKZCF7N6Qg0ZW0POtLZbVkP0X/a9",
	"H5pYczJTcqVRaTLTNwY0zbFEltBPUgBr5i7rDNvs40Y07T4/FmYpFf/DJbMmxOT8VyzvVy1Z7Cz4reVA",
	"7y7g9/LE65wcFMeYm/LwwvnLVW+usoQbpjg50mFSl4V2ym9IabPEjPZAaYgZKk24F4QyrnVRjec6LrSm",
	"SUPIU2Qa4YZrbuy2+Pyam1+KGSjMpeZGqvXlydKYXE9GowU3y2I2jGU2+nmAAzFYD25H1TqqYswxsf7l",
	"/fj+TRAGpKyzwc1zCh1UZrKcB5PgxXA8fEFFLzNLi5mRW/3oS0247ujnBfZkzotq2WSDymqzNUT1uxHc",
	"cM+tQy8gRTZURNWWKSMBVTcu59oGMnDboGVj+0cZN+oD+HWO2pmDYoyFxpvEV9GdmH+6sGttehM/9/Om",
	"Zsiobj67C3eO9RsN7y43GkCejZ91TfiRyIcUAr3T4xlCkS8UK498PPv5QwlYlrq4Gs2+qTBGG7FLXzAL",
	"0bWNW8ZdjGFCZrIBo8gyRpX1Vj/WcRhOmp1JiGNU7X8OGr1eiSSXXBgdXNLUPSAafSF/WyzlUveAqby4",
	"AyYqp0oHhOp8elb0erjdbfQ03i2dW/UIrrfR71Yb4ait6WZ/0PPxePs05bjR5u3mXRic7fNeT2uDffVs",
	"/1frO/M2djpu8/Dh1IQMzVImbWhcmZJP9QYWqniApWlreztqR1COC6VQmHQNquyKw8Rl+j3w0u6FCh7i",
	"hU47VdskTntP845J6D3PLOGWLVH1/NmaSiqwtZjAVdss+y68r93xASjum+ZBWPaaHB4L4+/2f7VpTmn5",
	"rNfUh/hwA9p75c/XeB/Kd2C75O91JmxI807Qn68vmlPvh8bLy+PsnONEIWtJ34p+9nqE67ystd2Dwhft",
	"/GdLrYe5z6Ogtpra6c6nzXmP8viRHd42fIuwkBHLA8KdvrfU/3DC605cn5bullesO9muva78ymTX+2jk",
	"z+S6VeHmUd3ctY/upLrlq49iuh3w7CS6ZXMrwbe6Md8nfbe++XgSvz6M5bb0fBAx2Oj+/fM57qbHPGBY",
	"JfviyZ4E19vQx+O33jciDwzZre74uzD49hAH9PX69jBkb+mbBn0sP/ateig93jDeA9mxN8s/KTne333t",
	"PXEQM+7dHkcmxo2r/lRevLnljsWSfBNuYcWHOW1PTtzIPQ4lbvqjdvnxSbPjYzx9dDrs2XwXG97mc7/L",
	"Xm/18Uf/znSOmITV/ducK21C619ZuAPu6jLV8rOE64xrbbnZVAzgvUxT63iBqzJYR2xuUEXwg317yRdL",
	"mjgieq0RBWgJc6bgpNsCczq0U1o8sfi6nG6Gc6mwmi+Vq3o6WV1M4Y095M/ZAr+HqLqPjUCztQavbcP1",
	"8NGzLSBsfcLVBWLbik750jruAk0AT2ChkJnmYp3rLR9VWzu1Pqo+8LpzX4V05u7gdynkLH1MjcgjoPkf",
	"2Fz9fjs+3SI+5Zlto2mkl1fEweT5eOyJfra3Mdr9AFvkukEtwZuX6Q8OFpvfBD6ODXw7frH/qz0fAfXQ",
	"uFb7ROcbHS/i+Cu5L+iMyhCxvYL6hSeoXd+Cu6Qz3XAkFdRNBRMwqsAItrZDTEWFrklrkNdMAILCi7th",
	"hsLeYmpDdahG25Oa9QWEl24lm0HhYFa5/V8feBC57PvK8/8Trkqzgdiw28FIqtrw+mH0O1PXFYzsLqc0",
	"1EDp62AIBsAgteHdPXcoYkrxG6z6j077wETqtpD0wQWdf6HpfjSR3dpQgjJc78KT11Vhs3e7n+LzJQV1",
	"96WMy+6FSoNJMLp5PipZ7dWscIdjpaTupzdWlgVexgRb2B67hrCHwDSskPChq1MtGkJ8rjogLM8L3VlW",
	"k5PaBxPd7NYr2j9CP0B2eWXstWi0L/660qtTNLB9B1aJ3vW0+jFaZ6uNsE8405tnc12JxFhzVJoKkKSb",
	"pyYgC+M+KFhJRbUJpimpomWGVPaymSzMVJwwcB20ZTtwaE+h8xxWTNtGFwod9Cs44gNzLuxR5KktXa8x",
	"N/RkKl6MISFyecIMZFIbeDYejyuecRoSyWWQoP0U1oaQFbNfu5anolRCLVFMhSXVS5bnKDBpUpLrTRnC",
	"q5LMkXC9ZMp93kWltc1h37vAx0QyFTUzB22YsUQ3L3PdED7Z9qbqwBTJUk2TpIakbJu259lTEWm3KXW1",
	"EQazQo/KH1sx+ipOmdZ8vh4uZDQBJtZeoZdMRfQfZY99VHWYRbbfJaq7yULI00KTwfktJpASJ5Fz8snA",
	"4hpJL7fCVsdV7XBbiPzGbxCKPGEG9cQmASpIq4NkXbe300Im/gImsSXrSWQ/Up4Ke/xkAzttm7pZ8NQi",
	"efss1uQRnDBr72/01OaB0aZP4iUTCwJTYbvxywrPnzYKQQqIynNp/8Gw2TK9Aa+7Z1z7l20oYy+RkOy+",
	"hLQ/fMD5D9Md//rFNICRu//YCEzlh0FHFbhV2BEFNXdIfdJa/wjKcUVuF3dEUX6va5/A9mddl2FwOzBs",
	"8VrJInfZrRz3e4mo+04bwo0MFfbdz4WbmSTclqvDWniTBHZd3zTvXJTf7vcoXCnaUrD+I9hoEL68u7z7",
	"vwAAAP//mTsSKQtPAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
