// Package codegen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package codegen

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	types "github.com/compose-spec/compose-go/types"
	"github.com/deepmap/oapi-codegen/pkg/runtime"
	api "github.com/docker/compose/v2/pkg/api"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

const (
	Access_tokenScopes = "access_token.Scopes"
)

// Defines values for Scheme.
const (
	Http  Scheme = "http"
	Https Scheme = "https"
)

// Defines values for StoreAppAuthorType.
const (
	ByCasaos  StoreAppAuthorType = "by_casaos"
	Community StoreAppAuthorType = "community"
	Official  StoreAppAuthorType = "official"
	Unknown   StoreAppAuthorType = "unknown"
)

// Defines values for UpgradableAppInfoStatus.
const (
	Idle     UpgradableAppInfoStatus = "idle"
	Updating UpgradableAppInfoStatus = "updating"
)

// Defines values for WebAppGridItemAppType.
const (
	Container WebAppGridItemAppType = "container"
	Link      WebAppGridItemAppType = "link"
	V1app     WebAppGridItemAppType = "v1app"
	V2app     WebAppGridItemAppType = "v2app"
)

// Defines values for RequestComposeAppStatus.
const (
	RequestComposeAppStatusRestart RequestComposeAppStatus = "restart"
	RequestComposeAppStatusStart   RequestComposeAppStatus = "start"
	RequestComposeAppStatusStop    RequestComposeAppStatus = "stop"
)

// Defines values for SetComposeAppStatusJSONBody.
const (
	SetComposeAppStatusJSONBodyRestart SetComposeAppStatusJSONBody = "restart"
	SetComposeAppStatusJSONBodyStart   SetComposeAppStatusJSONBody = "start"
	SetComposeAppStatusJSONBodyStop    SetComposeAppStatusJSONBody = "stop"
)

// Defines values for ConvertParamsType.
const (
	Appfile ConvertParamsType = "appfile"
)

// AppStoreInfo > Do not mistake it as *information of AppStore* which does not exist.
type AppStoreInfo struct {
	Devices []DeviceStoreInfo `json:"devices" yaml:",omitempty"`
	Envs    []EnvStoreInfo    `json:"envs" yaml:",omitempty"`
	Image   string            `json:"image"`
	Ports   []PortStoreInfo   `json:"ports" yaml:",omitempty"`
	Volumes []VolumeStoreInfo `json:"volumes" yaml:",omitempty"`
}

// AppStoreMetadata defines model for AppStoreMetadata.
type AppStoreMetadata struct {
	ID        *int    `json:"id,omitempty"`
	StoreRoot *string `json:"store_root,omitempty"`
	URL       *string `json:"url,omitempty"`
}

// BaseResponse defines model for BaseResponse.
type BaseResponse struct {
	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// CategoryInfo defines model for CategoryInfo.
type CategoryInfo struct {
	Count       *int    `json:"count,omitempty"`
	Description *string `json:"description,omitempty"`
	Font        *string `json:"font,omitempty"`
	ID          *int    `json:"id,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// ComposeApp See [Compose Specification](https://compose-spec.io) for the schema structure of `ComposeApp`.
type ComposeApp = types.Project

// ComposeAppContainers Schema for `ComposeAppContainersOK` response.
type ComposeAppContainers struct {
	Containers *map[string]ContainerSummary `json:"containers,omitempty"`
	Main       *string                      `json:"main,omitempty"`
}

// ComposeAppStoreInfo defines model for ComposeAppStoreInfo.
type ComposeAppStoreInfo struct {
	// Apps The key is the name of a container app, and the value is the StoreInfo of this container app.
	Apps *map[string]AppStoreInfo `json:"apps,omitempty" yaml:",omitempty"`

	// Architectures The architectures supported by the compose app. If the architecture of the host is not in this list, the compose app will not be installed.
	Architectures *[]string          `json:"architectures,omitempty" yaml:",omitempty"`
	Author        string             `json:"author"`
	Category      string             `json:"category"`
	Description   map[string]string  `json:"description"`
	Developer     string             `json:"developer"`
	Hostname      *string            `json:"hostname,omitempty" yaml:",omitempty"`
	Icon          string             `json:"icon"`
	Image         *map[string]string `json:"image,omitempty"`
	Index         string             `json:"index" yaml:",omitempty"`

	// IsUncontrolled the mean the image tag is custom. not stable or latest
	IsUncontrolled *bool `json:"is_uncontrolled,omitempty" yaml:",omitempty"`

	// Main The main service is one of the services that the user will interact with.
	Main           *string  `json:"main,omitempty" yaml:",omitempty"`
	PortMap        string   `json:"port_map" mapstructure:"port_map" yaml:"port_map,omitempty"`
	Scheme         *Scheme  `json:"scheme,omitempty" yaml:",omitempty"`
	ScreenshotLink []string `json:"screenshot_link" mapstructure:"screenshot_link" yaml:"screenshot_link,omitempty"`

	// StoreAppId Store app ID of the compose app (unique across all app stores)
	//
	// > The `store_app_id` might be same as app name most of the time. However app name might change, due to cloning for example.
	// > If app name has changed, there is no way to associate it with the original app in the app store, unless we use the `store_app_id`.
	StoreAppID *StoreAppID       `json:"store_app_id,omitempty" mapstructure:"store_app_id" yaml:"store_app_id,omitempty"`
	Tagline    map[string]string `json:"tagline"`
	Thumbnail  string            `json:"thumbnail"`
	Tips       TipsStoreInfo     `json:"tips"`
	Title      map[string]string `json:"title"`
}

// ComposeAppStoreInfoLists defines model for ComposeAppStoreInfoLists.
type ComposeAppStoreInfoLists struct {
	Installed *[]StoreAppID                   `json:"installed,omitempty"`
	List      *map[string]ComposeAppStoreInfo `json:"list,omitempty"`
}

// ComposeAppStoreTag defines model for ComposeAppStoreTag.
type ComposeAppStoreTag struct {
	Tag string `json:"tag"`
}

// ComposeAppValidationErrors for list of `ComposeAppValidationErrors`, see **ERRORS** at the bottom of navigation bar.
type ComposeAppValidationErrors struct {
	union json.RawMessage
}

// ComposeAppValidationErrorsPortsInUse This is one of the `ComposeAppValidationErrors` that can be included in the response body of compose app installation.
type ComposeAppValidationErrorsPortsInUse struct {
	PortsInUse *struct {
		TCP *PortList `json:"TCP,omitempty"`
		UDP *PortList `json:"UDP,omitempty"`
	} `json:"ports_in_use,omitempty"`
}

// ComposeAppValidationErrorsPortsOutOfRange This is one of the `ComposeAppValidationErrors` that can be included in the response body of compose app installation.
type ComposeAppValidationErrorsPortsOutOfRange struct {
	PortsOutOfRange *[]string `json:"ports_out_of_range,omitempty"`
}

// ComposeAppWithStoreInfo Schema for `ComposeAppOK` response.
//
// > Do not mistake it as `ComposeAppStoreInfo` which is just store information of a compose app.
type ComposeAppWithStoreInfo struct {
	// Compose See [Compose Specification](https://compose-spec.io) for the schema structure of `ComposeApp`.
	Compose *ComposeApp `json:"compose,omitempty"`

	// IsUncontrolled the mean the image tag is custom. not stable or latest
	IsUncontrolled  *bool                `json:"is_uncontrolled,omitempty" yaml:",omitempty"`
	Status          *string              `json:"status,omitempty"`
	StoreInfo       *ComposeAppStoreInfo `json:"store_info,omitempty"`
	UpdateAvailable *bool                `json:"update_available,omitempty" yaml:",omitempty"`
}

// ContainerSummary See [Go Doc](https://pkg.go.dev/github.com/docker/compose/v2@v2.14.2/pkg/api#ContainerSummary) for the schema structure of `ContainerSummary`.
type ContainerSummary = api.ContainerSummary

// DeviceStoreInfo defines model for DeviceStoreInfo.
type DeviceStoreInfo struct {
	Container   *string            `json:"container,omitempty"`
	Description *map[string]string `json:"description,omitempty"`
}

// EnvStoreInfo defines model for EnvStoreInfo.
type EnvStoreInfo struct {
	Container   string            `json:"container"`
	Description map[string]string `json:"description"`
}

// GlobalSetting defines model for GlobalSetting.
type GlobalSetting struct {
	// Description description of the setting
	Description *string `json:"description,omitempty"`

	// Key key of the setting
	Key *string `json:"key,omitempty"`

	// Value value of the setting
	Value string `json:"value"`
}

// Info defines model for Info.
type Info struct {
	// Architecture current architecture
	Architecture *string `json:"architecture,omitempty"`
}

// PortList defines model for PortList.
type PortList = []string

// PortStoreInfo defines model for PortStoreInfo.
type PortStoreInfo struct {
	Container   string            `json:"container"`
	Description map[string]string `json:"description"`
}

// Scheme defines model for Scheme.
type Scheme string

// StoreAppAuthorType Type of the author of the app
//
// - `official`: The app is contributed by the app owner, i.e. `author“ and `developer“ are the same.
// - `by_casaos`: The app is contributed by CasaOS team, i.e. `author` is `CasaOS Team`
// - `community`: The app is contributed by the community, i.e. any app that is not `official` or `by_casaos`
type StoreAppAuthorType string

// StoreAppID Store app ID of the compose app (unique across all app stores)
//
// > The `store_app_id` might be same as app name most of the time. However app name might change, due to cloning for example.
// > If app name has changed, there is no way to associate it with the original app in the app store, unless we use the `store_app_id`.
type StoreAppID = string

// TipsStoreInfo defines model for TipsStoreInfo.
type TipsStoreInfo struct {
	BeforeInstall map[string]string `json:"before_install" mapstructure:"before_install" yaml:"before_install,omitempty"`
	Custom        *string           `json:"custom,omitempty"`
}

// UpgradableAppInfo Schema for `UpgradableAppListOK` response.
type UpgradableAppInfo struct {
	Icon   string                  `json:"icon"`
	Status UpgradableAppInfoStatus `json:"status"`

	// StoreAppId Store app ID of the compose app (unique across all app stores)
	//
	// > The `store_app_id` might be same as app name most of the time. However app name might change, due to cloning for example.
	// > If app name has changed, there is no way to associate it with the original app in the app store, unless we use the `store_app_id`.
	StoreAppID *StoreAppID `json:"store_app_id,omitempty" mapstructure:"store_app_id" yaml:"store_app_id,omitempty"`
	Title      string      `json:"title"`

	// Version current version of the installed app
	Version string `json:"version"`
}

// UpgradableAppInfoStatus defines model for UpgradableAppInfo.Status.
type UpgradableAppInfoStatus string

// VolumeStoreInfo defines model for VolumeStoreInfo.
type VolumeStoreInfo struct {
	Container   string            `json:"container"`
	Description map[string]string `json:"description"`
}

// WebAppGridItem (internal use ONLY)
type WebAppGridItem struct {
	AppType WebAppGridItemAppType `json:"app_type"`

	// AuthorType Type of the author of the app
	//
	// - `official`: The app is contributed by the app owner, i.e. `author`` and `developer`` are the same.
	// - `by_casaos`: The app is contributed by CasaOS team, i.e. `author` is `CasaOS Team`
	// - `community`: The app is contributed by the community, i.e. any app that is not `official` or `by_casaos`
	AuthorType     *StoreAppAuthorType `json:"author_type,omitempty"`
	Hostname       *string             `json:"hostname,omitempty"`
	Icon           *string             `json:"icon,omitempty"`
	Image          *string             `json:"image,omitempty"`
	Index          *string             `json:"index,omitempty"`
	IsUncontrolled *bool               `json:"is_uncontrolled,omitempty"`
	Name           *string             `json:"name,omitempty"`
	Port           *string             `json:"port,omitempty"`
	Scheme         *Scheme             `json:"scheme,omitempty" yaml:",omitempty"`
	Status         *string             `json:"status,omitempty"`

	// StoreAppId Store app ID of the compose app (unique across all app stores)
	//
	// > The `store_app_id` might be same as app name most of the time. However app name might change, due to cloning for example.
	// > If app name has changed, there is no way to associate it with the original app in the app store, unless we use the `store_app_id`.
	StoreAppID *StoreAppID        `json:"store_app_id,omitempty" mapstructure:"store_app_id" yaml:"store_app_id,omitempty"`
	Title      *map[string]string `json:"title,omitempty"`
}

// WebAppGridItemAppType defines model for WebAppGridItem.AppType.
type WebAppGridItemAppType string

// AppStoreID defines model for AppStoreID.
type AppStoreID = int

// AppStoreURL defines model for AppStoreURL.
type AppStoreURL = string

// CheckPortConflict defines model for CheckPortConflict.
type CheckPortConflict = bool

// ComposeAppID defines model for ComposeAppID.
type ComposeAppID = string

// ContainerID defines model for ContainerID.
type ContainerID = string

// ContainerIDs defines model for ContainerIDs.
type ContainerIDs = string

// DeleteConfigFolder defines model for DeleteConfigFolder.
type DeleteConfigFolder = bool

// DryRun defines model for DryRun.
type DryRun = bool

// Force defines model for Force.
type Force = bool

// GlobalSettingKey defines model for GlobalSettingKey.
type GlobalSettingKey = string

// PullLatestImage defines model for PullLatestImage.
type PullLatestImage = bool

// StoreAppAuthorTypeFilter Type of the author of the app
//
// - `official`: The app is contributed by the app owner, i.e. `author“ and `developer“ are the same.
// - `by_casaos`: The app is contributed by CasaOS team, i.e. `author` is `CasaOS Team`
// - `community`: The app is contributed by the community, i.e. any app that is not `official` or `by_casaos`
type StoreAppAuthorTypeFilter = StoreAppAuthorType

// StoreAppCategoryFilter defines model for StoreAppCategoryFilter.
type StoreAppCategoryFilter = string

// StoreAppIDString defines model for StoreAppIDString.
type StoreAppIDString = string

// StoreAppRecommendedFilter defines model for StoreAppRecommendedFilter.
type StoreAppRecommendedFilter = bool

// Uncontrolled defines model for Uncontrolled.
type Uncontrolled = bool

// AppStoreListOK defines model for AppStoreListOK.
type AppStoreListOK struct {
	Data *[]AppStoreMetadata `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// AppStoreRegisterOK defines model for AppStoreRegisterOK.
type AppStoreRegisterOK = BaseResponse

// AppStoreUnregisterOK defines model for AppStoreUnregisterOK.
type AppStoreUnregisterOK = BaseResponse

// CategoryListOK defines model for CategoryListOK.
type CategoryListOK struct {
	Data *[]CategoryInfo `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppBadRequest defines model for ComposeAppBadRequest.
type ComposeAppBadRequest struct {
	// Data for list of `ComposeAppValidationErrors`, see **ERRORS** at the bottom of navigation bar.
	Data *ComposeAppValidationErrors `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppContainersOK defines model for ComposeAppContainersOK.
type ComposeAppContainersOK struct {
	// Data Schema for `ComposeAppContainersOK` response.
	Data *ComposeAppContainers `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppHealthCheckOK defines model for ComposeAppHealthCheckOK.
type ComposeAppHealthCheckOK = BaseResponse

// ComposeAppInstallOK defines model for ComposeAppInstallOK.
type ComposeAppInstallOK = BaseResponse

// ComposeAppListOK defines model for ComposeAppListOK.
type ComposeAppListOK struct {
	Data *map[string]ComposeAppWithStoreInfo `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppLogsOK defines model for ComposeAppLogsOK.
type ComposeAppLogsOK struct {
	Data *string `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppOK defines model for ComposeAppOK.
type ComposeAppOK struct {
	// Data Schema for `ComposeAppOK` response.
	//
	// > Do not mistake it as `ComposeAppStoreInfo` which is just store information of a compose app.
	Data *ComposeAppWithStoreInfo `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppStoreInfoListsOK defines model for ComposeAppStoreInfoListsOK.
type ComposeAppStoreInfoListsOK struct {
	Data *ComposeAppStoreInfoLists `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppStoreInfoOK defines model for ComposeAppStoreInfoOK.
type ComposeAppStoreInfoOK struct {
	Data *ComposeAppStoreInfo `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppStoreTagOK defines model for ComposeAppStoreTagOK.
type ComposeAppStoreTagOK struct {
	Data *ComposeAppStoreTag `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppUninstallOK defines model for ComposeAppUninstallOK.
type ComposeAppUninstallOK = BaseResponse

// ComposeAppUpdateOK defines model for ComposeAppUpdateOK.
type ComposeAppUpdateOK = BaseResponse

// ComposeAppUpdateSettingsOK defines model for ComposeAppUpdateSettingsOK.
type ComposeAppUpdateSettingsOK = BaseResponse

// ContainerHealthCheckOK defines model for ContainerHealthCheckOK.
type ContainerHealthCheckOK = BaseResponse

// ContainerRecreateOK defines model for ContainerRecreateOK.
type ContainerRecreateOK = BaseResponse

// GetWebAppGridOK defines model for GetWebAppGridOK.
type GetWebAppGridOK struct {
	Data *[]WebAppGridItem `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// GlobalSettingOK defines model for GlobalSettingOK.
type GlobalSettingOK struct {
	Data *GlobalSetting `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// GlobalSettingsOK defines model for GlobalSettingsOK.
type GlobalSettingsOK struct {
	Data *[]GlobalSetting `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// InfoOK defines model for InfoOK.
type InfoOK = Info

// PullImagesOK defines model for PullImagesOK.
type PullImagesOK = BaseResponse

// RequestComposeAppStatusOK defines model for RequestComposeAppStatusOK.
type RequestComposeAppStatusOK = BaseResponse

// ResponseBadRequest defines model for ResponseBadRequest.
type ResponseBadRequest = BaseResponse

// ResponseConflict defines model for ResponseConflict.
type ResponseConflict = BaseResponse

// ResponseInternalServerError defines model for ResponseInternalServerError.
type ResponseInternalServerError = BaseResponse

// ResponseNotFound defines model for ResponseNotFound.
type ResponseNotFound = BaseResponse

// ResponseOK defines model for ResponseOK.
type ResponseOK = BaseResponse

// ResponseServiceUnavailable defines model for ResponseServiceUnavailable.
type ResponseServiceUnavailable = BaseResponse

// UpgradableAppListOK defines model for UpgradableAppListOK.
type UpgradableAppListOK struct {
	Data *[]UpgradableAppInfo `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// RequestComposeApp See [Compose Specification](https://compose-spec.io) for the schema structure of `ComposeApp`.
type RequestComposeApp = ComposeApp

// RequestComposeAppStatus defines model for RequestComposeAppStatus.
type RequestComposeAppStatus string

// ComposeAppStoreInfoListParams defines parameters for ComposeAppStoreInfoList.
type ComposeAppStoreInfoListParams struct {
	// Category Category of the store app
	Category *StoreAppCategoryFilter `form:"category,omitempty" json:"category,omitempty"`

	// AuthorType Author type of the store app
	AuthorType *StoreAppAuthorTypeFilter `form:"author_type,omitempty" json:"author_type,omitempty"`

	// Recommend The store app is recommended
	Recommend *StoreAppRecommendedFilter `form:"recommend,omitempty" json:"recommend,omitempty"`
}

// RegisterAppStoreParams defines parameters for RegisterAppStore.
type RegisterAppStoreParams struct {
	// Url URL of the app store
	Url *AppStoreURL `form:"url,omitempty" json:"url,omitempty"`
}

// InstallComposeAppParams defines parameters for InstallComposeApp.
type InstallComposeAppParams struct {
	// DryRun Dry run the request without actually excuting it, useful for validation and testing.
	//
	// - `true` - validate only
	// - `false` - validate and execute the request
	DryRun *DryRun `form:"dry_run,omitempty" json:"dry_run,omitempty"`

	// CheckPortConflict Check if the port of the app conflicts with ports already in use.
	//
	// - `true` - check port conflict
	// - `false` - skip port conflict check
	CheckPortConflict *CheckPortConflict `form:"check_port_conflict,omitempty" json:"check_port_conflict,omitempty"`

	// Uncontrolled Install the app without any control. the control mean version control, if the app is stable and latest. it is controlled, It will auto update. otherwise it is uncontrolled.
	//
	// - `true` - uncontrolled install
	// - `false` - normal install
	Uncontrolled *Uncontrolled `form:"uncontrolled,omitempty" json:"uncontrolled,omitempty"`
}

// UninstallComposeAppParams defines parameters for UninstallComposeApp.
type UninstallComposeAppParams struct {
	// DeleteConfigFolder Delete the config folder of the app
	DeleteConfigFolder *DeleteConfigFolder `form:"delete_config_folder,omitempty" json:"delete_config_folder,omitempty"`
}

// UpdateComposeAppParams defines parameters for UpdateComposeApp.
type UpdateComposeAppParams struct {
	Force *Force `form:"force,omitempty" json:"force,omitempty"`
}

// ApplyComposeAppSettingsParams defines parameters for ApplyComposeAppSettings.
type ApplyComposeAppSettingsParams struct {
	// DryRun Dry run the request without actually excuting it, useful for validation and testing.
	//
	// - `true` - validate only
	// - `false` - validate and execute the request
	DryRun *DryRun `form:"dry_run,omitempty" json:"dry_run,omitempty"`

	// CheckPortConflict Check if the port of the app conflicts with ports already in use.
	//
	// - `true` - check port conflict
	// - `false` - skip port conflict check
	CheckPortConflict *CheckPortConflict `form:"check_port_conflict,omitempty" json:"check_port_conflict,omitempty"`

	// Uncontrolled Install the app without any control. the control mean version control, if the app is stable and latest. it is controlled, It will auto update. otherwise it is uncontrolled.
	//
	// - `true` - uncontrolled install
	// - `false` - normal install
	Uncontrolled *Uncontrolled `form:"uncontrolled,omitempty" json:"uncontrolled,omitempty"`
}

// ComposeAppLogsParams defines parameters for ComposeAppLogs.
type ComposeAppLogsParams struct {
	// Lines Number of lines to show from the end of the logs for each compose app.
	//
	// - show all logs if `-1`
	Lines *int `form:"lines,omitempty" json:"lines,omitempty"`
}

// SetComposeAppStatusJSONBody defines parameters for SetComposeAppStatus.
type SetComposeAppStatusJSONBody string

// RecreateContainerByIDParams defines parameters for RecreateContainerByID.
type RecreateContainerByIDParams struct {
	// Pull Try to pull the latest image from the registry
	Pull  *PullLatestImage `form:"pull,omitempty" json:"pull,omitempty"`
	Force *Force           `form:"force,omitempty" json:"force,omitempty"`
}

// ConvertJSONBody defines parameters for Convert.
type ConvertJSONBody = map[string]interface{}

// ConvertParams defines parameters for Convert.
type ConvertParams struct {
	Type *ConvertParamsType `form:"type,omitempty" json:"type,omitempty"`
}

// ConvertParamsType defines parameters for Convert.
type ConvertParamsType string

// PullImagesParams defines parameters for PullImages.
type PullImagesParams struct {
	// ContainerIds a list of comma separated container IDs
	ContainerIds *ContainerIDs `form:"container_ids,omitempty" json:"container_ids,omitempty"`
}

// RegisterAppStoreSyncParams defines parameters for RegisterAppStoreSync.
type RegisterAppStoreSyncParams struct {
	// Url URL of the app store
	Url *AppStoreURL `form:"url,omitempty" json:"url,omitempty"`
}

// InstallComposeAppJSONRequestBody defines body for InstallComposeApp for application/json ContentType.
type InstallComposeAppJSONRequestBody = ComposeApp

// ApplyComposeAppSettingsJSONRequestBody defines body for ApplyComposeAppSettings for application/json ContentType.
type ApplyComposeAppSettingsJSONRequestBody = ComposeApp

// SetComposeAppStatusJSONRequestBody defines body for SetComposeAppStatus for application/json ContentType.
type SetComposeAppStatusJSONRequestBody SetComposeAppStatusJSONBody

// ConvertJSONRequestBody defines body for Convert for application/json ContentType.
type ConvertJSONRequestBody = ConvertJSONBody

// UpdateGlobalSettingJSONRequestBody defines body for UpdateGlobalSetting for application/json ContentType.
type UpdateGlobalSettingJSONRequestBody = GlobalSetting

// AsComposeAppValidationErrorsPortsInUse returns the union data inside the ComposeAppValidationErrors as a ComposeAppValidationErrorsPortsInUse
func (t ComposeAppValidationErrors) AsComposeAppValidationErrorsPortsInUse() (ComposeAppValidationErrorsPortsInUse, error) {
	var body ComposeAppValidationErrorsPortsInUse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromComposeAppValidationErrorsPortsInUse overwrites any union data inside the ComposeAppValidationErrors as the provided ComposeAppValidationErrorsPortsInUse
func (t *ComposeAppValidationErrors) FromComposeAppValidationErrorsPortsInUse(v ComposeAppValidationErrorsPortsInUse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeComposeAppValidationErrorsPortsInUse performs a merge with any union data inside the ComposeAppValidationErrors, using the provided ComposeAppValidationErrorsPortsInUse
func (t *ComposeAppValidationErrors) MergeComposeAppValidationErrorsPortsInUse(v ComposeAppValidationErrorsPortsInUse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(b, t.union)
	t.union = merged
	return err
}

// AsComposeAppValidationErrorsPortsOutOfRange returns the union data inside the ComposeAppValidationErrors as a ComposeAppValidationErrorsPortsOutOfRange
func (t ComposeAppValidationErrors) AsComposeAppValidationErrorsPortsOutOfRange() (ComposeAppValidationErrorsPortsOutOfRange, error) {
	var body ComposeAppValidationErrorsPortsOutOfRange
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromComposeAppValidationErrorsPortsOutOfRange overwrites any union data inside the ComposeAppValidationErrors as the provided ComposeAppValidationErrorsPortsOutOfRange
func (t *ComposeAppValidationErrors) FromComposeAppValidationErrorsPortsOutOfRange(v ComposeAppValidationErrorsPortsOutOfRange) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeComposeAppValidationErrorsPortsOutOfRange performs a merge with any union data inside the ComposeAppValidationErrors, using the provided ComposeAppValidationErrorsPortsOutOfRange
func (t *ComposeAppValidationErrors) MergeComposeAppValidationErrorsPortsOutOfRange(v ComposeAppValidationErrorsPortsOutOfRange) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(b, t.union)
	t.union = merged
	return err
}

func (t ComposeAppValidationErrors) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ComposeAppValidationErrors) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get app list from registered app stores
	// (GET /apps)
	ComposeAppStoreInfoList(ctx echo.Context, params ComposeAppStoreInfoListParams) error
	// Get the list of upgradable apps from installed app.
	// (GET /apps/upgradable)
	UpgradableAppList(ctx echo.Context) error
	// Get app info from registered app stores
	// (GET /apps/{id})
	ComposeAppStoreInfo(ctx echo.Context, id StoreAppIDString) error
	// Get compose details of an app from registered app stores
	// (GET /apps/{id}/compose)
	ComposeApp(ctx echo.Context, id StoreAppIDString) error
	// Get app stable version from registered app stores
	// (GET /apps/{id}/stable)
	ComposeAppMainStableTag(ctx echo.Context, id StoreAppIDString) error
	// Get server of app stable version from registered app stores
	// (GET /apps/{id}/stable/{serviceName})
	ComposeAppServiceStableTag(ctx echo.Context, id StoreAppIDString, serviceName string) error
	// Get the list of registered app stores
	// (GET /appstore)
	AppStoreList(ctx echo.Context) error
	// Register an app store
	// (POST /appstore)
	RegisterAppStore(ctx echo.Context, params RegisterAppStoreParams) error
	// Unregister an app store
	// (DELETE /appstore/{id})
	UnregisterAppStore(ctx echo.Context, id AppStoreID) error
	// Get the list of app categories
	// (GET /categories)
	CategoryList(ctx echo.Context) error
	// Get the list of installed compose apps
	// (GET /compose)
	MyComposeAppList(ctx echo.Context) error
	// Install a compose app
	// (POST /compose)
	InstallComposeApp(ctx echo.Context, params InstallComposeAppParams) error
	// Uninstall a compose app
	// (DELETE /compose/{id})
	UninstallComposeApp(ctx echo.Context, id ComposeAppID, params UninstallComposeAppParams) error
	// Get compose details of a locally installed app
	// (GET /compose/{id})
	MyComposeApp(ctx echo.Context, id ComposeAppID) error
	// Update container images of compose app to match the compose app in AppStore.
	// (PATCH /compose/{id})
	UpdateComposeApp(ctx echo.Context, id ComposeAppID, params UpdateComposeAppParams) error
	// Apply settings to a compose app
	// (PUT /compose/{id})
	ApplyComposeAppSettings(ctx echo.Context, id ComposeAppID, params ApplyComposeAppSettingsParams) error
	// Get the list of containers of a compose app
	// (GET /compose/{id}/containers)
	ComposeAppContainers(ctx echo.Context, id ComposeAppID) error
	// Check if the compose app is running healthy
	// (GET /compose/{id}/healthcheck)
	CheckComposeAppHealthByID(ctx echo.Context, id ComposeAppID) error
	// Get the logs of a compose app
	// (GET /compose/{id}/logs)
	ComposeAppLogs(ctx echo.Context, id ComposeAppID, params ComposeAppLogsParams) error
	// Start/restart/stop a compose app
	// (PUT /compose/{id}/status)
	SetComposeAppStatus(ctx echo.Context, id ComposeAppID) error
	// Recreate the container app
	// (PATCH /container/{id})
	RecreateContainerByID(ctx echo.Context, id ContainerID, params RecreateContainerByIDParams) error
	// Check if the container app is running healthy
	// (GET /container/{id}/healthcheck)
	CheckContainerHealthByID(ctx echo.Context, id ContainerID) error
	// Convert to compose app from another file format
	// (POST /convert)
	Convert(ctx echo.Context, params ConvertParams) error
	// Get all global settings
	// (GET /global)
	GetGlobalSettings(ctx echo.Context) error
	// Delete a global setting
	// (DELETE /global/{key})
	DeleteGlobalSetting(ctx echo.Context, key GlobalSettingKey) error
	// Get a global setting
	// (GET /global/{key})
	GetGlobalSetting(ctx echo.Context, key GlobalSettingKey) error
	// Update a global setting
	// (PUT /global/{key})
	UpdateGlobalSetting(ctx echo.Context, key GlobalSettingKey) error
	// Post a batch pull request specified images
	// (POST /image)
	PullImages(ctx echo.Context, params PullImagesParams) error
	// Get certain common information
	// (GET /info)
	Info(ctx echo.Context) error
	// (internal use ONLY)
	// (GET /web/appgrid)
	GetAppGrid(ctx echo.Context) error
	// Register an app store in Sync.
	// (POST /web/sync/appstore)
	RegisterAppStoreSync(ctx echo.Context, params RegisterAppStoreSyncParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ComposeAppStoreInfoList converts echo context to params.
func (w *ServerInterfaceWrapper) ComposeAppStoreInfoList(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ComposeAppStoreInfoListParams
	// ------------- Optional query parameter "category" -------------

	err = runtime.BindQueryParameter("form", true, false, "category", ctx.QueryParams(), &params.Category)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter category: %s", err))
	}

	// ------------- Optional query parameter "author_type" -------------

	err = runtime.BindQueryParameter("form", true, false, "author_type", ctx.QueryParams(), &params.AuthorType)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter author_type: %s", err))
	}

	// ------------- Optional query parameter "recommend" -------------

	err = runtime.BindQueryParameter("form", true, false, "recommend", ctx.QueryParams(), &params.Recommend)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter recommend: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ComposeAppStoreInfoList(ctx, params)
	return err
}

// UpgradableAppList converts echo context to params.
func (w *ServerInterfaceWrapper) UpgradableAppList(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpgradableAppList(ctx)
	return err
}

// ComposeAppStoreInfo converts echo context to params.
func (w *ServerInterfaceWrapper) ComposeAppStoreInfo(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id StoreAppIDString

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ComposeAppStoreInfo(ctx, id)
	return err
}

// ComposeApp converts echo context to params.
func (w *ServerInterfaceWrapper) ComposeApp(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id StoreAppIDString

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ComposeApp(ctx, id)
	return err
}

// ComposeAppMainStableTag converts echo context to params.
func (w *ServerInterfaceWrapper) ComposeAppMainStableTag(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id StoreAppIDString

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ComposeAppMainStableTag(ctx, id)
	return err
}

// ComposeAppServiceStableTag converts echo context to params.
func (w *ServerInterfaceWrapper) ComposeAppServiceStableTag(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id StoreAppIDString

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// ------------- Path parameter "serviceName" -------------
	var serviceName string

	err = runtime.BindStyledParameterWithLocation("simple", false, "serviceName", runtime.ParamLocationPath, ctx.Param("serviceName"), &serviceName)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter serviceName: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ComposeAppServiceStableTag(ctx, id, serviceName)
	return err
}

// AppStoreList converts echo context to params.
func (w *ServerInterfaceWrapper) AppStoreList(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.AppStoreList(ctx)
	return err
}

// RegisterAppStore converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterAppStore(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params RegisterAppStoreParams
	// ------------- Optional query parameter "url" -------------

	err = runtime.BindQueryParameter("form", true, false, "url", ctx.QueryParams(), &params.Url)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter url: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RegisterAppStore(ctx, params)
	return err
}

// UnregisterAppStore converts echo context to params.
func (w *ServerInterfaceWrapper) UnregisterAppStore(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id AppStoreID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UnregisterAppStore(ctx, id)
	return err
}

// CategoryList converts echo context to params.
func (w *ServerInterfaceWrapper) CategoryList(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CategoryList(ctx)
	return err
}

// MyComposeAppList converts echo context to params.
func (w *ServerInterfaceWrapper) MyComposeAppList(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.MyComposeAppList(ctx)
	return err
}

// InstallComposeApp converts echo context to params.
func (w *ServerInterfaceWrapper) InstallComposeApp(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params InstallComposeAppParams
	// ------------- Optional query parameter "dry_run" -------------

	err = runtime.BindQueryParameter("form", true, false, "dry_run", ctx.QueryParams(), &params.DryRun)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter dry_run: %s", err))
	}

	// ------------- Optional query parameter "check_port_conflict" -------------

	err = runtime.BindQueryParameter("form", true, false, "check_port_conflict", ctx.QueryParams(), &params.CheckPortConflict)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter check_port_conflict: %s", err))
	}

	// ------------- Optional query parameter "uncontrolled" -------------

	err = runtime.BindQueryParameter("form", true, false, "uncontrolled", ctx.QueryParams(), &params.Uncontrolled)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter uncontrolled: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.InstallComposeApp(ctx, params)
	return err
}

// UninstallComposeApp converts echo context to params.
func (w *ServerInterfaceWrapper) UninstallComposeApp(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ComposeAppID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params UninstallComposeAppParams
	// ------------- Optional query parameter "delete_config_folder" -------------

	err = runtime.BindQueryParameter("form", true, false, "delete_config_folder", ctx.QueryParams(), &params.DeleteConfigFolder)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter delete_config_folder: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UninstallComposeApp(ctx, id, params)
	return err
}

// MyComposeApp converts echo context to params.
func (w *ServerInterfaceWrapper) MyComposeApp(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ComposeAppID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.MyComposeApp(ctx, id)
	return err
}

// UpdateComposeApp converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateComposeApp(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ComposeAppID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateComposeAppParams
	// ------------- Optional query parameter "force" -------------

	err = runtime.BindQueryParameter("form", true, false, "force", ctx.QueryParams(), &params.Force)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter force: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateComposeApp(ctx, id, params)
	return err
}

// ApplyComposeAppSettings converts echo context to params.
func (w *ServerInterfaceWrapper) ApplyComposeAppSettings(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ComposeAppID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ApplyComposeAppSettingsParams
	// ------------- Optional query parameter "dry_run" -------------

	err = runtime.BindQueryParameter("form", true, false, "dry_run", ctx.QueryParams(), &params.DryRun)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter dry_run: %s", err))
	}

	// ------------- Optional query parameter "check_port_conflict" -------------

	err = runtime.BindQueryParameter("form", true, false, "check_port_conflict", ctx.QueryParams(), &params.CheckPortConflict)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter check_port_conflict: %s", err))
	}

	// ------------- Optional query parameter "uncontrolled" -------------

	err = runtime.BindQueryParameter("form", true, false, "uncontrolled", ctx.QueryParams(), &params.Uncontrolled)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter uncontrolled: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ApplyComposeAppSettings(ctx, id, params)
	return err
}

// ComposeAppContainers converts echo context to params.
func (w *ServerInterfaceWrapper) ComposeAppContainers(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ComposeAppID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ComposeAppContainers(ctx, id)
	return err
}

// CheckComposeAppHealthByID converts echo context to params.
func (w *ServerInterfaceWrapper) CheckComposeAppHealthByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ComposeAppID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CheckComposeAppHealthByID(ctx, id)
	return err
}

// ComposeAppLogs converts echo context to params.
func (w *ServerInterfaceWrapper) ComposeAppLogs(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ComposeAppID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ComposeAppLogsParams
	// ------------- Optional query parameter "lines" -------------

	err = runtime.BindQueryParameter("form", true, false, "lines", ctx.QueryParams(), &params.Lines)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter lines: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ComposeAppLogs(ctx, id, params)
	return err
}

// SetComposeAppStatus converts echo context to params.
func (w *ServerInterfaceWrapper) SetComposeAppStatus(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ComposeAppID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SetComposeAppStatus(ctx, id)
	return err
}

// RecreateContainerByID converts echo context to params.
func (w *ServerInterfaceWrapper) RecreateContainerByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ContainerID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params RecreateContainerByIDParams
	// ------------- Optional query parameter "pull" -------------

	err = runtime.BindQueryParameter("form", true, false, "pull", ctx.QueryParams(), &params.Pull)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter pull: %s", err))
	}

	// ------------- Optional query parameter "force" -------------

	err = runtime.BindQueryParameter("form", true, false, "force", ctx.QueryParams(), &params.Force)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter force: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RecreateContainerByID(ctx, id, params)
	return err
}

// CheckContainerHealthByID converts echo context to params.
func (w *ServerInterfaceWrapper) CheckContainerHealthByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ContainerID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CheckContainerHealthByID(ctx, id)
	return err
}

// Convert converts echo context to params.
func (w *ServerInterfaceWrapper) Convert(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ConvertParams
	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameter("form", true, false, "type", ctx.QueryParams(), &params.Type)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter type: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.Convert(ctx, params)
	return err
}

// GetGlobalSettings converts echo context to params.
func (w *ServerInterfaceWrapper) GetGlobalSettings(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetGlobalSettings(ctx)
	return err
}

// DeleteGlobalSetting converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteGlobalSetting(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "key" -------------
	var key GlobalSettingKey

	err = runtime.BindStyledParameterWithLocation("simple", false, "key", runtime.ParamLocationPath, ctx.Param("key"), &key)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter key: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteGlobalSetting(ctx, key)
	return err
}

// GetGlobalSetting converts echo context to params.
func (w *ServerInterfaceWrapper) GetGlobalSetting(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "key" -------------
	var key GlobalSettingKey

	err = runtime.BindStyledParameterWithLocation("simple", false, "key", runtime.ParamLocationPath, ctx.Param("key"), &key)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter key: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetGlobalSetting(ctx, key)
	return err
}

// UpdateGlobalSetting converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateGlobalSetting(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "key" -------------
	var key GlobalSettingKey

	err = runtime.BindStyledParameterWithLocation("simple", false, "key", runtime.ParamLocationPath, ctx.Param("key"), &key)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter key: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateGlobalSetting(ctx, key)
	return err
}

// PullImages converts echo context to params.
func (w *ServerInterfaceWrapper) PullImages(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params PullImagesParams
	// ------------- Optional query parameter "container_ids" -------------

	err = runtime.BindQueryParameter("form", true, false, "container_ids", ctx.QueryParams(), &params.ContainerIds)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter container_ids: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PullImages(ctx, params)
	return err
}

// Info converts echo context to params.
func (w *ServerInterfaceWrapper) Info(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.Info(ctx)
	return err
}

// GetAppGrid converts echo context to params.
func (w *ServerInterfaceWrapper) GetAppGrid(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetAppGrid(ctx)
	return err
}

// RegisterAppStoreSync converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterAppStoreSync(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params RegisterAppStoreSyncParams
	// ------------- Optional query parameter "url" -------------

	err = runtime.BindQueryParameter("form", true, false, "url", ctx.QueryParams(), &params.Url)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter url: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RegisterAppStoreSync(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/apps", wrapper.ComposeAppStoreInfoList)
	router.GET(baseURL+"/apps/upgradable", wrapper.UpgradableAppList)
	router.GET(baseURL+"/apps/:id", wrapper.ComposeAppStoreInfo)
	router.GET(baseURL+"/apps/:id/compose", wrapper.ComposeApp)
	router.GET(baseURL+"/apps/:id/stable", wrapper.ComposeAppMainStableTag)
	router.GET(baseURL+"/apps/:id/stable/:serviceName", wrapper.ComposeAppServiceStableTag)
	router.GET(baseURL+"/appstore", wrapper.AppStoreList)
	router.POST(baseURL+"/appstore", wrapper.RegisterAppStore)
	router.DELETE(baseURL+"/appstore/:id", wrapper.UnregisterAppStore)
	router.GET(baseURL+"/categories", wrapper.CategoryList)
	router.GET(baseURL+"/compose", wrapper.MyComposeAppList)
	router.POST(baseURL+"/compose", wrapper.InstallComposeApp)
	router.DELETE(baseURL+"/compose/:id", wrapper.UninstallComposeApp)
	router.GET(baseURL+"/compose/:id", wrapper.MyComposeApp)
	router.PATCH(baseURL+"/compose/:id", wrapper.UpdateComposeApp)
	router.PUT(baseURL+"/compose/:id", wrapper.ApplyComposeAppSettings)
	router.GET(baseURL+"/compose/:id/containers", wrapper.ComposeAppContainers)
	router.GET(baseURL+"/compose/:id/healthcheck", wrapper.CheckComposeAppHealthByID)
	router.GET(baseURL+"/compose/:id/logs", wrapper.ComposeAppLogs)
	router.PUT(baseURL+"/compose/:id/status", wrapper.SetComposeAppStatus)
	router.PATCH(baseURL+"/container/:id", wrapper.RecreateContainerByID)
	router.GET(baseURL+"/container/:id/healthcheck", wrapper.CheckContainerHealthByID)
	router.POST(baseURL+"/convert", wrapper.Convert)
	router.GET(baseURL+"/global", wrapper.GetGlobalSettings)
	router.DELETE(baseURL+"/global/:key", wrapper.DeleteGlobalSetting)
	router.GET(baseURL+"/global/:key", wrapper.GetGlobalSetting)
	router.PUT(baseURL+"/global/:key", wrapper.UpdateGlobalSetting)
	router.POST(baseURL+"/image", wrapper.PullImages)
	router.GET(baseURL+"/info", wrapper.Info)
	router.GET(baseURL+"/web/appgrid", wrapper.GetAppGrid)
	router.POST(baseURL+"/web/sync/appstore", wrapper.RegisterAppStoreSync)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9aXPbOBLoX0Fxt+pNpijJSTw5XDVV68RJxi+ZscvHzpuNXRJEtiTEJMABQDnalP/7",
	"K1wkQVK3HHv2+LATizgajUajL3R/CyKWZowClSI4+BZkmOMUJHD912GWnUvG4fhI/RWDiDjJJGE0OAiO",
	"jxAbITkBhLMMCdUsCAOiPmVYToIwoDiF4CAgcRAGHP7MCYc4OJA8hzAQ0QRSrEaFrzjNEggO9sJAzjLd",
	"g0oYAw/u7sIChMuzT00YLs8+zQXizxz4rIQi50nQOm0wkTITB73emMhJPuxGLO0dR/D7BCdwAdGk9xYL",
	"fHLecYAEBZhCckLHGsq3E4huThmXbxkdJSSSTVh1E0QMtBnjsgp5ZLsJdEvkRH8WCCcccDxDhKJcQPeK",
	"XtEOGij8DVAHRXo8PZDrrb+PcCJ0A3FDMv+76XNF56BIf+2rHn3Xw0NZDCOcJ9JtocXCkLEEMDVoULQk",
	"4DDL2ijmMMuQoRqMItNSL/4HRRtTnACVSLLiU8bZF4gkUtA92Y60AjGjkZyo3WrdPUYlJhR4G9TFRwU7",
	"oXrLjlh0AxzxnEqSKoooZ9p7DS/3Rvv4ZRw/H0X7z2N4gZ8Oo/29eP+n6OXr0aufXv60vw9Pn794+Rp+",
	"Gj7F+y/3917vPd/HLyN48ezpRgtduCTRXBNGCRGaACOWphgJUOdeQqxIpVitmEcnrk2fxGLOoYL956/2",
	"Xr180Ylf/vS6sz989qKDR09HndcvXuH9F3sv4uevX7fuxREkIEEdIzJ+z5IYeBN800bvRKQbopFuWTlR",
	"c0CPdc++6dU3vdak8SM+O8tpC1B8pghCA6B2CoTUh5nlEuFI5jhJZgi+RrkkdIyIDNWhHuUJGjGOpjgh",
	"MVYjIUxjJEGoVvUjb1sBYjSZ+Ye9+KS6w1eIcosgC8rcQx/zWZ/ntB0JevhWLLxnPALVtm3Mkf645ogf",
	"EjbEyTlItfKPMGti+CPM3A6PdWMkTOv2M3MDsxW5w8npu98Oj/uHp8f9j+/+aCXL0zxJPmG1L8cpHkMT",
	"uAs+U8wry5NEQ5joxoio1mjEWWp3Y0yE1LhqQ5zqvS7e9KV0mGWHuZwwfjHL4D1JZNuxMS2QGsPhUd+Y",
	"C84L1l36etoqXH/nMAoOgr/1SumhZ76KXhMgD863WMKY8dk8KN33VUGMbPs5jCiaYNm6ow6e46Nz82MD",
	"knM3c/utlVPyZw4IR5wJdVknpQwi7ve+cqCfgWLfQGOI52HzoopBRATiZZ85CC1arEuJl1TdDJwliVpc",
	"Q16kQmJ7OBQsBW+kM2T7dR1LV3+gFDBFU+BCcUX7Y+gEKLsaIfEwMUzPHLguIlJ9KCEJ0bFixGp7cslQ",
	"nik22UVMToDfEgG2Q14Bvs53q98QMevw2S9lPMVJ+W2eEFrFUOvOz8PunaEbEPINiwnoO/3M/FAKXepH",
	"NQFQLX/iLEtIpG+V3hfB9J212hGuDKlmrg40w2ni0+rfUGzEIXc6/jj89ROycFxRAXxKIhAHVxShbrd7",
	"RVfmJB4Yd2FDMCsPY3XKxhG7C5uoOpdY5mIthAHN0+DgcyAk5mYS9y8hWRZcN0/qQpCFgaABrN5pkTEq",
	"wNPBPhEhTz6uBTFOkpNRcPB5MZbfYAFndsbgLvwWZJxlwKWlshhLPRiRkIplO+aA/RUk1h3vCqxgzvFM",
	"IeW6BTEnH4OKrnemb0ng32G5y4G5pPwxgOOuxb8EGThgj+mIrUcC5Ql9g2N7ah9usasxp38Wwvs7zhkX",
	"81b4BsdOHPeXWihr4iF3drXFlrCuupG/AE7kRJs/VlpecbN8C1IQQkvbQcYUR1314vBXvBxEK5usif1d",
	"QvDQxxrHMVHz4OTU+74aUfxO5MQYCv0Dz4ZfIJKrEsonNn7QA1CKNFf53t7zKGFjoQQW9Ueb2W+lRT3+",
	"E13bPL2sdplvvsFpKRqKCRSh/wXYnA/vqptd9PoLLXCttV3g8V9kaRd45SN6ScmD8/9LrZY+OADW/CYe",
	"ABArVjxiacFCeAYRh4fYrA8gf4fhYZZ94CR+9DpACeqxhHQ9LcCzBT9WhuMBucZ6xKPfutrK1tm5DS6/",
	"RZC4C6p9stM8SbQ5/vvzqzkGpQc1Ebg2a2nOrfxTaapnpaa6G8TVBnVNqx7zTWAt+u8M0OqIrt0xlcCp",
	"OhR8Clzr+ZsC7IZCZixkBtsZ9HOHd51+Y/I9y2m8Kfy/MYnMADuD2RvSNdz8+jfHYbfH3bQ4N8bsS4qn",
	"mCR4aGbeBEY7EqoOtTOg5wx+mY05jtVfj8DisNJN5EG8rjWxQKcfy6RGaXinjJKPjhiiTKKUCIlvtGsI",
	"C/QjoSPGU+OeZyPkRvoR3U5INEExA6G7wVciZDcI6ysG7QBZedFHun2bPcUsOQy+dhjOSCdiMYyBduCr",
	"5Lgj8VgPbbT1IGSpmi2TM40JoNPVIXhHpzuenjiveYuP88C47poWljDQgVArg33KuNwx3FOW5Okae/dP",
	"3X6nQNxVXUSfLSbthjoMlYCGBbldh4EkUqO6gEe7san2pldcHIW35qB+WIm+JVJCSZqnOkSPA45PaDKr",
	"Rci4kD21vjHrWH/n8ZHmaWqOPmdM+gRQC6zrpJjQYO4MJVHkPNkqgq+HeTQhU+hxGIneBHAsemru7r9J",
	"tnR+f4GXZ5/MDnlMr4HGgu3X2Y79gDjInFOI0XCGhLm3BYnBers5ICIQpjMv0ixodTh6rpcGIBHLqb8L",
	"z8N1trfOZ6u78J5YT/wRlhi9wdFNnileKVbZ0xGrwRUM9QAdDi6qc+kYhliLEZ6G2xKu+aMKlFnVcmD8",
	"YMiW0BIA9Nl5g88ziMjIXrvXPzhqtu70jsgg6hL2RAeK6YgYzWuQkDyPZM51MM+gnG3QDeoGeLs4+6P6",
	"j+iemvDK6rcOSRU7UeBaPOimistgOQkOgsoBq0JX/DFmPdPjbo5/qwUTZjFqbYN2j9gAOX9482qNvJE3",
	"c2LYEc7zNMV8pva9IrBtHc558O2u6Q8JA83rVg75aTcyN483VqdtQ0T4NuGwJY7oBmaKDykSVOThQqJc",
	"wCjOstBEL04ATXGSg2vtXT9yYsNzil4mJKSC9BIVBnuNw2avNRPYROzA3pgCERoleawDdmxYURF70Xo+",
	"1hYN9C0iQR9B0R555TVBIs/U8TJcvgZSFx3bwKZKFxcCN2FCxygpGVOvhggdwBvWRzFxTqrZEFwwkg5n",
	"quL3c4DT+MV+oFaQvthXckIh2jR4qkP16isJdiF2mbjDNnEBXQBO20TFIg6wnWE32tfusXlHptGvQqdA",
	"+7lQPMzRq76mNSESmrNcoJG6ExU5Tzij5N9Ghcg4G3OcdtGxrHwD01qgIchbAIrkLUOMo1TRuMJvLoEr",
	"skYccIIkSSFEAo8gmakR1d5AbCJNMz5TwMAMRBf9wXKOlHSngJsVf+CEUXNdz1iOYtBShw6/nzC1k7dG",
	"7JAmyo5xiEP1m5JG3K8TzCE2DxYES0HRJY9RhrmcGUYwYbeIyP8jkOSYipRIBSFTwo2iGaINFSC7QRuD",
	"jGEKidoIfz/P53PJMFDnpHlnB20i3PoKTFSXd4p7OqbdLyKGhEx5l4LsjScLxc9/KN6v2K3oFavpqeG7",
	"WfuyCt1pGxptaFttSCc0hq/+Kns7Qp/o5wvDQxVF6IhPTRo6alpifaCiXEiWdjVbs/GejNtwT5+zueBJ",
	"y7Ps7aP4ohfdGTTiKzdakrvCm2xffUE27lGtQJ00F81soyGRnGCpf8kFcMO39YHAkXk2UGPavnhgF+hu",
	"YdmYk6KBm2mwmw3Uz4JSnPnU8er5q/11x09xVoiu2ldnBw7dzO6XGgRaUIGl0eemlW7PAaiYMNlPCL3x",
	"AP+8i9N7kgE9zwDiCxCyV07XeWpP8n3O8UzPsfjuXuMarm1KHXfF3tQ+1LdIa/o4y/pGF1vlmYBRtSQe",
	"J4RuzeXec1C3IkQ5B3MHxUR1GOb6cvRuY2FuY8lY0n4FyUmeDikmyc75/v+FJJmNCO0VU3S/ZK28X5Js",
	"qeR+QTLhW5wMf9iRUNMWz+WbpKy0FlbfYlS5YvU2tzdp2EJijgaqmHeLsZhwV1SFH10viDNqMWg5oXhl",
	"i16NTj3bcxgoMXz7+LnFsXNtUTjNlUnzY0mn06d73Wet70eqe6e6+ShshLOq5dHZCpb/+WOcMi7FMb20",
	"HoEtBjnJ5cnoDNMxBHfXdS11pAQD+7JxMH+ggWIRgH788d3Z2cnZ+Y8/InsXD5mULFW9KZ6SsWEQQ8y7",
	"8y0+JbtYafUt8gIRNRlhEeRGbogwNRqer+I6OwkasnhmX3cWqqGlfD1Y05Cizch9os5+i/3y4u3pKrZ3",
	"dea0n+lojeYN/b5V418T2RUqedwYZ7nss1GfO1ALlrRExpqPI+cWWwuJfgzoikY6zzR3Ra/oIifaoIXb",
	"DawDjQj0JRcSlfacirfNe3XXZgHUH9d5SvR9tZF5xqt71k5E8cCppCSeU2oE9KW2dCPJEUsNG9xi5p1d",
	"3/OTF5CYSecAscWyvZfvzqDbbnz/wNARi0pre3Yz7o5ZN4Zp1Y1kXrY5+3Zv+uwf02fdp/vdZ6p9D2fk",
	"b/Xplprp/eZLjfU4I93Gkhba7HFGWi32jbW4Ndh3977TucV1ZIGo2QcUxmJO7tnE9uH0EhnH5hwRyXNZ",
	"rwr8xb/uGewLkgL6F6OwXIguQfQhuK7HDzZXVwPYp/bKX6URwj2br7yBz4AeHqPD02P0UT+cbyzvpu1N",
	"/k35Jr911PrL+qWMRzsOmvMYf8KCmcRN56v531KR1yQGMBNd25jFFl9KxeLdhCfKOQcqPXO9B4+zsa/g",
	"KCxkoV3e/2bYtY+Emux+j8TvMESXx9udh/PCFFQ8S9dquQ6LMK907Z+avTff5m50pbYkNmgKl5XkCkYt",
	"riQlsc/K2WhEIoKTwQG6KJ+yaxHAGiqsV0V9YbcUeIhIF7poYEYcDLRlY1Ao1eoHbtJ9CJwqWayDBsNZ",
	"P8ICM7FwGutUkYDT2iSq8aDicxnoUSOWpjklcrYU+KKlHRfTmW6txWnrzCpRoYSoCshGkrJb6RoFYVC0",
	"CMKgmCAIg5zeUHZL1UbPk7fKbA64zIPRartU83ammKv7VCgAyg0/KUEpf3wzM2jyfnxbga789dLB6SWg",
	"WJ56ou7nW5x8oiKLqz0aVM1yA5SS8UQ7CBWtKNFc9dSm5JSJIiuVJCl00S/sFqbGo2qb6M7RROkrIYpz",
	"4zJKmJIrteRjT3y3gOB4VPaeYGH7xmEZ2EIZusU6ewoWgkUES600aMeSAoVxMiYUJ1ap8tN9hSinCQiB",
	"brUp3ahz3oIXWdKXE8vxUbA4BKiyjWvaWKvG0tLAWvm1xn98O1+DoQ9hZGR2rXVuL7lkQm9oLoALZAZ3",
	"Kq1C6d2aTvTa6mvQFuv3f69hwChftQQv+jckFbzDmQZ3qQRQm/y6Hhu7XAtuCaVdFKfygN7DiiJo+SmJ",
	"tUFVa2jEOBHm6H8bWfKd8blc6zeg/cvzg6vSpnwV3LXBarO9zBe3XDoYy6QKa64NPFjb+Glty27esH4o",
	"iyQdegMrEZXl/luuZLTeevjnylqUyUj23eIUbNq0mHCIJDNRT5uLY7WnXo3d+4G4NwmKQ5/89umPJ40T",
	"olAurUjlCHX6zGzr9Kn5bxUG7TNoo9xqyqoNMlWtHEXwSGICyrnHRALu6f8/eNrap+ndd96UZtumhWxZ",
	"jqIyXrI1jNuPOt3b22vjOuu6eBcaue6Dqc07fis60BrO2XkeNXca9Ft87c8kcmYWbo5LFIEQfclugBZp",
	"+CaATT5DK5oYurZhR5W4rIwoFV/rnmT+a4goI/qyNnLcFUUIIfNBsJxHgFKICf75Kvgh4zACLjoRSxjv",
	"mE08QDHmN0+uAiR4JED+fFUcDo5vu8YupS5r+/qkGbWdsDHTcdk9I/Lb//SHmFLgfTV8nypxtP9qby/7",
	"qk7KVbApsIka6B6hlbdET9EfJjksBpikY4QTBYJhEgao7w+RgaZXo4IranXCwyxDv2KKx5CqmznV/zTK",
	"REJGEM2iBELrMNGhceauJnSsRPbqXzqNlv0XyzLzL2PiCRHISPsW3jOOiBC5msK49aNcqEtbhChLAAtA",
	"UyKI8eN9/kDkL/kQcciYIOqCKw29ix8JPFGK6BdGKPrMco6OiIgYj8vesfmhOx73buifh8PhmyH8vydG",
	"xXCyQTuCDk+PK5LGQTB9ptgAy4DijAQHwfPuXve5NdzqI95z0bxjaEkn/AGkdnUKJQv57zuSpKorChMT",
	"6G4aA6piXZorHMdlWrK6+1wDU6aDnuP8LZv05qR4nOfxbenZSGK5Rt9mNsS761outWd7e/P4ftGutyBp",
	"yV0Y/LTKEItejWqG7lwTehvNkRHSbJTLNmaEWqvSm+gIY4ywcKEU5ITFwlwRmlh6eSGVzqWbHy5Ojk6e",
	"tBBBQ6MJNkFe2xPD+8GaTrJqff25J41biveUg+6KGPxG4ruFZ847asK+3PBclBXry6FntLHiq/U8F5G9",
	"Lmp9oAAYdNFJxS+tf3Jh9APFzAeVGPpi6NCE62Jh0loKbQ6MIVOHgUYzN/RqR3/jY19kUt3ZuTPEs7+3",
	"vzrxFK+b7++s6gcHW59VRWm9ive6leIOowgyiYZMTvQmeo9zrRm4nqlp4BJhmky/zh05MGMNkJESnSHt",
	"l4uLU5eVTpOufYfQaC7UnYwka5kw9GMhdDDrEHzb3cC4Hzt2xd2ZB+gESzRiScJuxdrvohaT9cNT8+Mj",
	"Ysc5YpCYJKJ8FLojqjZxEQvZqA2dsOLQD86ubtgrusDjJwoqL6h5Pr9dsP2/YkLP9VwXePxIOJtJovUI",
	"GZu/KTslht43u42/4RTuHgVp2CQJu6SO8NucRAzVSH3/rVRLlvAKptaq+vAfS5v2RTQb3QeV6tfFa0vL",
	"1azMGwnKtbTO9y8jb4CiMMiYWAcrLnFzpVbOekeqWu1nM3puySGtqXkN3FbyJ+mur1fvWk0dtOP9dAty",
	"V7V7Fr8iiReajSmBso5iWCTA3npbj4+23FUvGfcj4lIlXGtuj30xYa3I6/GgakrwjXhQLaf4Yv6hNdgS",
	"2uUrW6LaqFWhDsJxjCofWpb568xPkxxsd819N4Zb2h+q1rgK4pyes5zhutoZfgWSoqqMLUf1tqX+Aso4",
	"mxIvYr1U9ayVoqOjRFzNogkWSssbAhrYMXSc6QFq6pnusb8Ofrf9jBa3iRJXQPP7BCga2MJEP5siHEQ0",
	"VqJrayAj/YSISF0VqSiEZEwmVVS0SYMWsVuoi7Yc1Ap2ymaNuBU6eTVVDO90VUBm84m3Uiik16wScrfd",
	"ASqTpa96sbYm9d/9AWw9JQvPW4VPLb0fV+ZXRTrhLajKK6S3Apm0VE3bVh2oZkV+VDctWXubw/9Q45oO",
	"q8hYoiv33auBzYsnjMloBBxoBGWuigkxfrlB07hp7df2iZ1veyoTX6nrQ+0q0CnhjGqX2RRzonQ94a20",
	"i951x100+PvFvwYFOjhkCY5M9KmptqcjGP/NKCAJX1uZf1Ww2PKE/leYCFHCIl3FsB52tVCgwTKatFRu",
	"zUy1QlQiQZF/pXJeLdSrEvu5yJVpxv2OnNcUQtya2br074+J05otKh1UOuZI1F85SoZStceNGGVCy51a",
	"RiS5bC0Xm8xcIICWLf8n/u5Y/NUorlpEDa7vX1z5rxOaG+UVtpWdHwuXWHJK1xK/e346v+3MBq3pBx/0",
	"lvfKfD2y+75quCh3ofH+er3tnOhaHrqs+Nz9fDND9g2XESLNcEiQVNFVVC2aPnA5PwZtT2KMJCnQ4Nne",
	"Hjr5OLAFFlHEYvM6/a15KGCAcuXTOYsgznkpV6t5dcBWyWlHucznBE6pQeqVzt7M9FOQByQ0v4bKdpT2",
	"fPWOLcnRfULzSuB7ooJANmzXbs9sPUJL2HinHOMT28UlWMtxn6dD48RKCAXNKcWE3ZZiDNDY0bVaj3lN",
	"haNJI7ioYzoqbUk3JCM06DwdzK06q+drL+b7tBqHXST53Zb+bCG3x8jiFL62Y2plzHmr1LoytZ1Dsxzt",
	"DrjGtoKOhWQjcWd+UZRtXXCPg4rOJeayZ+v+9oRk2dqEZG/Wwto4Rz1emYpcMapCttjw9rG9VxPf68Xw",
	"711NblbeekRU4aAqipcXSYg9enC/L6KIuRJTxiHCsgwC2ViG+h2Gl8dICVJVw8p3kJ0qFsQSwlvGb8xF",
	"l8AYRzMTvetEAUbd8/TpXne/+1wr3IB5QoCXCvN7xv1Q2FwAGnx4d4HmCqMDbcECHC+Q6bxydNsfqu0I",
	"vyHQ3atcVqHgZZLZXKKegnnx5fyZdUnLNGigtE18se/0m4XYcZaNSAJtldebV+HKRW5acss0ysnvwta7",
	"4W3ob5zBo36DX7eMYapjwU3SS5NRy7+fUkZr+zbWaWYqjMfftQ8g/UJ2G3niG7Xw7imeMUmQWU9hnFht",
	"+b1vNzCreQJ9PBhnm5+TZ13m4PXWr/GuN5O4ilpZj+hGNAhCuLYBi/AfrkZyD4XnekHKxxa8uxamrd7S",
	"5ji5F2RvxofXKr25Ex7duskbKy33441ZZ6cVTyveibcHFp0yoajHOT8kQ1meJN4DJev1wS5vMstFMjNm",
	"iOHMOEm0DNAnsRigjhnAdipSuFSis53IcHwk3Bg60c7yviYPo26MftC1MCry5gxkW4xcWSJ0G/lNbMg2",
	"vAKlu6cJu3tD7X7TuHMbaXGm5HC3eEcmGp46ldhX4K082L4JW3/15Quu+3BQA1e7o9NMMVpNGrrsSNzC",
	"sIezbMxNEoB5947NaLGZjFOr1OyD354Oo9gf97EJtTqCXsz6luHZ5zMa/S9E+55DtJUmrBC97AVqJc+D",
	"3gY/w8Pna4Vr8xDCbJOughf0ps8URfTT4qG53hQ7UbPcnJ5Oa9z24OTClBO0ylbtxDTN2NUhDIhKN9SR",
	"IV7cs0tBUV/p4hH1MkyCmlKdKdIJeGB65rWVR63qtq3j1jXajUYumK4rJ+fx3MVDNphDZZg6a2iOZJI2",
	"mExVRzAiVGcrsbloz2D089Xy6l9XAeoZ40pzH216311NW6rFbZN67vfdT+k/718MQK2uwL2CsyIkOwXC",
	"TzDcDkGjUN7up1+MgnqrHYJQTR/cNnmtIu6upvVytLbNWy9pu6uJa4nK2qZulrLd1eS1XNNtkzdrIO/+",
	"wNVT/S8+d42yGN8DpLJyxHrA1eptfBcwy5oLG8BaK+vxtSPx+ANneWbEGDvIr/bemyvhh02BI2wIC2HL",
	"NR829KKwmPXcFhFvym9WNfLCTefeGeGcZBst2d09blPP5NzMMtjM3l4F35Jrwze5mGzWKbGxsHrM9d31",
	"3f8PAAD//zY268JmogAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
