// Package codegen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package codegen

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	types "github.com/compose-spec/compose-go/types"
	"github.com/deepmap/oapi-codegen/pkg/runtime"
	api "github.com/docker/compose/v2/pkg/api"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

const (
	Access_tokenScopes = "access_token.Scopes"
)

// Defines values for Scheme.
const (
	Http  Scheme = "http"
	Https Scheme = "https"
)

// Defines values for StoreAppAuthorType.
const (
	ByCasaos  StoreAppAuthorType = "by_casaos"
	Community StoreAppAuthorType = "community"
	Official  StoreAppAuthorType = "official"
	Unknown   StoreAppAuthorType = "unknown"
)

// Defines values for UpgradableAppInfoStatus.
const (
	Idle     UpgradableAppInfoStatus = "idle"
	Updating UpgradableAppInfoStatus = "updating"
)

// Defines values for WebAppGridItemAppType.
const (
	Container WebAppGridItemAppType = "container"
	Link      WebAppGridItemAppType = "link"
	V1app     WebAppGridItemAppType = "v1app"
	V2app     WebAppGridItemAppType = "v2app"
)

// Defines values for RequestComposeAppStatus.
const (
	RequestComposeAppStatusRestart RequestComposeAppStatus = "restart"
	RequestComposeAppStatusStart   RequestComposeAppStatus = "start"
	RequestComposeAppStatusStop    RequestComposeAppStatus = "stop"
)

// Defines values for SetComposeAppStatusJSONBody.
const (
	SetComposeAppStatusJSONBodyRestart SetComposeAppStatusJSONBody = "restart"
	SetComposeAppStatusJSONBodyStart   SetComposeAppStatusJSONBody = "start"
	SetComposeAppStatusJSONBodyStop    SetComposeAppStatusJSONBody = "stop"
)

// Defines values for ConvertParamsType.
const (
	Appfile ConvertParamsType = "appfile"
)

// AppStoreInfo > Do not mistake it as *information of AppStore* which does not exist.
type AppStoreInfo struct {
	Devices []DeviceStoreInfo `json:"devices" yaml:",omitempty"`
	Envs    []EnvStoreInfo    `json:"envs" yaml:",omitempty"`
	Image   string            `json:"image"`
	Ports   []PortStoreInfo   `json:"ports" yaml:",omitempty"`
	Volumes []VolumeStoreInfo `json:"volumes" yaml:",omitempty"`
}

// AppStoreMetadata defines model for AppStoreMetadata.
type AppStoreMetadata struct {
	ID        *int    `json:"id,omitempty"`
	StoreRoot *string `json:"store_root,omitempty"`
	URL       *string `json:"url,omitempty"`
}

// BaseResponse defines model for BaseResponse.
type BaseResponse struct {
	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// CategoryInfo defines model for CategoryInfo.
type CategoryInfo struct {
	Count       *int    `json:"count,omitempty"`
	Description *string `json:"description,omitempty"`
	Font        *string `json:"font,omitempty"`
	ID          *int    `json:"id,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// ComposeApp See [Compose Specification](https://compose-spec.io) for the schema structure of `ComposeApp`.
type ComposeApp = types.Project

// ComposeAppContainers Schema for `ComposeAppContainersOK` response.
type ComposeAppContainers struct {
	Containers *map[string]ContainerSummary `json:"containers,omitempty"`
	Main       *string                      `json:"main,omitempty"`
}

// ComposeAppStoreInfo defines model for ComposeAppStoreInfo.
type ComposeAppStoreInfo struct {
	// Apps The key is the name of a container app, and the value is the StoreInfo of this container app.
	Apps *map[string]AppStoreInfo `json:"apps,omitempty" yaml:",omitempty"`

	// Architectures The architectures supported by the compose app. If the architecture of the host is not in this list, the compose app will not be installed.
	Architectures *[]string          `json:"architectures,omitempty" yaml:",omitempty"`
	Author        string             `json:"author"`
	Category      string             `json:"category"`
	Description   map[string]string  `json:"description"`
	Developer     string             `json:"developer"`
	Hostname      *string            `json:"hostname,omitempty" yaml:",omitempty"`
	Icon          string             `json:"icon"`
	Image         *map[string]string `json:"image,omitempty"`
	Index         string             `json:"index" yaml:",omitempty"`

	// IsUncontrolled the mean the image tag is custom. not stable or latest
	IsUncontrolled *bool `json:"is_uncontrolled,omitempty" yaml:",omitempty"`

	// Main The main service is one of the services that the user will interact with.
	Main           *string  `json:"main,omitempty" yaml:",omitempty"`
	PortMap        string   `json:"port_map" mapstructure:"port_map" yaml:"port_map,omitempty"`
	Scheme         *Scheme  `json:"scheme,omitempty" yaml:",omitempty"`
	ScreenshotLink []string `json:"screenshot_link" mapstructure:"screenshot_link" yaml:"screenshot_link,omitempty"`

	// StoreAppId Store app ID of the compose app (unique across all app stores)
	//
	// > The `store_app_id` might be same as app name most of the time. However app name might change, due to cloning for example.
	// > If app name has changed, there is no way to associate it with the original app in the app store, unless we use the `store_app_id`.
	StoreAppID *StoreAppID       `json:"store_app_id,omitempty" mapstructure:"store_app_id" yaml:"store_app_id,omitempty"`
	Tagline    map[string]string `json:"tagline"`
	Thumbnail  string            `json:"thumbnail"`
	Tips       TipsStoreInfo     `json:"tips"`
	Title      map[string]string `json:"title"`
}

// ComposeAppStoreInfoLists defines model for ComposeAppStoreInfoLists.
type ComposeAppStoreInfoLists struct {
	Installed *[]StoreAppID                   `json:"installed,omitempty"`
	List      *map[string]ComposeAppStoreInfo `json:"list,omitempty"`
}

// ComposeAppStoreTag defines model for ComposeAppStoreTag.
type ComposeAppStoreTag struct {
	Tag string `json:"tag"`
}

// ComposeAppValidationErrors for list of `ComposeAppValidationErrors`, see **ERRORS** at the bottom of navigation bar.
type ComposeAppValidationErrors struct {
	union json.RawMessage
}

// ComposeAppValidationErrorsPortsInUse This is one of the `ComposeAppValidationErrors` that can be included in the response body of compose app installation.
type ComposeAppValidationErrorsPortsInUse struct {
	PortsInUse *struct {
		TCP *PortList `json:"TCP,omitempty"`
		UDP *PortList `json:"UDP,omitempty"`
	} `json:"ports_in_use,omitempty"`
}

// ComposeAppValidationErrorsPortsOutOfRange This is one of the `ComposeAppValidationErrors` that can be included in the response body of compose app installation.
type ComposeAppValidationErrorsPortsOutOfRange struct {
	PortsOutOfRange *[]string `json:"ports_out_of_range,omitempty"`
}

// ComposeAppWithStoreInfo Schema for `ComposeAppOK` response.
//
// > Do not mistake it as `ComposeAppStoreInfo` which is just store information of a compose app.
type ComposeAppWithStoreInfo struct {
	// Compose See [Compose Specification](https://compose-spec.io) for the schema structure of `ComposeApp`.
	Compose *ComposeApp `json:"compose,omitempty"`

	// IsUncontrolled the mean the image tag is custom. not stable or latest
	IsUncontrolled  *bool                `json:"is_uncontrolled,omitempty" yaml:",omitempty"`
	Status          *string              `json:"status,omitempty"`
	StoreInfo       *ComposeAppStoreInfo `json:"store_info,omitempty"`
	UpdateAvailable *bool                `json:"update_available,omitempty" yaml:",omitempty"`
}

// ContainerSummary See [Go Doc](https://pkg.go.dev/github.com/docker/compose/v2@v2.14.2/pkg/api#ContainerSummary) for the schema structure of `ContainerSummary`.
type ContainerSummary = api.ContainerSummary

// DeviceStoreInfo defines model for DeviceStoreInfo.
type DeviceStoreInfo struct {
	Container   *string            `json:"container,omitempty"`
	Description *map[string]string `json:"description,omitempty"`
}

// EnvStoreInfo defines model for EnvStoreInfo.
type EnvStoreInfo struct {
	Container   string            `json:"container"`
	Description map[string]string `json:"description"`
}

// GlobalSetting defines model for GlobalSetting.
type GlobalSetting struct {
	// Description description of the setting
	Description *string `json:"description,omitempty"`

	// Key key of the setting
	Key *string `json:"key,omitempty"`

	// Value value of the setting
	Value string `json:"value"`
}

// Info defines model for Info.
type Info struct {
	// Architecture current architecture
	Architecture *string `json:"architecture,omitempty"`
}

// PortList defines model for PortList.
type PortList = []string

// PortStoreInfo defines model for PortStoreInfo.
type PortStoreInfo struct {
	Container   string            `json:"container"`
	Description map[string]string `json:"description"`
}

// Scheme defines model for Scheme.
type Scheme string

// StoreAppAuthorType Type of the author of the app
//
// - `official`: The app is contributed by the app owner, i.e. `author“ and `developer“ are the same.
// - `by_casaos`: The app is contributed by CasaOS team, i.e. `author` is `CasaOS Team`
// - `community`: The app is contributed by the community, i.e. any app that is not `official` or `by_casaos`
type StoreAppAuthorType string

// StoreAppID Store app ID of the compose app (unique across all app stores)
//
// > The `store_app_id` might be same as app name most of the time. However app name might change, due to cloning for example.
// > If app name has changed, there is no way to associate it with the original app in the app store, unless we use the `store_app_id`.
type StoreAppID = string

// TipsStoreInfo defines model for TipsStoreInfo.
type TipsStoreInfo struct {
	BeforeInstall map[string]string `json:"before_install" mapstructure:"before_install" yaml:"before_install,omitempty"`
	Custom        *string           `json:"custom,omitempty"`
}

// UpgradableAppInfo Schema for `UpgradableAppListOK` response.
type UpgradableAppInfo struct {
	Icon   string                  `json:"icon"`
	Status UpgradableAppInfoStatus `json:"status"`

	// StoreAppId Store app ID of the compose app (unique across all app stores)
	//
	// > The `store_app_id` might be same as app name most of the time. However app name might change, due to cloning for example.
	// > If app name has changed, there is no way to associate it with the original app in the app store, unless we use the `store_app_id`.
	StoreAppID *StoreAppID `json:"store_app_id,omitempty" mapstructure:"store_app_id" yaml:"store_app_id,omitempty"`
	Title      string      `json:"title"`

	// Version current version of the installed app
	Version string `json:"version"`
}

// UpgradableAppInfoStatus defines model for UpgradableAppInfo.Status.
type UpgradableAppInfoStatus string

// VolumeStoreInfo defines model for VolumeStoreInfo.
type VolumeStoreInfo struct {
	Container   string            `json:"container"`
	Description map[string]string `json:"description"`
}

// WebAppGridItem (internal use ONLY)
type WebAppGridItem struct {
	AppType WebAppGridItemAppType `json:"app_type"`

	// AuthorType Type of the author of the app
	//
	// - `official`: The app is contributed by the app owner, i.e. `author`` and `developer`` are the same.
	// - `by_casaos`: The app is contributed by CasaOS team, i.e. `author` is `CasaOS Team`
	// - `community`: The app is contributed by the community, i.e. any app that is not `official` or `by_casaos`
	AuthorType *StoreAppAuthorType `json:"author_type,omitempty"`

	// ExitCode For an exited app, the exit code of its first stopped container (0, 137 or 143 after a normal stop).
	ExitCode *int `json:"exit_code,omitempty"`

	// Failed The app isn't running because it crashed or keeps restarting (a container exited with an error code, was killed for memory, is restarting or dead) - not because someone stopped it. Absent while the app runs.
	Failed         *bool   `json:"failed,omitempty"`
	Hostname       *string `json:"hostname,omitempty"`
	Icon           *string `json:"icon,omitempty"`
	Image          *string `json:"image,omitempty"`
	Index          *string `json:"index,omitempty"`
	IsUncontrolled *bool   `json:"is_uncontrolled,omitempty"`
	Name           *string `json:"name,omitempty"`
	Port           *string `json:"port,omitempty"`
	Scheme         *Scheme `json:"scheme,omitempty" yaml:",omitempty"`
	Status         *string `json:"status,omitempty"`

	// StoreAppId Store app ID of the compose app (unique across all app stores)
	//
	// > The `store_app_id` might be same as app name most of the time. However app name might change, due to cloning for example.
	// > If app name has changed, there is no way to associate it with the original app in the app store, unless we use the `store_app_id`.
	StoreAppID *StoreAppID        `json:"store_app_id,omitempty" mapstructure:"store_app_id" yaml:"store_app_id,omitempty"`
	Title      *map[string]string `json:"title,omitempty"`
}

// WebAppGridItemAppType defines model for WebAppGridItem.AppType.
type WebAppGridItemAppType string

// AppStoreID defines model for AppStoreID.
type AppStoreID = int

// AppStoreURL defines model for AppStoreURL.
type AppStoreURL = string

// CheckPortConflict defines model for CheckPortConflict.
type CheckPortConflict = bool

// ComposeAppID defines model for ComposeAppID.
type ComposeAppID = string

// ContainerID defines model for ContainerID.
type ContainerID = string

// ContainerIDs defines model for ContainerIDs.
type ContainerIDs = string

// DeleteConfigFolder defines model for DeleteConfigFolder.
type DeleteConfigFolder = bool

// DryRun defines model for DryRun.
type DryRun = bool

// Force defines model for Force.
type Force = bool

// GlobalSettingKey defines model for GlobalSettingKey.
type GlobalSettingKey = string

// PullLatestImage defines model for PullLatestImage.
type PullLatestImage = bool

// StoreAppAuthorTypeFilter Type of the author of the app
//
// - `official`: The app is contributed by the app owner, i.e. `author“ and `developer“ are the same.
// - `by_casaos`: The app is contributed by CasaOS team, i.e. `author` is `CasaOS Team`
// - `community`: The app is contributed by the community, i.e. any app that is not `official` or `by_casaos`
type StoreAppAuthorTypeFilter = StoreAppAuthorType

// StoreAppCategoryFilter defines model for StoreAppCategoryFilter.
type StoreAppCategoryFilter = string

// StoreAppIDString defines model for StoreAppIDString.
type StoreAppIDString = string

// StoreAppRecommendedFilter defines model for StoreAppRecommendedFilter.
type StoreAppRecommendedFilter = bool

// Uncontrolled defines model for Uncontrolled.
type Uncontrolled = bool

// AppStoreListOK defines model for AppStoreListOK.
type AppStoreListOK struct {
	Data *[]AppStoreMetadata `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// AppStoreRegisterOK defines model for AppStoreRegisterOK.
type AppStoreRegisterOK = BaseResponse

// AppStoreUnregisterOK defines model for AppStoreUnregisterOK.
type AppStoreUnregisterOK = BaseResponse

// CategoryListOK defines model for CategoryListOK.
type CategoryListOK struct {
	Data *[]CategoryInfo `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppBadRequest defines model for ComposeAppBadRequest.
type ComposeAppBadRequest struct {
	// Data for list of `ComposeAppValidationErrors`, see **ERRORS** at the bottom of navigation bar.
	Data *ComposeAppValidationErrors `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppContainersOK defines model for ComposeAppContainersOK.
type ComposeAppContainersOK struct {
	// Data Schema for `ComposeAppContainersOK` response.
	Data *ComposeAppContainers `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppHealthCheckOK defines model for ComposeAppHealthCheckOK.
type ComposeAppHealthCheckOK = BaseResponse

// ComposeAppInstallOK defines model for ComposeAppInstallOK.
type ComposeAppInstallOK = BaseResponse

// ComposeAppListOK defines model for ComposeAppListOK.
type ComposeAppListOK struct {
	Data *map[string]ComposeAppWithStoreInfo `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppLogsOK defines model for ComposeAppLogsOK.
type ComposeAppLogsOK struct {
	Data *string `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppOK defines model for ComposeAppOK.
type ComposeAppOK struct {
	// Data Schema for `ComposeAppOK` response.
	//
	// > Do not mistake it as `ComposeAppStoreInfo` which is just store information of a compose app.
	Data *ComposeAppWithStoreInfo `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppStoreInfoListsOK defines model for ComposeAppStoreInfoListsOK.
type ComposeAppStoreInfoListsOK struct {
	Data *ComposeAppStoreInfoLists `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppStoreInfoOK defines model for ComposeAppStoreInfoOK.
type ComposeAppStoreInfoOK struct {
	Data *ComposeAppStoreInfo `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppStoreTagOK defines model for ComposeAppStoreTagOK.
type ComposeAppStoreTagOK struct {
	Data *ComposeAppStoreTag `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppUninstallOK defines model for ComposeAppUninstallOK.
type ComposeAppUninstallOK = BaseResponse

// ComposeAppUpdateOK defines model for ComposeAppUpdateOK.
type ComposeAppUpdateOK = BaseResponse

// ComposeAppUpdateSettingsOK defines model for ComposeAppUpdateSettingsOK.
type ComposeAppUpdateSettingsOK = BaseResponse

// ContainerHealthCheckOK defines model for ContainerHealthCheckOK.
type ContainerHealthCheckOK = BaseResponse

// ContainerRecreateOK defines model for ContainerRecreateOK.
type ContainerRecreateOK = BaseResponse

// GetWebAppGridOK defines model for GetWebAppGridOK.
type GetWebAppGridOK struct {
	Data *[]WebAppGridItem `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// GlobalSettingOK defines model for GlobalSettingOK.
type GlobalSettingOK struct {
	Data *GlobalSetting `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// GlobalSettingsOK defines model for GlobalSettingsOK.
type GlobalSettingsOK struct {
	Data *[]GlobalSetting `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// InfoOK defines model for InfoOK.
type InfoOK = Info

// PullImagesOK defines model for PullImagesOK.
type PullImagesOK = BaseResponse

// RequestComposeAppStatusOK defines model for RequestComposeAppStatusOK.
type RequestComposeAppStatusOK = BaseResponse

// ResponseBadRequest defines model for ResponseBadRequest.
type ResponseBadRequest = BaseResponse

// ResponseConflict defines model for ResponseConflict.
type ResponseConflict = BaseResponse

// ResponseInternalServerError defines model for ResponseInternalServerError.
type ResponseInternalServerError = BaseResponse

// ResponseNotFound defines model for ResponseNotFound.
type ResponseNotFound = BaseResponse

// ResponseOK defines model for ResponseOK.
type ResponseOK = BaseResponse

// ResponseServiceUnavailable defines model for ResponseServiceUnavailable.
type ResponseServiceUnavailable = BaseResponse

// UpgradableAppListOK defines model for UpgradableAppListOK.
type UpgradableAppListOK struct {
	Data *[]UpgradableAppInfo `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// RequestComposeApp See [Compose Specification](https://compose-spec.io) for the schema structure of `ComposeApp`.
type RequestComposeApp = ComposeApp

// RequestComposeAppStatus defines model for RequestComposeAppStatus.
type RequestComposeAppStatus string

// ComposeAppStoreInfoListParams defines parameters for ComposeAppStoreInfoList.
type ComposeAppStoreInfoListParams struct {
	// Category Category of the store app
	Category *StoreAppCategoryFilter `form:"category,omitempty" json:"category,omitempty"`

	// AuthorType Author type of the store app
	AuthorType *StoreAppAuthorTypeFilter `form:"author_type,omitempty" json:"author_type,omitempty"`

	// Recommend The store app is recommended
	Recommend *StoreAppRecommendedFilter `form:"recommend,omitempty" json:"recommend,omitempty"`
}

// RegisterAppStoreParams defines parameters for RegisterAppStore.
type RegisterAppStoreParams struct {
	// Url URL of the app store
	Url *AppStoreURL `form:"url,omitempty" json:"url,omitempty"`
}

// InstallComposeAppParams defines parameters for InstallComposeApp.
type InstallComposeAppParams struct {
	// DryRun Dry run the request without actually excuting it, useful for validation and testing.
	//
	// - `true` - validate only
	// - `false` - validate and execute the request
	DryRun *DryRun `form:"dry_run,omitempty" json:"dry_run,omitempty"`

	// CheckPortConflict Check if the port of the app conflicts with ports already in use.
	//
	// - `true` - check port conflict
	// - `false` - skip port conflict check
	CheckPortConflict *CheckPortConflict `form:"check_port_conflict,omitempty" json:"check_port_conflict,omitempty"`

	// Uncontrolled Install the app without any control. the control mean version control, if the app is stable and latest. it is controlled, It will auto update. otherwise it is uncontrolled.
	//
	// - `true` - uncontrolled install
	// - `false` - normal install
	Uncontrolled *Uncontrolled `form:"uncontrolled,omitempty" json:"uncontrolled,omitempty"`
}

// UninstallComposeAppParams defines parameters for UninstallComposeApp.
type UninstallComposeAppParams struct {
	// DeleteConfigFolder Delete the config folder of the app
	DeleteConfigFolder *DeleteConfigFolder `form:"delete_config_folder,omitempty" json:"delete_config_folder,omitempty"`
}

// UpdateComposeAppParams defines parameters for UpdateComposeApp.
type UpdateComposeAppParams struct {
	Force *Force `form:"force,omitempty" json:"force,omitempty"`
}

// ApplyComposeAppSettingsParams defines parameters for ApplyComposeAppSettings.
type ApplyComposeAppSettingsParams struct {
	// DryRun Dry run the request without actually excuting it, useful for validation and testing.
	//
	// - `true` - validate only
	// - `false` - validate and execute the request
	DryRun *DryRun `form:"dry_run,omitempty" json:"dry_run,omitempty"`

	// CheckPortConflict Check if the port of the app conflicts with ports already in use.
	//
	// - `true` - check port conflict
	// - `false` - skip port conflict check
	CheckPortConflict *CheckPortConflict `form:"check_port_conflict,omitempty" json:"check_port_conflict,omitempty"`

	// Uncontrolled Install the app without any control. the control mean version control, if the app is stable and latest. it is controlled, It will auto update. otherwise it is uncontrolled.
	//
	// - `true` - uncontrolled install
	// - `false` - normal install
	Uncontrolled *Uncontrolled `form:"uncontrolled,omitempty" json:"uncontrolled,omitempty"`
}

// ComposeAppLogsParams defines parameters for ComposeAppLogs.
type ComposeAppLogsParams struct {
	// Lines Number of lines to show from the end of the logs for each compose app.
	//
	// - show all logs if `-1`
	Lines *int `form:"lines,omitempty" json:"lines,omitempty"`
}

// SetComposeAppStatusJSONBody defines parameters for SetComposeAppStatus.
type SetComposeAppStatusJSONBody string

// RecreateContainerByIDParams defines parameters for RecreateContainerByID.
type RecreateContainerByIDParams struct {
	// Pull Try to pull the latest image from the registry
	Pull  *PullLatestImage `form:"pull,omitempty" json:"pull,omitempty"`
	Force *Force           `form:"force,omitempty" json:"force,omitempty"`
}

// ConvertJSONBody defines parameters for Convert.
type ConvertJSONBody = map[string]interface{}

// ConvertParams defines parameters for Convert.
type ConvertParams struct {
	Type *ConvertParamsType `form:"type,omitempty" json:"type,omitempty"`
}

// ConvertParamsType defines parameters for Convert.
type ConvertParamsType string

// PullImagesParams defines parameters for PullImages.
type PullImagesParams struct {
	// ContainerIds a list of comma separated container IDs
	ContainerIds *ContainerIDs `form:"container_ids,omitempty" json:"container_ids,omitempty"`
}

// RegisterAppStoreSyncParams defines parameters for RegisterAppStoreSync.
type RegisterAppStoreSyncParams struct {
	// Url URL of the app store
	Url *AppStoreURL `form:"url,omitempty" json:"url,omitempty"`
}

// InstallComposeAppJSONRequestBody defines body for InstallComposeApp for application/json ContentType.
type InstallComposeAppJSONRequestBody = ComposeApp

// ApplyComposeAppSettingsJSONRequestBody defines body for ApplyComposeAppSettings for application/json ContentType.
type ApplyComposeAppSettingsJSONRequestBody = ComposeApp

// SetComposeAppStatusJSONRequestBody defines body for SetComposeAppStatus for application/json ContentType.
type SetComposeAppStatusJSONRequestBody SetComposeAppStatusJSONBody

// ConvertJSONRequestBody defines body for Convert for application/json ContentType.
type ConvertJSONRequestBody = ConvertJSONBody

// UpdateGlobalSettingJSONRequestBody defines body for UpdateGlobalSetting for application/json ContentType.
type UpdateGlobalSettingJSONRequestBody = GlobalSetting

// AsComposeAppValidationErrorsPortsInUse returns the union data inside the ComposeAppValidationErrors as a ComposeAppValidationErrorsPortsInUse
func (t ComposeAppValidationErrors) AsComposeAppValidationErrorsPortsInUse() (ComposeAppValidationErrorsPortsInUse, error) {
	var body ComposeAppValidationErrorsPortsInUse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromComposeAppValidationErrorsPortsInUse overwrites any union data inside the ComposeAppValidationErrors as the provided ComposeAppValidationErrorsPortsInUse
func (t *ComposeAppValidationErrors) FromComposeAppValidationErrorsPortsInUse(v ComposeAppValidationErrorsPortsInUse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeComposeAppValidationErrorsPortsInUse performs a merge with any union data inside the ComposeAppValidationErrors, using the provided ComposeAppValidationErrorsPortsInUse
func (t *ComposeAppValidationErrors) MergeComposeAppValidationErrorsPortsInUse(v ComposeAppValidationErrorsPortsInUse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(b, t.union)
	t.union = merged
	return err
}

// AsComposeAppValidationErrorsPortsOutOfRange returns the union data inside the ComposeAppValidationErrors as a ComposeAppValidationErrorsPortsOutOfRange
func (t ComposeAppValidationErrors) AsComposeAppValidationErrorsPortsOutOfRange() (ComposeAppValidationErrorsPortsOutOfRange, error) {
	var body ComposeAppValidationErrorsPortsOutOfRange
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromComposeAppValidationErrorsPortsOutOfRange overwrites any union data inside the ComposeAppValidationErrors as the provided ComposeAppValidationErrorsPortsOutOfRange
func (t *ComposeAppValidationErrors) FromComposeAppValidationErrorsPortsOutOfRange(v ComposeAppValidationErrorsPortsOutOfRange) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeComposeAppValidationErrorsPortsOutOfRange performs a merge with any union data inside the ComposeAppValidationErrors, using the provided ComposeAppValidationErrorsPortsOutOfRange
func (t *ComposeAppValidationErrors) MergeComposeAppValidationErrorsPortsOutOfRange(v ComposeAppValidationErrorsPortsOutOfRange) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(b, t.union)
	t.union = merged
	return err
}

func (t ComposeAppValidationErrors) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ComposeAppValidationErrors) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get app list from registered app stores
	// (GET /apps)
	ComposeAppStoreInfoList(ctx echo.Context, params ComposeAppStoreInfoListParams) error
	// Get the list of upgradable apps from installed app.
	// (GET /apps/upgradable)
	UpgradableAppList(ctx echo.Context) error
	// Get app info from registered app stores
	// (GET /apps/{id})
	ComposeAppStoreInfo(ctx echo.Context, id StoreAppIDString) error
	// Get compose details of an app from registered app stores
	// (GET /apps/{id}/compose)
	ComposeApp(ctx echo.Context, id StoreAppIDString) error
	// Get app stable version from registered app stores
	// (GET /apps/{id}/stable)
	ComposeAppMainStableTag(ctx echo.Context, id StoreAppIDString) error
	// Get server of app stable version from registered app stores
	// (GET /apps/{id}/stable/{serviceName})
	ComposeAppServiceStableTag(ctx echo.Context, id StoreAppIDString, serviceName string) error
	// Get the list of registered app stores
	// (GET /appstore)
	AppStoreList(ctx echo.Context) error
	// Register an app store
	// (POST /appstore)
	RegisterAppStore(ctx echo.Context, params RegisterAppStoreParams) error
	// Unregister an app store
	// (DELETE /appstore/{id})
	UnregisterAppStore(ctx echo.Context, id AppStoreID) error
	// Get the list of app categories
	// (GET /categories)
	CategoryList(ctx echo.Context) error
	// Get the list of installed compose apps
	// (GET /compose)
	MyComposeAppList(ctx echo.Context) error
	// Install a compose app
	// (POST /compose)
	InstallComposeApp(ctx echo.Context, params InstallComposeAppParams) error
	// Uninstall a compose app
	// (DELETE /compose/{id})
	UninstallComposeApp(ctx echo.Context, id ComposeAppID, params UninstallComposeAppParams) error
	// Get compose details of a locally installed app
	// (GET /compose/{id})
	MyComposeApp(ctx echo.Context, id ComposeAppID) error
	// Update container images of compose app to match the compose app in AppStore.
	// (PATCH /compose/{id})
	UpdateComposeApp(ctx echo.Context, id ComposeAppID, params UpdateComposeAppParams) error
	// Apply settings to a compose app
	// (PUT /compose/{id})
	ApplyComposeAppSettings(ctx echo.Context, id ComposeAppID, params ApplyComposeAppSettingsParams) error
	// Get the list of containers of a compose app
	// (GET /compose/{id}/containers)
	ComposeAppContainers(ctx echo.Context, id ComposeAppID) error
	// Check if the compose app is running healthy
	// (GET /compose/{id}/healthcheck)
	CheckComposeAppHealthByID(ctx echo.Context, id ComposeAppID) error
	// Get the logs of a compose app
	// (GET /compose/{id}/logs)
	ComposeAppLogs(ctx echo.Context, id ComposeAppID, params ComposeAppLogsParams) error
	// Start/restart/stop a compose app
	// (PUT /compose/{id}/status)
	SetComposeAppStatus(ctx echo.Context, id ComposeAppID) error
	// Recreate the container app
	// (PATCH /container/{id})
	RecreateContainerByID(ctx echo.Context, id ContainerID, params RecreateContainerByIDParams) error
	// Check if the container app is running healthy
	// (GET /container/{id}/healthcheck)
	CheckContainerHealthByID(ctx echo.Context, id ContainerID) error
	// Convert to compose app from another file format
	// (POST /convert)
	Convert(ctx echo.Context, params ConvertParams) error
	// Get all global settings
	// (GET /global)
	GetGlobalSettings(ctx echo.Context) error
	// Delete a global setting
	// (DELETE /global/{key})
	DeleteGlobalSetting(ctx echo.Context, key GlobalSettingKey) error
	// Get a global setting
	// (GET /global/{key})
	GetGlobalSetting(ctx echo.Context, key GlobalSettingKey) error
	// Update a global setting
	// (PUT /global/{key})
	UpdateGlobalSetting(ctx echo.Context, key GlobalSettingKey) error
	// Post a batch pull request specified images
	// (POST /image)
	PullImages(ctx echo.Context, params PullImagesParams) error
	// Get certain common information
	// (GET /info)
	Info(ctx echo.Context) error
	// (internal use ONLY)
	// (GET /web/appgrid)
	GetAppGrid(ctx echo.Context) error
	// Register an app store in Sync.
	// (POST /web/sync/appstore)
	RegisterAppStoreSync(ctx echo.Context, params RegisterAppStoreSyncParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ComposeAppStoreInfoList converts echo context to params.
func (w *ServerInterfaceWrapper) ComposeAppStoreInfoList(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ComposeAppStoreInfoListParams
	// ------------- Optional query parameter "category" -------------

	err = runtime.BindQueryParameter("form", true, false, "category", ctx.QueryParams(), &params.Category)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter category: %s", err))
	}

	// ------------- Optional query parameter "author_type" -------------

	err = runtime.BindQueryParameter("form", true, false, "author_type", ctx.QueryParams(), &params.AuthorType)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter author_type: %s", err))
	}

	// ------------- Optional query parameter "recommend" -------------

	err = runtime.BindQueryParameter("form", true, false, "recommend", ctx.QueryParams(), &params.Recommend)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter recommend: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ComposeAppStoreInfoList(ctx, params)
	return err
}

// UpgradableAppList converts echo context to params.
func (w *ServerInterfaceWrapper) UpgradableAppList(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpgradableAppList(ctx)
	return err
}

// ComposeAppStoreInfo converts echo context to params.
func (w *ServerInterfaceWrapper) ComposeAppStoreInfo(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id StoreAppIDString

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ComposeAppStoreInfo(ctx, id)
	return err
}

// ComposeApp converts echo context to params.
func (w *ServerInterfaceWrapper) ComposeApp(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id StoreAppIDString

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ComposeApp(ctx, id)
	return err
}

// ComposeAppMainStableTag converts echo context to params.
func (w *ServerInterfaceWrapper) ComposeAppMainStableTag(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id StoreAppIDString

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ComposeAppMainStableTag(ctx, id)
	return err
}

// ComposeAppServiceStableTag converts echo context to params.
func (w *ServerInterfaceWrapper) ComposeAppServiceStableTag(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id StoreAppIDString

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// ------------- Path parameter "serviceName" -------------
	var serviceName string

	err = runtime.BindStyledParameterWithLocation("simple", false, "serviceName", runtime.ParamLocationPath, ctx.Param("serviceName"), &serviceName)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter serviceName: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ComposeAppServiceStableTag(ctx, id, serviceName)
	return err
}

// AppStoreList converts echo context to params.
func (w *ServerInterfaceWrapper) AppStoreList(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.AppStoreList(ctx)
	return err
}

// RegisterAppStore converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterAppStore(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params RegisterAppStoreParams
	// ------------- Optional query parameter "url" -------------

	err = runtime.BindQueryParameter("form", true, false, "url", ctx.QueryParams(), &params.Url)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter url: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RegisterAppStore(ctx, params)
	return err
}

// UnregisterAppStore converts echo context to params.
func (w *ServerInterfaceWrapper) UnregisterAppStore(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id AppStoreID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UnregisterAppStore(ctx, id)
	return err
}

// CategoryList converts echo context to params.
func (w *ServerInterfaceWrapper) CategoryList(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CategoryList(ctx)
	return err
}

// MyComposeAppList converts echo context to params.
func (w *ServerInterfaceWrapper) MyComposeAppList(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.MyComposeAppList(ctx)
	return err
}

// InstallComposeApp converts echo context to params.
func (w *ServerInterfaceWrapper) InstallComposeApp(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params InstallComposeAppParams
	// ------------- Optional query parameter "dry_run" -------------

	err = runtime.BindQueryParameter("form", true, false, "dry_run", ctx.QueryParams(), &params.DryRun)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter dry_run: %s", err))
	}

	// ------------- Optional query parameter "check_port_conflict" -------------

	err = runtime.BindQueryParameter("form", true, false, "check_port_conflict", ctx.QueryParams(), &params.CheckPortConflict)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter check_port_conflict: %s", err))
	}

	// ------------- Optional query parameter "uncontrolled" -------------

	err = runtime.BindQueryParameter("form", true, false, "uncontrolled", ctx.QueryParams(), &params.Uncontrolled)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter uncontrolled: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.InstallComposeApp(ctx, params)
	return err
}

// UninstallComposeApp converts echo context to params.
func (w *ServerInterfaceWrapper) UninstallComposeApp(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ComposeAppID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params UninstallComposeAppParams
	// ------------- Optional query parameter "delete_config_folder" -------------

	err = runtime.BindQueryParameter("form", true, false, "delete_config_folder", ctx.QueryParams(), &params.DeleteConfigFolder)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter delete_config_folder: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UninstallComposeApp(ctx, id, params)
	return err
}

// MyComposeApp converts echo context to params.
func (w *ServerInterfaceWrapper) MyComposeApp(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ComposeAppID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.MyComposeApp(ctx, id)
	return err
}

// UpdateComposeApp converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateComposeApp(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ComposeAppID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateComposeAppParams
	// ------------- Optional query parameter "force" -------------

	err = runtime.BindQueryParameter("form", true, false, "force", ctx.QueryParams(), &params.Force)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter force: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateComposeApp(ctx, id, params)
	return err
}

// ApplyComposeAppSettings converts echo context to params.
func (w *ServerInterfaceWrapper) ApplyComposeAppSettings(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ComposeAppID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ApplyComposeAppSettingsParams
	// ------------- Optional query parameter "dry_run" -------------

	err = runtime.BindQueryParameter("form", true, false, "dry_run", ctx.QueryParams(), &params.DryRun)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter dry_run: %s", err))
	}

	// ------------- Optional query parameter "check_port_conflict" -------------

	err = runtime.BindQueryParameter("form", true, false, "check_port_conflict", ctx.QueryParams(), &params.CheckPortConflict)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter check_port_conflict: %s", err))
	}

	// ------------- Optional query parameter "uncontrolled" -------------

	err = runtime.BindQueryParameter("form", true, false, "uncontrolled", ctx.QueryParams(), &params.Uncontrolled)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter uncontrolled: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ApplyComposeAppSettings(ctx, id, params)
	return err
}

// ComposeAppContainers converts echo context to params.
func (w *ServerInterfaceWrapper) ComposeAppContainers(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ComposeAppID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ComposeAppContainers(ctx, id)
	return err
}

// CheckComposeAppHealthByID converts echo context to params.
func (w *ServerInterfaceWrapper) CheckComposeAppHealthByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ComposeAppID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CheckComposeAppHealthByID(ctx, id)
	return err
}

// ComposeAppLogs converts echo context to params.
func (w *ServerInterfaceWrapper) ComposeAppLogs(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ComposeAppID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ComposeAppLogsParams
	// ------------- Optional query parameter "lines" -------------

	err = runtime.BindQueryParameter("form", true, false, "lines", ctx.QueryParams(), &params.Lines)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter lines: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ComposeAppLogs(ctx, id, params)
	return err
}

// SetComposeAppStatus converts echo context to params.
func (w *ServerInterfaceWrapper) SetComposeAppStatus(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ComposeAppID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SetComposeAppStatus(ctx, id)
	return err
}

// RecreateContainerByID converts echo context to params.
func (w *ServerInterfaceWrapper) RecreateContainerByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ContainerID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params RecreateContainerByIDParams
	// ------------- Optional query parameter "pull" -------------

	err = runtime.BindQueryParameter("form", true, false, "pull", ctx.QueryParams(), &params.Pull)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter pull: %s", err))
	}

	// ------------- Optional query parameter "force" -------------

	err = runtime.BindQueryParameter("form", true, false, "force", ctx.QueryParams(), &params.Force)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter force: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RecreateContainerByID(ctx, id, params)
	return err
}

// CheckContainerHealthByID converts echo context to params.
func (w *ServerInterfaceWrapper) CheckContainerHealthByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ContainerID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CheckContainerHealthByID(ctx, id)
	return err
}

// Convert converts echo context to params.
func (w *ServerInterfaceWrapper) Convert(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ConvertParams
	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameter("form", true, false, "type", ctx.QueryParams(), &params.Type)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter type: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.Convert(ctx, params)
	return err
}

// GetGlobalSettings converts echo context to params.
func (w *ServerInterfaceWrapper) GetGlobalSettings(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetGlobalSettings(ctx)
	return err
}

// DeleteGlobalSetting converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteGlobalSetting(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "key" -------------
	var key GlobalSettingKey

	err = runtime.BindStyledParameterWithLocation("simple", false, "key", runtime.ParamLocationPath, ctx.Param("key"), &key)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter key: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteGlobalSetting(ctx, key)
	return err
}

// GetGlobalSetting converts echo context to params.
func (w *ServerInterfaceWrapper) GetGlobalSetting(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "key" -------------
	var key GlobalSettingKey

	err = runtime.BindStyledParameterWithLocation("simple", false, "key", runtime.ParamLocationPath, ctx.Param("key"), &key)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter key: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetGlobalSetting(ctx, key)
	return err
}

// UpdateGlobalSetting converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateGlobalSetting(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "key" -------------
	var key GlobalSettingKey

	err = runtime.BindStyledParameterWithLocation("simple", false, "key", runtime.ParamLocationPath, ctx.Param("key"), &key)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter key: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateGlobalSetting(ctx, key)
	return err
}

// PullImages converts echo context to params.
func (w *ServerInterfaceWrapper) PullImages(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params PullImagesParams
	// ------------- Optional query parameter "container_ids" -------------

	err = runtime.BindQueryParameter("form", true, false, "container_ids", ctx.QueryParams(), &params.ContainerIds)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter container_ids: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PullImages(ctx, params)
	return err
}

// Info converts echo context to params.
func (w *ServerInterfaceWrapper) Info(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.Info(ctx)
	return err
}

// GetAppGrid converts echo context to params.
func (w *ServerInterfaceWrapper) GetAppGrid(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetAppGrid(ctx)
	return err
}

// RegisterAppStoreSync converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterAppStoreSync(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params RegisterAppStoreSyncParams
	// ------------- Optional query parameter "url" -------------

	err = runtime.BindQueryParameter("form", true, false, "url", ctx.QueryParams(), &params.Url)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter url: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RegisterAppStoreSync(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/apps", wrapper.ComposeAppStoreInfoList)
	router.GET(baseURL+"/apps/upgradable", wrapper.UpgradableAppList)
	router.GET(baseURL+"/apps/:id", wrapper.ComposeAppStoreInfo)
	router.GET(baseURL+"/apps/:id/compose", wrapper.ComposeApp)
	router.GET(baseURL+"/apps/:id/stable", wrapper.ComposeAppMainStableTag)
	router.GET(baseURL+"/apps/:id/stable/:serviceName", wrapper.ComposeAppServiceStableTag)
	router.GET(baseURL+"/appstore", wrapper.AppStoreList)
	router.POST(baseURL+"/appstore", wrapper.RegisterAppStore)
	router.DELETE(baseURL+"/appstore/:id", wrapper.UnregisterAppStore)
	router.GET(baseURL+"/categories", wrapper.CategoryList)
	router.GET(baseURL+"/compose", wrapper.MyComposeAppList)
	router.POST(baseURL+"/compose", wrapper.InstallComposeApp)
	router.DELETE(baseURL+"/compose/:id", wrapper.UninstallComposeApp)
	router.GET(baseURL+"/compose/:id", wrapper.MyComposeApp)
	router.PATCH(baseURL+"/compose/:id", wrapper.UpdateComposeApp)
	router.PUT(baseURL+"/compose/:id", wrapper.ApplyComposeAppSettings)
	router.GET(baseURL+"/compose/:id/containers", wrapper.ComposeAppContainers)
	router.GET(baseURL+"/compose/:id/healthcheck", wrapper.CheckComposeAppHealthByID)
	router.GET(baseURL+"/compose/:id/logs", wrapper.ComposeAppLogs)
	router.PUT(baseURL+"/compose/:id/status", wrapper.SetComposeAppStatus)
	router.PATCH(baseURL+"/container/:id", wrapper.RecreateContainerByID)
	router.GET(baseURL+"/container/:id/healthcheck", wrapper.CheckContainerHealthByID)
	router.POST(baseURL+"/convert", wrapper.Convert)
	router.GET(baseURL+"/global", wrapper.GetGlobalSettings)
	router.DELETE(baseURL+"/global/:key", wrapper.DeleteGlobalSetting)
	router.GET(baseURL+"/global/:key", wrapper.GetGlobalSetting)
	router.PUT(baseURL+"/global/:key", wrapper.UpdateGlobalSetting)
	router.POST(baseURL+"/image", wrapper.PullImages)
	router.GET(baseURL+"/info", wrapper.Info)
	router.GET(baseURL+"/web/appgrid", wrapper.GetAppGrid)
	router.POST(baseURL+"/web/sync/appstore", wrapper.RegisterAppStoreSync)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9+2/bOPL4v0LoPsC1C9lOmmy7DXDApU3bzbfdTZDHLfbaIqalsc2NROpIyqmuyP/+",
	"BV+SKMlvp83e44fbxuJjODOcGc4Mh1+DiKUZo0ClCI6+BhnmOAUJXP91nGWXknE4PVF/xSAiTjJJGA2O",
	"gtMTxMZITgHhLENCNQvCgKhPGZbTIAwoTiE4CkgchAGHf+WEQxwcSZ5DGIhoCilWo8IXnGYJBEd7YSCL",
	"TPegEibAg/v7sATh+uJDG4briw9zgfhXDryooMh5EnROG0ylzMTRYDAhcpqP+hFLB2970KO9ovdl8CuZ",
	"Yc7OLnsOjqCEUkhO6EQD+XoK0e054/I1o+OERLINqm6CiAE2Y1zWAY9sN4HuiJzqzwLhhAOOC0QoygX0",
	"P9FPtIeGCn1D1EORHk8P5Hrr72OcCN1A3JLM/276fKJzMKS/3qgeN66Hh7EYxjhPpKOgxcKIsQQwNWhQ",
	"rCTgOMu6GOY4y5BhGowi01Iv/olijRlOgEokWfkp4+wPiCRS0D3djrMCUdBIThW1OqnHqMSEAu+Cuvyo",
	"YCdUk+yERbfAEc+pJKniiGqmvZfwYm98iF/E8cE4OjyI4TneH0WHe/Hhj9GLl+Offnzx4+Eh7B88f/ES",
	"fhzt48MXh3sv9w4O8YsInj/b32ihC5ck2mvCKCFCM2DE0hQjAWrbS4gVq5SrFfP4xLW5IbGYs6fg8OCn",
	"vZ9ePO/FL3582TscPXvew+P9ce/l85/w4fO95/HBy5edtDiBBCSobUQmb1kSA2+Db9poSkS6IRrrlrUd",
	"NQf0WPe8Mb1uTK81efyEFxc57QCKF4ohNACKUiCk3swslwhHMsdJUiD4EuWS0AkiMlSbepwnaMw4muGE",
	"xFiNhDCNkQShWjW3vG0FiNGk8Dd7+Ul1hy8Q5RZBFpS5mz7mxQ3PaTcS9PCdWHjLeASqbdeYY/1xzRHf",
	"JWyEk0uQauXvoWhj+D0UjsIT3RgJ07p7z9xCsaJ0ODt/8+vx6c3x+enN+ze/d7LleZ4kH7Ciy2mKJ9AG",
	"7ooXSnhleZJoCBPdGBHVGo05Sy01JkRIjasuxKne6+JNK6XjLDvO5ZTxqyKDtySRXdvGtEBqDIdHrTAX",
	"7Besu9zoaetw/R+HcXAU/GVQGQ8D81UM2gB5cL7GEiaMF/OgdN9XBTGy7ecIomiKZSdFHTynJ5fmxxYk",
	"l27mbq2VU/KvHBCOOBNKWSeVCSIeVl850C9AiW+gMcTzsHlVxyAiAvGqzxyEli3W5cRrqjQDZ0miFtcy",
	"F6mQ2G4OBUspG2mBbL++E+nqD5QCpmgGXCipaH8MnQFlVyMkHiVG6JkN10dEqg8VJCE6VYJYkSeXDOWZ",
	"EpN9xOQU+B0RYDvkNeCbcrf+DRGzDl/8UsZTnFTf5tmgdQx1Un4edu8N34CQr1hMQOv0C/NDZXSpH9UE",
	"QLX9ibMsIZHWKoM/BNM6a7UtXBtSzVwfqMBp4vPqX1BszCG3O34//uUDsnB8ogL4jEQgjj5RhPr9/ie6",
	"siTxwLgPW4ZZtRnrU7a22H3YRtWlxDIXayEMaJ4GRx8DITE3k7h/Ccmy4HN7py4EWRgIWsBqSouMUQHe",
	"EewDEfLs/VoQ4yQ5GwdHHxdj+RUWcGFnDO7Dr0HGWQZcWi6LsdSDEQmpWEYxB+wvILHueF9iBXOOC4WU",
	"zx2IOXsf1I56F1pLAv8Gy10OzDXljwEcpxb/FGzggD2lY7YeC1Q79BWO7a79fotdTTj9ozTe33DOuJi3",
	"wlc4dua4v9TysCa+J2VXW2wF66qE/BlwIqfa/bHS8krN8jVIQQhtbQcZUxJ1VcXhr3g5iNY2WRP7u4Tg",
	"e29rHMdEzYOTc+/7akzxG5FT4yf0Nzwb/QGRXJVRPrDJd90AlUnzKd/bO4gSNhHKYFF/dLn9VlrU49/R",
	"DeLpZXXbfPMdTkvRUE6gGP1PIOZ8eFcldtnrT7TAtdZ2hSd/kqVd4ZW36DUl313+X+tj6XcHwLrfxHcA",
	"xJoVj9hasBBeQMThexDrHcjfYHScZe84iR/9GaAC9VRCut4pwPMFP1aB4wG5xnrEoyddY2XrUG4D5bcI",
	"Eqeguic7z5NEu+O/vbya41D6ri4C12atk3On/FQn1YvqpLobxDUGdU3rEfNNYC377wzQ+oiu3SmVwKna",
	"FHwGXJ/zNwXYDYXMWMgMtjPo5w7vOv3K5FuW03hT+H9lEpkBdgazN6RruLn6N9tht9vdtLg0zuxrimeY",
	"JHhkZt4ERjsSqg+1M6DnDH6dTTiO1V+PwOOwkibyIF7Xm1ii009lUqO0olPmkI9OGKJMopQIiW91aAgL",
	"9AOhY8ZTE55nY+RG+gHdTUk0RTEDobvBFyJkPwibKwYdAFl50Se6fZc/xSw5DL70GM5IL2IxTID24Ivk",
	"uCfxRA9tTutByFI1WyYLjQmgs9UheENnO56euKh5R4zzyITu2h6WMNCJUCuDfc643DHcM5bk6Rq0+4du",
	"v1Mg7ushoo8Wk5agDkMVoGHJbp/DQBKpUV3Co8PYVEfTayGOMlpz1NysRGuJlFCS5qnO0OOA4zOaFI0M",
	"GZexp9Y3YT0b7zw90TJNzXHDGZM+A7zGAtcS63opJjSYO0PFFDlPtkngG2AeTckMBhzGYjAFHIuBmrr/",
	"b5Itnd5f3/XFB0MgT+a1sFhK/abUsR8QB5lzCjEaFUgYtS1IDDbYzQERgTAtvESzoDPe6EVeWoBELKc+",
	"EQ7CdajbFLN1IrwlNhB/giVGr3B0m2dKVIpVSDpmDbiCkR6gx8HldC4dw/BqOcJ+uC3fmj/qQJlVLQfG",
	"z4XsyCwBQB9dMPgyg4iMrdb9/MQxs42m90QGUZ+wpzpPTCfEaFGDhOR5JHOuc3mG1WzDftD0v9vF2R/V",
	"f0T/3GRX1r/1SKqkiQLX4kE3VUIGy2lwFNT2Vx268o8JG5ge93PCWx2YMItRaxt2B8SGyIXD25o18kbe",
	"LIZhR7jM0xTzQtG9Zq9tnc159PW+HQ4JAy3qVs746fYxt7c3VrttQ0T4LuGwI43oFgolhxQLKvZwGVEu",
	"XxRnWWiSF6eAZjjJwbX2tI+c2uycspfJCKkhvUKFwV5rs1mtZvKaiB3YG1MgQqMkj3W+js0qKlMvOvfH",
	"2paB1iIS9BYU3YlXXhMk8kxtLyPlGyD10anNa6p1cRlwUyZ0ipIyMfVqiND5u2FzFJPmpJqNwOUi6Wym",
	"On4/BjiNnx8GagXp80NlJpSWTUumOlSvvpJgF1aXSTvsshbQFeC0y1Is0wC7BXarfUOPzdsyrX41PgV6",
	"kwslwxy/ajWtGZHQnOUCjZVOVOw85YySf5sTRMbZhOO0j05l7RuY1gKNQN4BUCTvGGIcpYrHFX5zCVyx",
	"NeKAEyRJCiESeAxJoUZUtIHYJJpmvFDAQAGij35nOUfKuFPAFeUfOGHUqOuC5SgGbXXo7PspU5S8M2aH",
	"NEl2jEMcqt+UNeJ+nWIOsbmvIFgKii95jDLMZWEEwZTdISL/KpDkmIqUSAUhU8aN4hmi/RQg+0GXgIxh",
	"BokihE/Py/lSMgzUPmnr7KDLhFv//BI17Z1ST8e0/4eIISEz3qcgB5PpIuvz70r0K2krBuViBmr0fta9",
	"qvLktA2Lts5aXTgnNIYv/iIHO8KeuMkXJocqhtD5npozdM60xHo/RbmQLO1rqWazPRm3yZ6+YHOpk1Zk",
	"WeWjxKKX2xm0sis3WpLT4G2pr74gm/WoVqA2mstltrmQSE6x1L/kArgR23o/4MhcGmjIbN86sAt0Sli2",
	"5qRo6GYa7oaA+lJQijOfO346+Olw3fFTnJWWq47U2YFDN7P7pQGBtlNgae65aaXbcwAqpkzeJITeeoB/",
	"3MHmPcuAXmYA8RUIOahm6+3bjfyAUzzTUyxW3Gvo4AZJmpgrKdP40CSQPuXjLLsxB7FVrgiYc5bEk4TQ",
	"rWXcWw5KJUKUczAKKCaqwyjXmtFTxcKoYslY0q1/5DRPRxSTZNdC//9BkhRjQgflDP0/sk7BL0m21Gq/",
	"IpnwnU1GOOzIoOlK5fK9UdZSC+vXMOoisa7JrRYNOzjMsUAd8W4xFhNOP9WE0ecFKUYdvixnEK/szGuw",
	"qed2DgNlgm+fOrc4ba4rAae9Mml+rNh0tr/Xf9Z5daROO9XNR2Erk1UtjxYrOP3nj3HOuBSn9NoGA7YY",
	"5CyXZ+MLTCcQ3H9unlDHyiqwlxqH8wcaKgkB6Icf3lxcnF1c/vADsop4xKRkqepN8YxMjHwYYd6f7+2p",
	"pMVKq+8wFohoGAiLIDdGQ4SpOd35x1vnI0EjFhf2Ymd5LLScrwdrO1G0B/mGqL3f4bu8en2+ittd7Tkd",
	"YjpZo3nrbN952l8T2TUuedwYZ7m8YeMb7kAtRdISA2s+jlxEbC0k+umfKzroPLfcJ/qJLoqfDTuk3dDG",
	"zohAf+RCosqXUwu0eRfuurx/+uM6t4i+7VFknuPqgY8morzbVHESzyk11vlSP7ox5Ijlhg20mLlid+OF",
	"yEtIzKRzgNhi2d6ld+fM7Xa8v2PohEWVpz27nfQnrB/DrB5BMpfanG97MHv299mz/v5h/5lqP8AZ+Utz",
	"uqUuer/5Ukc9zki/taSF/nqckU5vfWstbg32yr0fb+4IG1kgGs4BhbGYkwd2r707v0YmpjnHRPKi1asC",
	"f/XPBwb7iqSA/skoLDeiKxB9CD43Uwfbq2sA7HN77a/KA+FuzNeuv2dAj0/R8fkpeq/vzLeWd9t1Hf+2",
	"uo7fOWrzUv1SwaODBu15TCxhwUzitvfF/G+pyWtqApiJPtt0xY44Ss3b3YYnyjkHKj1XvQeP86+vECQs",
	"baFd6n8z7NpbQk32sFviNxih69Pt9sNl6Qcqb6TrU7nOiDAXdO2fWry3r+VupFI7ahq0jctaXQVzLK7V",
	"I7E3ytl4TCKCk+ERuqpusWsTwPopbERFfWF3FHiISB/6aGhGHA61Y2NYHqrVD9xU+hA4VbZYDw1HxU2E",
	"BWZi4TQ2oCIBp41JVONhLd4y1KNGLE1zSmSxFPiypR0X00K31ua0DWRVqFBGVA1kY0lZUrpGQRiULYIw",
	"KCcIwiCnt5TdUUXoefZWVcgBVyUwOh2Xat7eDHOlT4UCoCL4WQVK9eOrwqDJ+/F1Dbrq12sHp1d7YnnV",
	"iWaMb3HdiZotrmg0rHvlhiglk6kODipeUaa56qn9yCkTZUEqSVLoo5/ZHcxMNNU20Z2jqTqvhCjOTbgo",
	"Ycqu1JaP3fH9EoLTcdV7ioXtG4dVUgtl6A7rwilYCBYRLPWhQQeVFCiMkwmhOLGHKr/QV4hymoAQ6E77",
	"0c1xzlvwIjf6cmY5PQkWp//UyLimi7XuK638q7VfG/LH9/O1BPoIxsZm16fO7S2XTGiC5gK4QGZwd6RV",
	"KL1fM4DeWH0D2nL9/u8NDJjDV6O2i/4NSQXvqNDgLrUAGpN/bqbFLj8Fd2TRLspR+X6Rw9o50IpTEmt/",
	"qj6gERNCmHP828iP73zP1VK/Ar25vjz6VLmUPwX3XbDaOi/zrS1XCMbKqNKZa3MO1vZ9Wteymzds7smy",
	"PIemXy2XsiK/FUrm0NtM/Fz5EGVqkX2zFAVbMC0mHCLJTMLT5tZY45JXi3pPiLuNoAT02a8ffn/a2iAK",
	"5dJaVI5RZ88MWWf75r91GHTIoItz68WqNqhRpRBH5I0SYe2FvGUcYYpUC8NzJvlG/Y1UD8WXRAo0Jtx4",
	"s7LMq6b3ZC9E+wcvlK2zf3iA8Fgq1erqBqn2T2vugFq+5RiTTjdVZYHRv0pk3TtoBBHOTU2jiGMxhVjN",
	"eAuQCWTr1ahmT+qJW3ZNWueqJXLOuF5TiO6wQLdEbzMl+lJIGVdGnTcY4ygGHD/VZZBkCYJgKTAKJS6I",
	"7KPjkVB7+W5KEih1Oc+p6HB9rZ7Q8TjSM6qpJ0QCHuj/P9rv7NNOtHCxrXbbtr9yWbGoKnO1M5/ez//d",
	"29vrUgLrRtsXuhwfQsfMk4YrhjNbkfJ58U0nnHRRBB1cJrIwCzfSK4pAiBvJboGW9RCngE1hSWsoGjFj",
	"E8BqGXIZeQ82xZ902h2OP9FxlqFfMMUTSNUOSvU/jf2ekDFERZRAaGMUOhPN6EdCJ8pKrv/l9m1odqb5",
	"l/GqhAhkpN35StwRIXI1hQmkR7lQilKEKEsAC0AzIogJnX18R+TP+QhxyJggSqlUvtWFKflPjX3uNOu8",
	"xR6fn9Y09VEwe6boxjKgOCPBUXDQ3+sfWL+npsnAJcJOoKMQ7zuQOlIolMz2b0YkSf2oJUw6nRMNBljF",
	"a5qMp3FV0KsZfdbAVHWU58ROqyaDOcUR5wVMO3q2yj+u0bddR/D+c6MK2bO9vXkbtWw3WFDu4z4Mflxl",
	"iEX3LfUOdJ59TUbD/kIaQrk6XUZB2xOxSS4wZ3kLF0pBTlkszJ7WzDLIS6tuLt88uTo7OXvawQStA0Gw",
	"CfK6Luc9DNZ0eVIbKs89a9ZyvGdc91fE4FcS3y/cc95WE/bSgxfhqzkvjj2fhzVWbOC2TIp1FsxQATDs",
	"o7NaWFf/5DLQh0qrD2vp5+XQocl0xcIUhBTamxZDpjYDjQo39Gpbf+NtX9Yg3dm+M8xzuHe4OvOU94If",
	"bq/qXP2t96ritEEt+NvJccdRBJlEIyanmojetVbrRW3WOBq6EpKmRq6L5g3NWENk1LrzQ/18dXXu6rlp",
	"1rUp/K3mQulXJFnHhKGfSqATQUfgu76GJnrXsyvuFx6gUyzRmCUJuxNrXylazNbfn5sfHxM7yRGDxCQR",
	"1XXKHXG1SStYKEZt5oE1h544t7QRr+gKT54qqLyE4PnydgH5f8GEXuq5rvDkkUg2U37qEQo2nyg7ZYbB",
	"V0vGX3EK94+CNWx5gV1yR/h1TgmDepa7f82oo752DVNrvZfwH8ub9jIxGz8El+qLuWtby/V6xhsZyo2C",
	"yA9vI2+AojDImFgHK67kce2VmfW2VP2ZnM34uaP6submNXBbqzyku75cvWu96M6O6ekW5FS1u1G+IouX",
	"JxvzeMg6B8OydPTWZD092ZKqXhnrRySlKrjWJI+9cGDdfuvJoHox7Y1kUKMa92L5oU+wFbTLV7bkaKNW",
	"hXoIxzGqfehY5i+FX2A42E7NfTOBW/kf6t64GuLcOWe5wHWvTvhvd5TvsdiHnF53vFyAMs5mxEv4ro56",
	"1kvR00kW7rWfKRbqlDcCNLRj6DTNI9Q+Z7p78jp33PYzp7hNDnElNL9NgaKhfdLnb+b5CiJaK9GvUiBj",
	"/YSISP2eUPmEkHGZ1FHRZQ1axG5xXLQPKa3gp2y/rrZCJ+81EiM73fsZxXzmrT2xMWi/r3G/3Qaqyoyv",
	"qlg7y+HvfgN27pKF+60mp5bqx5XlVVmIdwuu8p6gW4FNOt4b2/Y4UK8n/Kg0LVmbzOF/qHNNpyVkLNFv",
	"3j2og81Lx4vJeAwcaARVmYcpMTG2Ydu5af3X9oaa73uqakYp9aGoCnRGOKM6ZDbDnKiznvBW2kdv+pM+",
	"Gv7f1T+HJTo4ZAmOTPKmeadOJwD+m1FAEr50Cv+6YbHlDv2vcBGihEX6/b9m2tJCgwbLaNrx5Glm3vlD",
	"FRIU+9fenGukStVSJxeFMs2431DymicEtxa2rnD6Y5K0hkRVgEoniYjmJUHJUKpo3ErxJbSi1DImyWXn",
	"Q6tJ4YL62rb8n/m7Y/NXo7juETW4fnhz5b/OaG49TLCt7fxYpMSSXbqW+T3wK+Ft5zborNz3XbW890DW",
	"I9P3dcdFRYXW9eX1yDnVr2DoB7nn0vNVgewVKGNEmuGQIKniq6j+3PjQlcwYdt0oMZakQMNne3vo7P3Q",
	"Pk2oc0C1uH9t8uwNUO7hcc4iiHNe2dVqXp2wVUnacS7zOYlTapDmG2GvCn2T4jsymv/6yHacdrB6x46y",
	"4j6jeY/He6aCKHN/DXmK9RgtYZOdSowPbBdKsJEEmacjE8RKCAUtKcWU3VVmDNDY8bVaj7mMhKNpK7mo",
	"Zzqq05JuSMZo2Nsfzn2vVc/X/Qzufj1xtszX3pb/7BNoj1HEKXxtJ9SqJOFOq3VlbruE9kOuO5Aa2xo6",
	"FpKNzJ35z4lsG4J7HFx0KTGXA3tpYCAky9ZmJKtZS2/jnOPxylzknnEqbYsNtY/tvZr53nxG/sGPye03",
	"qx4RVzioyme/y/q9Hj+43xdxxFyLKeMQYVklgWxsQ/0Go+tTpAypumPlG9hONQ9iBeEd47dG0SUwwVFh",
	"snedKcCou9092+sf9g/0gRswTwjw6sD8lnE/FTYXgIbv3lyhucboUHuwAMcLbDrvIbftN9V2jN8y6B7U",
	"Lqtx8DLLbC5Tz8Bc0XHxzKalZRq0UNplvthr7u0nzHGWjUkCXW+Wt1Xhys/DdJRmaT3Evgtf74ba0Cec",
	"waO+wt70jGGqc8FNyUhTkMrXTymjDbpNdJWWmuDxqfYOpP8E3EaR+NYrcg+Uz5gkyKyndE6stvzB11so",
	"GpFAHw8m2OaXtFlXOHi99fWpz5tZXOUrU49IIxoEIdwgwCL8h6ux3PfCc/Mpx8eWvLsWpu25pStw8iDI",
	"3kwOr/Vo5U5kdCeRNz60PEw0Zh1KK5lWXuztTiw6Z0Jxjwt+SIayPEm8C0o26oNd1WGWi6QwbohRYYIk",
	"2ga4IbEYop4ZwHYqK6DUsrOdyXB6ItwYuk7N8r6mjKFujJ7oZyRq9mYBsitHrnpccxv7TWwoNrynPXfP",
	"E5Z6Ix1+07hzhLQ4U3a4W7xjEw1Pk0vstd1OGWzvhK2/+uoG10MEqIEr6ugqTYzWa24u2xJ3MBrgLJtw",
	"c2t7nt6xFSE2s3Eabxz74HeXkyjp4z62oVZb0MtZ3zI9+7Kg0f9StB84RVudhBWil91ArV3M12Twr+R/",
	"/KxwbS5CGDLp9+OCweyZ4oibtLxoroliJ2q/1Kan0yduu3FyYR7is4etxo5pu7HrQxgQ1dlQZ4Z4ec+u",
	"ZkBzpYtH1MswBV6q40xZGsAD03OvrTxq/WzbOW7zRLvRyKXQdS+xeTJ38ZAt4VAbpika2iNpp0hkCj2d",
	"wJhQXV7ClnK9gPHfPi1/OOtTgAbGudKmo62Ou6tpq2Nx16Re+H33U/rX+xcD0CjL/6DgrAjJToHw6/N2",
	"Q9B6Y2730y9GQbPVDkGoV9/tmrzxluyupvVKnHbN23wMdlcTNwp9dU3dfgR2V5M3SjV3Td5+PXj3G65Z",
	"KX/xvmu9KvEtQKoeXlgPuMZzFd8EzOrJgg1gbbyK8aUn8eQdZ3lmzBg7yC9W78218MO2wRG2jIWwQ82H",
	"rXNRWM56aZ/fbttv9mjkpZvO1RnhnGIbHcXRPWnTLITcrtLXLn5eB9+yays2uZht1nmhYuHjK5/vP9//",
	"/wAAAP//zcjlup+hAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
