// GENERATED by services/backup/cmd/gen-uicontract from services/backup/jobs/errors.go.
// Do not edit: change the Go file, then run `go generate ./jobs` in services/backup.
//
// Every error_code the backend can send, with its retry class and the
// one-click fixes (actions) the UI offers for it. Explain a code with
// backup.err.<code>.title / .cause / .fix and label an action with
// backup.action.<action>.

export const ERROR_CODES = Object.freeze({
	ambiguous_device: Object.freeze({ class: 'config', actions: Object.freeze(['open_storage', 'change_dest']) }),
	app_start_failed: Object.freeze({ class: 'hook', actions: Object.freeze(['view_log']) }),
	app_stop_failed: Object.freeze({ class: 'hook', actions: Object.freeze(['view_log', 'edit_hooks']) }),
	appdata_cloud_needs_archive: Object.freeze({ class: 'config', actions: Object.freeze(['switch_archive']) }),
	busy: Object.freeze({ class: 'transient', actions: Object.freeze(['retry', 'view_log']) }),
	cancelled_by_user: Object.freeze({ class: 'lifecycle', actions: Object.freeze(['retry']) }),
	cancelled_unmounted: Object.freeze({ class: 'lifecycle', actions: Object.freeze(['how_to_run', 'retry']) }),
	case_collision: Object.freeze({ class: 'config', actions: Object.freeze(['view_log', 'change_dest']) }),
	change_guard: Object.freeze({ class: 'guard', actions: Object.freeze(['review']) }),
	cloud_auth: Object.freeze({ class: 'config', actions: Object.freeze(['fix_sign_in']) }),
	cloud_quota_daily: Object.freeze({ class: 'deferred', actions: Object.freeze(['view_log']) }),
	cloud_rate_limited: Object.freeze({ class: 'transient', actions: Object.freeze(['view_log']) }),
	decision_timeout: Object.freeze({ class: 'lifecycle', actions: Object.freeze(['retry']) }),
	delete_guard: Object.freeze({ class: 'guard', actions: Object.freeze(['review']) }),
	dest_inside_source: Object.freeze({ class: 'config', actions: Object.freeze(['change_dest', 'edit_filters']) }),
	dest_marker_mismatch: Object.freeze({ class: 'guard', actions: Object.freeze(['reconnect_dest', 'change_dest']) }),
	dest_offline: Object.freeze({ class: 'transient', actions: Object.freeze(['how_to_run', 'change_dest']) }),
	empty_source: Object.freeze({ class: 'guard', actions: Object.freeze(['review', 'edit_job']) }),
	endpoint_unknown: Object.freeze({ class: 'config', actions: Object.freeze(['edit_job']) }),
	engine_unavailable: Object.freeze({ class: 'transient', actions: Object.freeze(['view_log']) }),
	fat32_file_too_large: Object.freeze({ class: 'config', actions: Object.freeze(['edit_filters', 'change_dest']) }),
	forbidden: Object.freeze({ class: 'api', actions: Object.freeze([]) }),
	internal: Object.freeze({ class: 'lifecycle', actions: Object.freeze(['view_log']) }),
	interrupted: Object.freeze({ class: 'lifecycle', actions: Object.freeze(['view_log']) }),
	invalid_filter: Object.freeze({ class: 'config', actions: Object.freeze(['edit_filters']) }),
	invalid_state: Object.freeze({ class: 'api', actions: Object.freeze([]) }),
	io_error: Object.freeze({ class: 'transient', actions: Object.freeze(['view_log', 'retry']) }),
	max_duration: Object.freeze({ class: 'lifecycle', actions: Object.freeze(['edit_job', 'view_log']) }),
	network_unreachable: Object.freeze({ class: 'transient', actions: Object.freeze(['retry', 'view_log']) }),
	no_space: Object.freeze({ class: 'config', actions: Object.freeze(['open_storage', 'change_dest']) }),
	not_found: Object.freeze({ class: 'api', actions: Object.freeze([]) }),
	path_not_allowed: Object.freeze({ class: 'config', actions: Object.freeze(['edit_job']) }),
	rate_limited: Object.freeze({ class: 'api', actions: Object.freeze([]) }),
	revision_conflict: Object.freeze({ class: 'api', actions: Object.freeze([]) }),
	source_offline: Object.freeze({ class: 'transient', actions: Object.freeze(['how_to_run', 'edit_job']) }),
	store_unavailable: Object.freeze({ class: 'api', actions: Object.freeze([]) }),
	system_disk_full: Object.freeze({ class: 'transient', actions: Object.freeze(['open_storage', 'retry']) }),
	token_invalid: Object.freeze({ class: 'api', actions: Object.freeze([]) }),
	unauthorized: Object.freeze({ class: 'api', actions: Object.freeze(['sign_in']) }),
	validation: Object.freeze({ class: 'api', actions: Object.freeze([]) }),
	vm_shutdown_timeout: Object.freeze({ class: 'hook', actions: Object.freeze(['view_log', 'edit_hooks']) }),
	vm_start_failed: Object.freeze({ class: 'hook', actions: Object.freeze(['view_log']) }),
	window_closed: Object.freeze({ class: 'config', actions: Object.freeze(['edit_job']) })
})

export const ERROR_CLASSES = Object.freeze(['transient', 'deferred', 'guard', 'config', 'hook', 'lifecycle', 'api'])

export const ACTIONS = Object.freeze(['change_dest', 'edit_filters', 'edit_hooks', 'edit_job', 'fix_sign_in', 'how_to_run', 'open_storage', 'reconnect_dest', 'retry', 'review', 'sign_in', 'switch_archive', 'view_log'])

// Values of a 400 response's field_errors besides error codes; label
// them with backup.field.<code>.
export const FIELD_CODES = Object.freeze(['required', 'invalid', 'out_of_range', 'too_many', 'invalid_cron', 'invalid_time', 'unknown_app', 'unknown_vm', 'mirror_needs_dest', 'not_resolvable', 'dest_overlaps_job'])

// errorInfo returns {class, actions} for a code; unknown codes are
// treated as internal, like the backend does.
export function errorInfo(code) {
	return ERROR_CODES[code] || ERROR_CODES.internal
}

// errorKeys returns the i18n keys explaining a code.
export function errorKeys(code) {
	const c = ERROR_CODES[code] ? code : 'internal'
	return {
		title: `backup.err.${c}.title`,
		cause: `backup.err.${c}.cause`,
		fix: `backup.err.${c}.fix`
	}
}

// fieldErrorKey returns the i18n key for a field_errors value.
export function fieldErrorKey(value) {
	if (FIELD_CODES.includes(value)) return `backup.field.${value}`
	return errorKeys(value).title
}
