// GENERATED by services/backup/cmd/gen-uicontract from services/backup/jobs/events.go.
// Do not edit: change the Go file, then run `go generate ./jobs` in services/backup.
//
// Message-bus events, received through this.$socket (vue-socket.io-extended)
// as { Properties: { ... } } with every property a string.

export const BACKUP_EVENTS = Object.freeze({
	RUN_BEGIN: 'nivaroos:backup:run-begin',
	RUN_PROGRESS: 'nivaroos:backup:run-progress',
	RUN_END: 'nivaroos:backup:run-end',
	RUN_WAITING: 'nivaroos:backup:run-waiting',
	JOB_CHANGED: 'nivaroos:backup:job-changed',
	NOTIFY: 'nivaroos:backup:notify'
})

// Properties sent with each event.
export const EVENT_PROPERTIES = Object.freeze({
	'nivaroos:backup:run-begin': Object.freeze(['run_id', 'job_id', 'kind', 'status', 'phase', 'error_code']),
	'nivaroos:backup:run-progress': Object.freeze(['run_id', 'job_id', 'kind', 'status', 'phase', 'bytes', 'total_bytes', 'files', 'total_files', 'speed_bps', 'eta_sec', 'errors', 'current_file']),
	'nivaroos:backup:run-end': Object.freeze(['run_id', 'job_id', 'kind', 'status', 'phase', 'bytes', 'total_bytes', 'files', 'total_files', 'speed_bps', 'eta_sec', 'errors', 'current_file', 'error_code', 'summary']),
	'nivaroos:backup:run-waiting': Object.freeze(['run_id', 'job_id', 'kind', 'status', 'phase', 'error_code']),
	'nivaroos:backup:job-changed': Object.freeze(['job_id', 'change', 'revision']),
	'nivaroos:backup:notify': Object.freeze(['key', 'args', 'title', 'message', 'level', 'job_id', 'run_id', 'window'])
})

export const JOB_CHANGE = Object.freeze({ CREATED: 'created', UPDATED: 'updated', DELETED: 'deleted', TOGGLED: 'toggled' })
