#!/usr/bin/env python3
"""Copies the web UI's English Backup & Sync texts into the app.

The backup service sends i18n keys and args, never English (backup spec
§12.12); the web UI renders them from ui/src/assets/lang/en_US.json. The
app renders the same keys with the same words, from
lib/backup/backup_strings.g.dart, which this writes:

    python3 mobile/tool/gen_backup_strings.py

Run it after the web's backup.* texts change. The Settings, Shortcuts and
Scheduled Tasks migration texts are left out: the app has none of those
screens.
"""
import json
import pathlib

root = pathlib.Path(__file__).resolve().parents[2]
src = root / 'ui/src/assets/lang/en_US.json'
out = root / 'mobile/lib/backup/backup_strings.g.dart'
skip = {'settings', 'shortcuts', 'migrate'}

texts = json.loads(src.read_text(encoding='utf-8'))
keys = sorted(k for k in texts if k.startswith('backup.') and k.split('.')[1] not in skip)


def dart(s):
    return "'" + s.replace('\\', '\\\\').replace("'", "\\'").replace('$', '\\$').replace('\n', '\\n') + "'"


lines = [
    '// GENERATED by mobile/tool/gen_backup_strings.py from',
    '// ui/src/assets/lang/en_US.json. Do not edit: change the web text, then',
    '// run the script again.',
    '',
    "part of 'backup_strings.dart';",
    '',
    'const Map<String, String> _en = {',
]
for k in keys:
    lines.append(f'  {dart(k)}: {dart(texts[k])},')
lines.append('};')
out.write_text('\n'.join(lines) + '\n', encoding='utf-8')
print(f'{len(keys)} texts -> {out.relative_to(root)}')
