// Package codegen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package codegen

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

const (
	Access_tokenScopes = "access_token.Scopes"
)

// Defines values for MergeStatus.
const (
	Error         MergeStatus = "error"
	Initialized   MergeStatus = "initialized"
	Uninitialized MergeStatus = "uninitialized"
)

// BaseResponse defines model for BaseResponse.
type BaseResponse struct {
	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// Merge defines model for Merge.
type Merge struct {
	CreatedAt         *time.Time `json:"created_at,omitempty"`
	Fstype            *string    `json:"fstype,omitempty"`
	Id                *int       `json:"id,omitempty"`
	MountPoint        string     `json:"mount_point"`
	SourceBasePath    *string    `json:"source_base_path,omitempty"`
	SourceVolumeUuids *[]string  `json:"source_volume_uuids,omitempty"`
	UpdatedAt         *time.Time `json:"updated_at,omitempty"`
}

// MergeStatus defines model for MergeStatus.
type MergeStatus string

// Mount defines model for Mount.
type Mount struct {
	// Extended Extended properties of the mount
	Extended   *map[string]string `json:"extended,omitempty"`
	Fstype     *string            `json:"fstype,omitempty"`
	Id         *int               `json:"id,omitempty"`
	MountPoint string             `json:"mount_point"`
	Options    *string            `json:"options,omitempty"`
	Source     *string            `json:"source,omitempty"`
}

// MountPoint defines model for MountPoint.
type MountPoint struct {
	MountPoint string `json:"mount_point"`
}

// AddMountResponseOK defines model for AddMountResponseOK.
type AddMountResponseOK struct {
	Data *Mount `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// GetMergeInitStatusResponseOK defines model for GetMergeInitStatusResponseOK.
type GetMergeInitStatusResponseOK struct {
	Data *MergeStatus `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// GetMergesResponseOK defines model for GetMergesResponseOK.
type GetMergesResponseOK struct {
	Data *[]Merge `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// GetMountsResponseOK defines model for GetMountsResponseOK.
type GetMountsResponseOK struct {
	Data *[]Mount `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// InitMergeResponseOK defines model for InitMergeResponseOK.
type InitMergeResponseOK struct {
	Data *MergeStatus `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ResponseBadRequest defines model for ResponseBadRequest.
type ResponseBadRequest = BaseResponse

// ResponseConflict defines model for ResponseConflict.
type ResponseConflict = BaseResponse

// ResponseForbidden defines model for ResponseForbidden.
type ResponseForbidden = BaseResponse

// ResponseNotFound defines model for ResponseNotFound.
type ResponseNotFound = BaseResponse

// ResponseServiceUnavailable defines model for ResponseServiceUnavailable.
type ResponseServiceUnavailable = BaseResponse

// SetMergeResponseOK defines model for SetMergeResponseOK.
type SetMergeResponseOK struct {
	Data *Merge `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// UmountResponseOK defines model for UmountResponseOK.
type UmountResponseOK = BaseResponse

// UpdateMountResponseOK defines model for UpdateMountResponseOK.
type UpdateMountResponseOK struct {
	Data *Mount `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// GetMergesParams defines parameters for GetMerges.
type GetMergesParams struct {
	// MountPoint Filter the results by mount point
	MountPoint *string `form:"mount_point,omitempty" json:"mount_point,omitempty"`
}

// UmountParams defines parameters for Umount.
type UmountParams struct {
	// MountPoint Filter the results by mount point
	MountPoint string `form:"mount_point" json:"mount_point"`
}

// GetMountsParams defines parameters for GetMounts.
type GetMountsParams struct {
	// Id Filter the results by id
	Id *string `form:"id,omitempty" json:"id,omitempty"`

	// MountPoint Filter the results by mount point
	MountPoint *string `form:"mount_point,omitempty" json:"mount_point,omitempty"`

	// Type Filter the results by type
	Type *string `form:"type,omitempty" json:"type,omitempty"`

	// Source Filter the results by source
	Source *string `form:"source,omitempty" json:"source,omitempty"`
}

// UpdateMountParams defines parameters for UpdateMount.
type UpdateMountParams struct {
	// MountPoint Filter the results by mount point
	MountPoint string `form:"mount_point" json:"mount_point"`
}

// SetMergeJSONRequestBody defines body for SetMerge for application/json ContentType.
type SetMergeJSONRequestBody = Merge

// InitMergeJSONRequestBody defines body for InitMerge for application/json ContentType.
type InitMergeJSONRequestBody = MountPoint

// MountJSONRequestBody defines body for Mount for application/json ContentType.
type MountJSONRequestBody = Mount

// UpdateMountJSONRequestBody defines body for UpdateMount for application/json ContentType.
type UpdateMountJSONRequestBody = Mount

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get merges
	// (GET /merge)
	GetMerges(ctx echo.Context, params GetMergesParams) error
	// Set a merge
	// (POST /merge)
	SetMerge(ctx echo.Context) error
	// Get merge initialization status
	// (GET /merge/init)
	GetMergeInitStatus(ctx echo.Context) error
	// Initialize a merge
	// (POST /merge/init)
	InitMerge(ctx echo.Context) error
	// Umount volume
	// (DELETE /mount)
	Umount(ctx echo.Context, params UmountParams) error
	// Get mounted volumes
	// (GET /mount)
	GetMounts(ctx echo.Context, params GetMountsParams) error
	// Mount a volume
	// (POST /mount)
	Mount(ctx echo.Context) error
	// Update a mount volume
	// (PUT /mount)
	UpdateMount(ctx echo.Context, params UpdateMountParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetMerges converts echo context to params.
func (w *ServerInterfaceWrapper) GetMerges(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMergesParams
	// ------------- Optional query parameter "mount_point" -------------

	err = runtime.BindQueryParameter("form", true, false, "mount_point", ctx.QueryParams(), &params.MountPoint)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter mount_point: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetMerges(ctx, params)
	return err
}

// SetMerge converts echo context to params.
func (w *ServerInterfaceWrapper) SetMerge(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SetMerge(ctx)
	return err
}

// GetMergeInitStatus converts echo context to params.
func (w *ServerInterfaceWrapper) GetMergeInitStatus(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetMergeInitStatus(ctx)
	return err
}

// InitMerge converts echo context to params.
func (w *ServerInterfaceWrapper) InitMerge(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.InitMerge(ctx)
	return err
}

// Umount converts echo context to params.
func (w *ServerInterfaceWrapper) Umount(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params UmountParams
	// ------------- Required query parameter "mount_point" -------------

	err = runtime.BindQueryParameter("form", true, true, "mount_point", ctx.QueryParams(), &params.MountPoint)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter mount_point: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.Umount(ctx, params)
	return err
}

// GetMounts converts echo context to params.
func (w *ServerInterfaceWrapper) GetMounts(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMountsParams
	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameter("form", true, false, "id", ctx.QueryParams(), &params.Id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// ------------- Optional query parameter "mount_point" -------------

	err = runtime.BindQueryParameter("form", true, false, "mount_point", ctx.QueryParams(), &params.MountPoint)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter mount_point: %s", err))
	}

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameter("form", true, false, "type", ctx.QueryParams(), &params.Type)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter type: %s", err))
	}

	// ------------- Optional query parameter "source" -------------

	err = runtime.BindQueryParameter("form", true, false, "source", ctx.QueryParams(), &params.Source)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetMounts(ctx, params)
	return err
}

// Mount converts echo context to params.
func (w *ServerInterfaceWrapper) Mount(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.Mount(ctx)
	return err
}

// UpdateMount converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateMount(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateMountParams
	// ------------- Required query parameter "mount_point" -------------

	err = runtime.BindQueryParameter("form", true, true, "mount_point", ctx.QueryParams(), &params.MountPoint)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter mount_point: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateMount(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/merge", wrapper.GetMerges)
	router.POST(baseURL+"/merge", wrapper.SetMerge)
	router.GET(baseURL+"/merge/init", wrapper.GetMergeInitStatus)
	router.POST(baseURL+"/merge/init", wrapper.InitMerge)
	router.DELETE(baseURL+"/mount", wrapper.Umount)
	router.GET(baseURL+"/mount", wrapper.GetMounts)
	router.POST(baseURL+"/mount", wrapper.Mount)
	router.PUT(baseURL+"/mount", wrapper.UpdateMount)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+Ra3W/bOBL/VwjePbSAbDkf7bUG8pBsr92g203RtHcHxIFBkyOZrUSq/HDiDfy/H0hK",
	"lmUrruO43hZ9iiVyPvmb4cwod5jKvJAChNG4f4cV6EIKDf7hlLF30grzoXx58da9pVIYEMb9JEWRcUoM",
	"lyL+rKVw7zQdQ078apZdJLh/dYf/qSDBffyPuBYWh306PiMaKgF4Ft3hQskClOFBB0aMZ7aOhVcSz2YR",
	"NtMCcB/L0WegBs+uI6yAsAuRTXHfKAszt4mBpooXTmvcxxdv8SzCb8C8A5XCueDm0hBj9Q9vtFM3qLob",
	"038Ii7mBXG9kOq5tJkqR6eOd4FD0EzkhgH6XTnDg9779ZbBf6XFG2Af4akGbDQyGW5IXGbifOWhNUif7",
	"jDBUsZhFj3TKJgYsCayIf5MiyTjd2o45/V6MWJRWUb6WasQZA7GtCTWDvdjQEFeR/inNa2kF29aGP6VB",
	"gcFebGiIq0gvQU04hU+CTAjPyCjouI01JSe0yGovdt0j+BJ+ojz3uAz3Kd9zBfcA1QpGDPwaFeYc7V5k",
	"Q6P+skLzuLlbYlQuIAXGKgEMjaZIg5qAQpozQDxBZgwKENeIiCmO6mjEeFnRuSnaKC5S7BUPgFvRiCog",
	"BtiQ+DNJpMrdL+c56Biew7eZRzjR4ZUzKiE2cwwSq6GbO5kq0biFiLPQlLTy5sJACsrt8yAfFpIH1NRm",
	"x69OP562cdbSKgrDEdEwLIgZL5FNiIozPoop0UTqOOEZ6DVsJjKzOQyt5Uw3Kria5TP6/MUhvHjeoUCP",
	"Osf/en7QeXn0rNd5AQekRw/ZAYGXbRKa5V2ErY+ax5zFzO34arkChvtXDd9drwC8xERZbDVOjwtuOMn4",
	"X8CQNsQ40SBs7pgurOEIW9F8BqWkcsJq9zQ3rHghBOAKMOHWgGDgUUIY4y5QSPa+sWeFVzOo/l2yQDVn",
	"JH0gIe+ZxShysRnA2tWK+mXt0JILE5O+/zPCsxYf1uCvLf4bwS+98UsALQ9WRyTL5M1QulQSWQ1DLmRE",
	"iYFUqmk3pIKTPNFRLifg8qTUBT3xyuVcJApAF4TCycG7+wNmSc+G/x6NV7f+vvLGUmp9oKseJNpZB9Qq",
	"bqaXLtcHkYRS0Hpo5JdQ0XIHujEQBgpHWJDcsTi1ZiwV/8tfdLUapOBvYRpSMxeJXL0SBrbXO6IFp8Yq",
	"8A8wEAghFBaCt1EOjJOTAX5SKEhA6Q6VmVQdfyNBHzGivjwdYKQV1WBOBnhsTKH7cazITTflZmxHVoMq",
	"r+UulXl8TuG/Y5LBR6DjOJOpjHPCRZUuw5/hiAgBaujYDwVPx2b4otcrbruFSAd4W2Uzx+g7amtuuBcx",
	"HGUW1ivM8xSRzKnwG9Hk4jIotX+NgjbxEgoGImiF/pCUZOjSSOWKB12WxDkRJAWNMr+qy1UuaGYZFyli",
	"XH/RESqIMj6tupKChZToln0Q6K4T83HMNTp9f4584tDIpSZFqN92w83Y59JKrJGISsEsNUhbOi7VyJ1f",
	"HK/XUiGutYUgjnFNrdZOfISKDIgGNOGaG8/z6g03v9sRUlBIzY1U0+snleuD21d9HXzyFEmFPksu0JW0",
	"Cr3imkrFamoWXnTTNP4ivp6ORmcj+N/TrotMbnzCaPXt6ftzHOEJKB2ic3IYsi0IUnDcx0fdXvcIR9gV",
	"HD45xHlVcKVgVqP7yceLVxdPsWehfG44Z7hfT+w8K0VyMKC0r4OXWlOeGVDeVwq0S+6uZPRnGA4QRyEf",
	"fbWgpnU6Wsxzi23at/Olr4cXRsiHvd59tfV8X9w2gZxF+Fnv6Nu0a5pVn5BtnhM1DU5DeeU1Q1Lnr1Db",
	"oBzMWDKNr2cRLqTe/CCqPhKHawK0OZNs+qAWZpP2r3EL+SZjGy+3NL07d/IlGESCm9d4eRaVwI9d1bct",
	"+utRPX4M6Fon/t8PfWhe6HqLfOFsdwjJ+Qz3e2Gyrq52Bcy2sfPOD+B83l9sCtCq42CQgYGND+BT1TXs",
	"ITM3nb+HTL0yTZpF+HgTwpZBuyd9wBE35qzHvePNKefDWE/4cnPCejzdwFLwAgpN/yKM/OvF0G3Nay4X",
	"kCwr6TWiVikQJivPHxiSItRMU20g76L/VBuJQCNAicdOGP9QqYLavmbzYEE18LqtyTO0rVsBlLN7cOkX",
	"2uDXa2uq9linbC/ek7XLLZfaBMKtOd5eZtkdt0udL7YaymASa0YOdlmULX8RbbnTSsSWWF4bDA+6x96V",
	"WfS73WE7u75a/kvi78uKj09u4dzIJtmtsC3n6af6LhkRtJgmEdfI+XpCMhDGtYFWzJtJFwXltkaTyQ0i",
	"KeGibiMF3KzNbwvfFH6gK/i+mPzRod3+hebXvPO9K5ZAvSY6FqeBHnzNOeDVtUNA+HgTwGlV5j88HMZ+",
	"IjMsJzL+E1MpZBnBf8ibTgYTyMrBQwnQpiqrV8/vPB230jWq4FW6MGbyo03yChLfyLgOxr/4AMnJYE0b",
	"O8AoDpOpJYG7FOQMbxUUouI6wrcdQ9I3StoiOLSx4b6GIFrNfXPKy/Kr3hJtRYOvZ9ez/wcAAP//qxz+",
	"jmUnAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
