// Package local_storage provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package local_storage

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
)

const (
	Access_tokenScopes = "access_token.Scopes"
)

// Defines values for MergeStatus.
const (
	Error         MergeStatus = "error"
	Initialized   MergeStatus = "initialized"
	Uninitialized MergeStatus = "uninitialized"
)

// BaseResponse defines model for BaseResponse.
type BaseResponse struct {
	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// Merge defines model for Merge.
type Merge struct {
	CreatedAt         *time.Time `json:"created_at,omitempty"`
	Fstype            *string    `json:"fstype,omitempty"`
	Id                *int       `json:"id,omitempty"`
	MountPoint        string     `json:"mount_point"`
	SourceBasePath    *string    `json:"source_base_path,omitempty"`
	SourceVolumeUuids *[]string  `json:"source_volume_uuids,omitempty"`
	UpdatedAt         *time.Time `json:"updated_at,omitempty"`
}

// MergeStatus defines model for MergeStatus.
type MergeStatus string

// Mount defines model for Mount.
type Mount struct {
	// Extended Extended properties of the mount
	Extended   *map[string]string `json:"extended,omitempty"`
	Fstype     *string            `json:"fstype,omitempty"`
	Id         *int               `json:"id,omitempty"`
	MountPoint string             `json:"mount_point"`
	Options    *string            `json:"options,omitempty"`
	Source     *string            `json:"source,omitempty"`
}

// MountPoint defines model for MountPoint.
type MountPoint struct {
	MountPoint string `json:"mount_point"`
}

// AddMountResponseOK defines model for AddMountResponseOK.
type AddMountResponseOK struct {
	Data *Mount `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// GetMergeInitStatusResponseOK defines model for GetMergeInitStatusResponseOK.
type GetMergeInitStatusResponseOK struct {
	Data *MergeStatus `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// GetMergesResponseOK defines model for GetMergesResponseOK.
type GetMergesResponseOK struct {
	Data *[]Merge `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// GetMountsResponseOK defines model for GetMountsResponseOK.
type GetMountsResponseOK struct {
	Data *[]Mount `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// InitMergeResponseOK defines model for InitMergeResponseOK.
type InitMergeResponseOK struct {
	Data *MergeStatus `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ResponseBadRequest defines model for ResponseBadRequest.
type ResponseBadRequest = BaseResponse

// ResponseConflict defines model for ResponseConflict.
type ResponseConflict = BaseResponse

// ResponseForbidden defines model for ResponseForbidden.
type ResponseForbidden = BaseResponse

// ResponseNotFound defines model for ResponseNotFound.
type ResponseNotFound = BaseResponse

// ResponseServiceUnavailable defines model for ResponseServiceUnavailable.
type ResponseServiceUnavailable = BaseResponse

// SetMergeResponseOK defines model for SetMergeResponseOK.
type SetMergeResponseOK struct {
	Data *Merge `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// UmountResponseOK defines model for UmountResponseOK.
type UmountResponseOK = BaseResponse

// UpdateMountResponseOK defines model for UpdateMountResponseOK.
type UpdateMountResponseOK struct {
	Data *Mount `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// GetMergesParams defines parameters for GetMerges.
type GetMergesParams struct {
	// MountPoint Filter the results by mount point
	MountPoint *string `form:"mount_point,omitempty" json:"mount_point,omitempty"`
}

// UmountParams defines parameters for Umount.
type UmountParams struct {
	// MountPoint Filter the results by mount point
	MountPoint string `form:"mount_point" json:"mount_point"`
}

// GetMountsParams defines parameters for GetMounts.
type GetMountsParams struct {
	// Id Filter the results by id
	Id *string `form:"id,omitempty" json:"id,omitempty"`

	// MountPoint Filter the results by mount point
	MountPoint *string `form:"mount_point,omitempty" json:"mount_point,omitempty"`

	// Type Filter the results by type
	Type *string `form:"type,omitempty" json:"type,omitempty"`

	// Source Filter the results by source
	Source *string `form:"source,omitempty" json:"source,omitempty"`
}

// UpdateMountParams defines parameters for UpdateMount.
type UpdateMountParams struct {
	// MountPoint Filter the results by mount point
	MountPoint string `form:"mount_point" json:"mount_point"`
}

// SetMergeJSONRequestBody defines body for SetMerge for application/json ContentType.
type SetMergeJSONRequestBody = Merge

// InitMergeJSONRequestBody defines body for InitMerge for application/json ContentType.
type InitMergeJSONRequestBody = MountPoint

// MountJSONRequestBody defines body for Mount for application/json ContentType.
type MountJSONRequestBody = Mount

// UpdateMountJSONRequestBody defines body for UpdateMount for application/json ContentType.
type UpdateMountJSONRequestBody = Mount

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetMerges request
	GetMerges(ctx context.Context, params *GetMergesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SetMerge request with any body
	SetMergeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SetMerge(ctx context.Context, body SetMergeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMergeInitStatus request
	GetMergeInitStatus(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// InitMerge request with any body
	InitMergeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	InitMerge(ctx context.Context, body InitMergeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Umount request
	Umount(ctx context.Context, params *UmountParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMounts request
	GetMounts(ctx context.Context, params *GetMountsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Mount request with any body
	MountWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	Mount(ctx context.Context, body MountJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateMount request with any body
	UpdateMountWithBody(ctx context.Context, params *UpdateMountParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateMount(ctx context.Context, params *UpdateMountParams, body UpdateMountJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetMerges(ctx context.Context, params *GetMergesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMergesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SetMergeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSetMergeRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SetMerge(ctx context.Context, body SetMergeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSetMergeRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetMergeInitStatus(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMergeInitStatusRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) InitMergeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInitMergeRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) InitMerge(ctx context.Context, body InitMergeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInitMergeRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Umount(ctx context.Context, params *UmountParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUmountRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetMounts(ctx context.Context, params *GetMountsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMountsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) MountWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMountRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Mount(ctx context.Context, body MountJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMountRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateMountWithBody(ctx context.Context, params *UpdateMountParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateMountRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateMount(ctx context.Context, params *UpdateMountParams, body UpdateMountJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateMountRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetMergesRequest generates requests for GetMerges
func NewGetMergesRequest(server string, params *GetMergesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/merge")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	queryValues := queryURL.Query()

	if params.MountPoint != nil {

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "mount_point", runtime.ParamLocationQuery, *params.MountPoint); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

	}

	queryURL.RawQuery = queryValues.Encode()

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSetMergeRequest calls the generic SetMerge builder with application/json body
func NewSetMergeRequest(server string, body SetMergeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSetMergeRequestWithBody(server, "application/json", bodyReader)
}

// NewSetMergeRequestWithBody generates requests for SetMerge with any type of body
func NewSetMergeRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/merge")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetMergeInitStatusRequest generates requests for GetMergeInitStatus
func NewGetMergeInitStatusRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/merge/init")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewInitMergeRequest calls the generic InitMerge builder with application/json body
func NewInitMergeRequest(server string, body InitMergeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewInitMergeRequestWithBody(server, "application/json", bodyReader)
}

// NewInitMergeRequestWithBody generates requests for InitMerge with any type of body
func NewInitMergeRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/merge/init")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewUmountRequest generates requests for Umount
func NewUmountRequest(server string, params *UmountParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/mount")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	queryValues := queryURL.Query()

	if queryFrag, err := runtime.StyleParamWithLocation("form", true, "mount_point", runtime.ParamLocationQuery, params.MountPoint); err != nil {
		return nil, err
	} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
		return nil, err
	} else {
		for k, v := range parsed {
			for _, v2 := range v {
				queryValues.Add(k, v2)
			}
		}
	}

	queryURL.RawQuery = queryValues.Encode()

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetMountsRequest generates requests for GetMounts
func NewGetMountsRequest(server string, params *GetMountsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/mount")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	queryValues := queryURL.Query()

	if params.Id != nil {

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "id", runtime.ParamLocationQuery, *params.Id); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

	}

	if params.MountPoint != nil {

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "mount_point", runtime.ParamLocationQuery, *params.MountPoint); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

	}

	if params.Type != nil {

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "type", runtime.ParamLocationQuery, *params.Type); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

	}

	if params.Source != nil {

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "source", runtime.ParamLocationQuery, *params.Source); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

	}

	queryURL.RawQuery = queryValues.Encode()

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewMountRequest calls the generic Mount builder with application/json body
func NewMountRequest(server string, body MountJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewMountRequestWithBody(server, "application/json", bodyReader)
}

// NewMountRequestWithBody generates requests for Mount with any type of body
func NewMountRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/mount")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewUpdateMountRequest calls the generic UpdateMount builder with application/json body
func NewUpdateMountRequest(server string, params *UpdateMountParams, body UpdateMountJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateMountRequestWithBody(server, params, "application/json", bodyReader)
}

// NewUpdateMountRequestWithBody generates requests for UpdateMount with any type of body
func NewUpdateMountRequestWithBody(server string, params *UpdateMountParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/mount")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	queryValues := queryURL.Query()

	if queryFrag, err := runtime.StyleParamWithLocation("form", true, "mount_point", runtime.ParamLocationQuery, params.MountPoint); err != nil {
		return nil, err
	} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
		return nil, err
	} else {
		for k, v := range parsed {
			for _, v2 := range v {
				queryValues.Add(k, v2)
			}
		}
	}

	queryURL.RawQuery = queryValues.Encode()

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetMerges request
	GetMergesWithResponse(ctx context.Context, params *GetMergesParams, reqEditors ...RequestEditorFn) (*GetMergesResponse, error)

	// SetMerge request with any body
	SetMergeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SetMergeResponse, error)

	SetMergeWithResponse(ctx context.Context, body SetMergeJSONRequestBody, reqEditors ...RequestEditorFn) (*SetMergeResponse, error)

	// GetMergeInitStatus request
	GetMergeInitStatusWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetMergeInitStatusResponse, error)

	// InitMerge request with any body
	InitMergeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*InitMergeResponse, error)

	InitMergeWithResponse(ctx context.Context, body InitMergeJSONRequestBody, reqEditors ...RequestEditorFn) (*InitMergeResponse, error)

	// Umount request
	UmountWithResponse(ctx context.Context, params *UmountParams, reqEditors ...RequestEditorFn) (*UmountResponse, error)

	// GetMounts request
	GetMountsWithResponse(ctx context.Context, params *GetMountsParams, reqEditors ...RequestEditorFn) (*GetMountsResponse, error)

	// Mount request with any body
	MountWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*MountResponse, error)

	MountWithResponse(ctx context.Context, body MountJSONRequestBody, reqEditors ...RequestEditorFn) (*MountResponse, error)

	// UpdateMount request with any body
	UpdateMountWithBodyWithResponse(ctx context.Context, params *UpdateMountParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateMountResponse, error)

	UpdateMountWithResponse(ctx context.Context, params *UpdateMountParams, body UpdateMountJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateMountResponse, error)
}

type GetMergesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data *[]Merge `json:"data,omitempty"`

		// Message message returned by server side if there is any
		Message *string `json:"message,omitempty"`
	}
	JSON503 *BaseResponse
}

// Status returns HTTPResponse.Status
func (r GetMergesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMergesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SetMergeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data *Merge `json:"data,omitempty"`

		// Message message returned by server side if there is any
		Message *string `json:"message,omitempty"`
	}
	JSON503 *BaseResponse
}

// Status returns HTTPResponse.Status
func (r SetMergeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SetMergeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetMergeInitStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data *MergeStatus `json:"data,omitempty"`

		// Message message returned by server side if there is any
		Message *string `json:"message,omitempty"`
	}
	JSON503 *BaseResponse
}

// Status returns HTTPResponse.Status
func (r GetMergeInitStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMergeInitStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type InitMergeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data *MergeStatus `json:"data,omitempty"`

		// Message message returned by server side if there is any
		Message *string `json:"message,omitempty"`
	}
	JSON503 *BaseResponse
}

// Status returns HTTPResponse.Status
func (r InitMergeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r InitMergeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UmountResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BaseResponse
	JSON400      *BaseResponse
	JSON403      *BaseResponse
	JSON404      *BaseResponse
	JSON409      *BaseResponse
}

// Status returns HTTPResponse.Status
func (r UmountResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UmountResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetMountsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data *[]Mount `json:"data,omitempty"`

		// Message message returned by server side if there is any
		Message *string `json:"message,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r GetMountsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMountsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type MountResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data *Mount `json:"data,omitempty"`

		// Message message returned by server side if there is any
		Message *string `json:"message,omitempty"`
	}
	JSON400 *BaseResponse
	JSON403 *BaseResponse
	JSON409 *BaseResponse
}

// Status returns HTTPResponse.Status
func (r MountResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r MountResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateMountResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data *Mount `json:"data,omitempty"`

		// Message message returned by server side if there is any
		Message *string `json:"message,omitempty"`
	}
	JSON400 *BaseResponse
	JSON403 *BaseResponse
	JSON404 *BaseResponse
	JSON409 *BaseResponse
}

// Status returns HTTPResponse.Status
func (r UpdateMountResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateMountResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetMergesWithResponse request returning *GetMergesResponse
func (c *ClientWithResponses) GetMergesWithResponse(ctx context.Context, params *GetMergesParams, reqEditors ...RequestEditorFn) (*GetMergesResponse, error) {
	rsp, err := c.GetMerges(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMergesResponse(rsp)
}

// SetMergeWithBodyWithResponse request with arbitrary body returning *SetMergeResponse
func (c *ClientWithResponses) SetMergeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SetMergeResponse, error) {
	rsp, err := c.SetMergeWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSetMergeResponse(rsp)
}

func (c *ClientWithResponses) SetMergeWithResponse(ctx context.Context, body SetMergeJSONRequestBody, reqEditors ...RequestEditorFn) (*SetMergeResponse, error) {
	rsp, err := c.SetMerge(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSetMergeResponse(rsp)
}

// GetMergeInitStatusWithResponse request returning *GetMergeInitStatusResponse
func (c *ClientWithResponses) GetMergeInitStatusWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetMergeInitStatusResponse, error) {
	rsp, err := c.GetMergeInitStatus(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMergeInitStatusResponse(rsp)
}

// InitMergeWithBodyWithResponse request with arbitrary body returning *InitMergeResponse
func (c *ClientWithResponses) InitMergeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*InitMergeResponse, error) {
	rsp, err := c.InitMergeWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInitMergeResponse(rsp)
}

func (c *ClientWithResponses) InitMergeWithResponse(ctx context.Context, body InitMergeJSONRequestBody, reqEditors ...RequestEditorFn) (*InitMergeResponse, error) {
	rsp, err := c.InitMerge(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInitMergeResponse(rsp)
}

// UmountWithResponse request returning *UmountResponse
func (c *ClientWithResponses) UmountWithResponse(ctx context.Context, params *UmountParams, reqEditors ...RequestEditorFn) (*UmountResponse, error) {
	rsp, err := c.Umount(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUmountResponse(rsp)
}

// GetMountsWithResponse request returning *GetMountsResponse
func (c *ClientWithResponses) GetMountsWithResponse(ctx context.Context, params *GetMountsParams, reqEditors ...RequestEditorFn) (*GetMountsResponse, error) {
	rsp, err := c.GetMounts(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMountsResponse(rsp)
}

// MountWithBodyWithResponse request with arbitrary body returning *MountResponse
func (c *ClientWithResponses) MountWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*MountResponse, error) {
	rsp, err := c.MountWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMountResponse(rsp)
}

func (c *ClientWithResponses) MountWithResponse(ctx context.Context, body MountJSONRequestBody, reqEditors ...RequestEditorFn) (*MountResponse, error) {
	rsp, err := c.Mount(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMountResponse(rsp)
}

// UpdateMountWithBodyWithResponse request with arbitrary body returning *UpdateMountResponse
func (c *ClientWithResponses) UpdateMountWithBodyWithResponse(ctx context.Context, params *UpdateMountParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateMountResponse, error) {
	rsp, err := c.UpdateMountWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateMountResponse(rsp)
}

func (c *ClientWithResponses) UpdateMountWithResponse(ctx context.Context, params *UpdateMountParams, body UpdateMountJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateMountResponse, error) {
	rsp, err := c.UpdateMount(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateMountResponse(rsp)
}

// ParseGetMergesResponse parses an HTTP response from a GetMergesWithResponse call
func ParseGetMergesResponse(rsp *http.Response) (*GetMergesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMergesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data *[]Merge `json:"data,omitempty"`

			// Message message returned by server side if there is any
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest BaseResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseSetMergeResponse parses an HTTP response from a SetMergeWithResponse call
func ParseSetMergeResponse(rsp *http.Response) (*SetMergeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SetMergeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data *Merge `json:"data,omitempty"`

			// Message message returned by server side if there is any
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest BaseResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseGetMergeInitStatusResponse parses an HTTP response from a GetMergeInitStatusWithResponse call
func ParseGetMergeInitStatusResponse(rsp *http.Response) (*GetMergeInitStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMergeInitStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data *MergeStatus `json:"data,omitempty"`

			// Message message returned by server side if there is any
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest BaseResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseInitMergeResponse parses an HTTP response from a InitMergeWithResponse call
func ParseInitMergeResponse(rsp *http.Response) (*InitMergeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &InitMergeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data *MergeStatus `json:"data,omitempty"`

			// Message message returned by server side if there is any
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest BaseResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseUmountResponse parses an HTTP response from a UmountWithResponse call
func ParseUmountResponse(rsp *http.Response) (*UmountResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UmountResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BaseResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BaseResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest BaseResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest BaseResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest BaseResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseGetMountsResponse parses an HTTP response from a GetMountsWithResponse call
func ParseGetMountsResponse(rsp *http.Response) (*GetMountsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMountsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data *[]Mount `json:"data,omitempty"`

			// Message message returned by server side if there is any
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseMountResponse parses an HTTP response from a MountWithResponse call
func ParseMountResponse(rsp *http.Response) (*MountResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &MountResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data *Mount `json:"data,omitempty"`

			// Message message returned by server side if there is any
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BaseResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest BaseResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest BaseResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseUpdateMountResponse parses an HTTP response from a UpdateMountWithResponse call
func ParseUpdateMountResponse(rsp *http.Response) (*UpdateMountResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateMountResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data *Mount `json:"data,omitempty"`

			// Message message returned by server side if there is any
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BaseResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest BaseResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest BaseResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest BaseResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}
