// Package codegen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package codegen

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v5"
)

const (
	Access_tokenScopes = "access_token.Scopes"
)

// BaseResponse defines model for BaseResponse.
type BaseResponse struct {
	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// HealthPorts defines model for HealthPorts.
type HealthPorts struct {
	TCP *[]int `json:"tcp,omitempty"`
	UDP *[]int `json:"udp,omitempty"`
}

// HealthServices defines model for HealthServices.
type HealthServices struct {
	NotRunning *[]string `json:"not_running,omitempty"`
	Running    *[]string `json:"running,omitempty"`
}

// SuccessResponseString defines model for SuccessResponseString.
type SuccessResponseString struct {
	// Data When the interface returns success, this field is the specific success information
	Data *string `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// GetHealthPortsOK defines model for GetHealthPortsOK.
type GetHealthPortsOK struct {
	Data *HealthPorts `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// GetHealthServicesOK defines model for GetHealthServicesOK.
type GetHealthServicesOK struct {
	Data *HealthServices `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ResponseClientError defines model for ResponseClientError.
type ResponseClientError = BaseResponse

// ResponseInternalServerError defines model for ResponseInternalServerError.
type ResponseInternalServerError = BaseResponse

// ResponseOK defines model for ResponseOK.
type ResponseOK = BaseResponse

// ResponseStringOK defines model for ResponseStringOK.
type ResponseStringOK = SuccessResponseString

// CheckUploadChunkParams defines parameters for CheckUploadChunk.
type CheckUploadChunkParams struct {
	// Path File path
	Path string `form:"path" json:"path"`

	// RelativePath File path
	RelativePath string `form:"relativePath" json:"relativePath"`

	// Filename File name
	Filename string `form:"filename" json:"filename"`

	// ChunkNumber chunk number
	ChunkNumber string `form:"chunkNumber" json:"chunkNumber"`

	// TotalChunks total chunks
	TotalChunks int `form:"totalChunks" json:"totalChunks"`
}

// PostUploadFileMultipartBody defines parameters for PostUploadFile.
type PostUploadFileMultipartBody struct {
	ChunkNumber      *string             `json:"chunkNumber,omitempty"`
	ChunkSize        *string             `json:"chunkSize,omitempty"`
	CurrentChunkSize *string             `json:"currentChunkSize,omitempty"`
	File             *openapi_types.File `json:"file,omitempty"`
	Filename         *string             `json:"filename,omitempty"`
	Identifier       *string             `json:"identifier,omitempty"`
	Path             *string             `json:"path,omitempty"`
	RelativePath     *string             `json:"relativePath,omitempty"`
	TotalChunks      *string             `json:"totalChunks,omitempty"`
	TotalSize        *string             `json:"totalSize,omitempty"`
}

// PostUploadFileMultipartRequestBody defines body for PostUploadFile for multipart/form-data ContentType.
type PostUploadFileMultipartRequestBody PostUploadFileMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Test file methods
	// (GET /file/test)
	GetFileTest(ctx *echo.Context) error
	// Check upload chunk
	// (GET /file/upload)
	CheckUploadChunk(ctx *echo.Context, params CheckUploadChunkParams) error
	// Upload file
	// (POST /file/upload)
	PostUploadFile(ctx *echo.Context) error
	// Get log
	// (GET /health/logs)
	GetHealthlogs(ctx *echo.Context) error
	// Get port in use
	// (GET /health/ports)
	GetHealthPorts(ctx *echo.Context) error
	// Get service status
	// (GET /health/services)
	GetHealthServices(ctx *echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetFileTest converts echo context to params.
func (w *ServerInterfaceWrapper) GetFileTest(ctx *echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetFileTest(ctx)
	return err
}

// CheckUploadChunk converts echo context to params.
func (w *ServerInterfaceWrapper) CheckUploadChunk(ctx *echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params CheckUploadChunkParams
	// ------------- Required query parameter "path" -------------

	err = runtime.BindQueryParameter("form", true, true, "path", ctx.QueryParams(), &params.Path)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter path: %s", err))
	}

	// ------------- Required query parameter "relativePath" -------------

	err = runtime.BindQueryParameter("form", true, true, "relativePath", ctx.QueryParams(), &params.RelativePath)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter relativePath: %s", err))
	}

	// ------------- Required query parameter "filename" -------------

	err = runtime.BindQueryParameter("form", true, true, "filename", ctx.QueryParams(), &params.Filename)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter filename: %s", err))
	}

	// ------------- Required query parameter "chunkNumber" -------------

	err = runtime.BindQueryParameter("form", true, true, "chunkNumber", ctx.QueryParams(), &params.ChunkNumber)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter chunkNumber: %s", err))
	}

	// ------------- Required query parameter "totalChunks" -------------

	err = runtime.BindQueryParameter("form", true, true, "totalChunks", ctx.QueryParams(), &params.TotalChunks)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter totalChunks: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CheckUploadChunk(ctx, params)
	return err
}

// PostUploadFile converts echo context to params.
func (w *ServerInterfaceWrapper) PostUploadFile(ctx *echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostUploadFile(ctx)
	return err
}

// GetHealthlogs converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealthlogs(ctx *echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetHealthlogs(ctx)
	return err
}

// GetHealthPorts converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealthPorts(ctx *echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetHealthPorts(ctx)
	return err
}

// GetHealthServices converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealthServices(ctx *echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetHealthServices(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/file/test", wrapper.GetFileTest)
	router.GET(baseURL+"/file/upload", wrapper.CheckUploadChunk)
	router.POST(baseURL+"/file/upload", wrapper.PostUploadFile)
	router.GET(baseURL+"/health/logs", wrapper.GetHealthlogs)
	router.GET(baseURL+"/health/ports", wrapper.GetHealthPorts)
	router.GET(baseURL+"/health/services", wrapper.GetHealthServices)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xY32/bthP/Vwh+vw/tIFup2wKD39J0SYtiTbCk2ENqtDR1tthIpMo7uXED/e8DScmW",
	"LDlNlnQY9tRGPN597nM/eOcbLk1eGA2akE9vuAUsjEbwf5wAvQGRUXpmLOHpO/dNGk2gyf1XFEWmpCBl",
	"dPwFjXbfUKaQC3+aZacLPr284f+3sOBT/r94ayoOchi/Egh/1DZ5Fd3wwpoCLKmAIBHkld2mogWRV1U1",
	"q6oq4gmgtKpw2PiUn77jVbR15xzsSkn4l3vUoLzdqcbUUaZA02/WGnsvp+7uSh9BsMmC0RaWt5rAapE5",
	"D8D+s5ga2ywY74O7Z9AfgqUboXOySi8f0fx5KSUgdvXvw1FFtVafhR3k090czQFRLP1BV1F9wCxQaTUk",
	"bL5mGHhGlQBTC0YpWGAKmdBrHnG4FnmRAZ9yHnELIjnV2ZpPyZYQcVoX7gRbwNvF3MNFsnD/KILc/71R",
	"/uvBRpnSBEvwEa+/CGuFg3I9WpqRFrn7dnF05iTKZI/Cl8/vqfDD67O2A5va7fmgDX2ypdbO40HTXKuV",
	"sMbgGIMS3iNqB0kV8btpHC0FwTexvrtm59Fwmj12P+wm2p8paJdKzLFvF0I2OYcMA5yIUaqQLRRkiUs3",
	"J4wFSLVQspFhSi+MzX1t8YF0m/mqAFlaRetzhzdgEv72JzJX4MtROUgpiAQsj3gd8cOSUmPV9x3tolDv",
	"oGbOme/79t5H4/ScHZ69ZYU1K5UAslyhhCwTGkyJLAdKTYJsYSxL1GIB1jValKCFVQbHH/VHfWwsU4gl",
	"uFpLWKJQlojKaIxYkYFAYCuFijw1lyeK3pRzZqEwqMjY9exJSlTgNI6XitJyPpYmj49HMNKj9eg6blA+",
	"HX/03inyqdQGzyO+AovBq9XEZY8pQItC8Sl/Pj4YP+cRLwSlntR4oTKICdB3vSVQn5kLQGJOrPF/zL1K",
	"6zl+m/Cpe8OPVQZO0jeU1rQyOTjY1zE3cnHrFagi/vI+V4ZeNZ9AZZ4Lux7C74gTS+TTS37c/uwTLxBS",
	"FpkRyV5KjlKQV3VfDarnmZFXLBXI5gCahfuQsCcaIEFGhs2B5SZRCwUJywSBfdqj0av94K8epaW+8oGy",
	"IgcCi76kuzA8ehfKTkuPXx9eHPqQjjOz5FEolK8l2PW2TupbFr6WykLS9P7tE7dbltEjGreQCVIrOHsc",
	"EF5rG8QPzLuA1XceYFq6CDFd5nPffzbWnw0b9eLvG+kH2CVDImNeHbbtTobtevGjRvqHdjfvajV7SCFv",
	"pqoq4i/uc7E9MD9+Kwh1G4ozULjTC/isinhhcKDmQ136au8V7plBCufH4djxDEivTLLeGSzzMiNVCEux",
	"ewRHzUO7DUT3IW6nTWd6mBwMzQle/Fx9h67ws4PJi0Hx0ron7Oh+tzwF0xseXnE+5XOlhc+5QdGQiDeD",
	"TWJSl2nvokpAk2uWO263Srt3xzejvqEh0U4H2oNtn5l2RXVDslf6rtxuJz0z/wKS3MBS/QfrsFtLOwXo",
	"HuHUz+txZpbYeoR7Q0cY673UMEt7NjojCWiEZEHk3er7YU7v2ycfmaETIFbnX81O8HVnWKl5KprN7Hai",
	"wgL3d/Kp95vTz/HY+cGUZiXCHT3H1ko3OKo5tfUexpAElcjMgoGQKfu82cB++cxqRYOz7c72+CACW79y",
	"/RwOa0dqZ2+lsbVn+emyu2FdztwMEH5ICNNnaTPXIVeTWAoUBrkTqNX3toYUcDNaM2HBBTVxg7D0j7Cb",
	"nEMM/Z60DY076Cxj7lggGqkEQdL457eQesbZ8aw/M12kwNqjPhNZZr6xtSkdIL/NCknsm6LUN6Vmd7Mg",
	"yVgFyIzuAsM1EuQtDJ1NwvFyPSKxPLGmLAI9tdzvvR2kF5dZ9VcAAAD///sK+3cAFgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
